from story import script
from audio.sound import VoiceLine
from story.actors import Trent, Hatcher, Darcy, Tilton, Brighton, CruiserCaptain, RedLeader, Kaitlyn, King, MajorScrew


class Msn8(object):
    MISSION_INDEX = 8


class Msn8Offer(Msn8, script.CutsceneProps):
    ALIAS = 'offer'
    TITLE = 'Предложение'
    DESCRIPTION = ''
    VOICE_LINES = [
        VoiceLine(10, Darcy, ru="", en="Hello. We're going to go into one room now, where there will be a couple of very big shots."),
        VoiceLine(20, Darcy, ru="", en="Please try to behave more restrained."),
        VoiceLine(30, Trent, ru="", en="Didn't understand anything, but I will try."),
        VoiceLine(40, Brighton, ru="", en="Ah, this is Mrs.Darcy - our beauty and a hope for a bright future."),
        VoiceLine(50, Kaitlyn, ru="", en="And this is, if I'm not mistaken, the expert on Order I was told so much about."),
        VoiceLine(60, Darcy, ru="", en="Yes, this is mister Trent. Trent, this is admiral Brighton and princess Caitlin."),
        VoiceLine(70, Brighton, ru="", en="And we have a matter of great importance for you, mister Trent."),
        VoiceLine(80, Trent, ru="", en="What?Again?"),
        VoiceLine(90, Brighton, ru="", en="Mr.Trent, let's keep it serious. The matter of discussion is Bretonian's state integrity."),
        VoiceLine(100, Trent, ru="", en="I'll try."),
        VoiceLine(110, Brighton, ru="", en="We have a mission for you ... a mission corresponding to your specialty."),
        VoiceLine(120, Trent, ru="", en="My specialty?"),
        VoiceLine(130, Brighton, ru="", en="Odrer, Mr.Trent, Order."),
        VoiceLine(140, Trent, ru="", en="Ah...Aaaaah..."),
        VoiceLine(150, Brighton, ru="", en="Mr.Trent, I must inform you, that this mission is monitored by ... the most high rank officials of Bretonia."),
        VoiceLine(160, Brighton, ru="", en="The lone fact, that Princess Caitlin is present on this meeting, should speak volumes to you."),
        VoiceLine(170, Trent, ru="", en="Of all the woes may God deliver us from both:  from their love and their wrath."),
        VoiceLine(180, Brighton, ru="", en="I don't share your scepticism, Mr.Trent, try to be more sagacious. "),
        VoiceLine(190, Brighton, ru="", en="You will do us a favor, and we, upon an opportunity, will do an offer to you in exchange."),
        VoiceLine(200, Trent, ru="", en="Okay. What the task even is?"),
        VoiceLine(210, Brighton, ru="", en="Now that's the spirit, Mr.Trent. Princess?"),
        VoiceLine(215, Kaitlyn, ru="", en="Yeah..."),
        VoiceLine(220, Brighton, ru="", en="Mr.Trent, at some point in time, Bretonia have come to some agreement with Order."),
        VoiceLine(230, Brighton, ru="", en="In essense it was summing up to Bretonia, ehem..."),
        VoiceLine(235, Brighton, ru="", en="Mr.Trent, have you heard of the Nomad problem?"),
        VoiceLine(240, Trent, ru="", en="More or less."),
        VoiceLine(250, Brighton, ru="", en="Good. A bit of caution won't hurt, you understand me?"),
        VoiceLine(260, Brighton, ru="", en="So, according to this agreement, Bretonia abandoned its interests in the sectors of so called \"The Nomad Legacy\". Do you know what I mean, Mr.Trent?"),
        VoiceLine(270, Trent, ru="", en="Slightly."),
        VoiceLine(280, Brighton, ru="", en="Ehem, okay. In return, Order pledged to restrict the access to these systems for everyone. That is, to limit it completely. Do you understand me, Mr.Trent?"),
        VoiceLine(290, Brighton, ru="", en="And we naively believed, that ASF, as a direct successor, would adhere to the established agreements. But what do we have now?"),
        VoiceLine(300, Trent, ru="", en="What?..."),
        VoiceLine(310, Brighton, ru="", en="The fact, that those bastards from IRA are colonising Tau-44 at full speed."),
        VoiceLine(320, Trent, ru="", en="Such bastards. Who's IRA by the way?"),
        VoiceLine(330, Brighton, ru="", en="Not \"who\" but \"what\". A group of fanatics, including religious ones, demanding the independence of Ireland from the Crown of Britain."),
        VoiceLine(340, Trent, ru="", en="Funny enough, considering that in the Sirius sector there is neither Ireland, nor Britain Crown."),
        VoiceLine(350, Kaitlyn, ru="", en="Mr.Trent..."),
        VoiceLine(360, Trent, ru="", en="What? As far As I know, there is no house of Ireland."),
        VoiceLine(370, Kaitlyn, ru="", en="But there are Irish, unfortunately..."),
        VoiceLine(380, Brighton, ru="", en="Do you realize now how wild this is, Mr.Trent?"),
        VoiceLine(390, Trent, ru="", en="Let's assume I do. What do you want me to do?"),
        VoiceLine(400, Brighton, ru="", en="To help us a bit. To fly to Tau-44 as a member of an operating squad and purge it from the IRA pressense."),
        VoiceLine(410, Brighton, ru="", en="Meanwhile, we suspect that ASF is directly involved in all of this. And here is where you come in handy."),
        VoiceLine(420, Trent, ru="", en="As who? As someone, who will point at someone and say \"He is from ASF\"? Doesn't sound very convincing."),
        VoiceLine(430, Kaitlyn, ru="", en="Uhhh..."),
        VoiceLine(435, Kaitlyn, ru="", en="Do fifty thosands sound convincing? You will just participate in a race, you don't have to become the winner."),
        VoiceLine(440, Trent, ru="", en="The Olympic principle? For fifty thosands? Maybe I was too quick to say that there is no Britain Crown in the Sirius sector."),
        VoiceLine(450, Kaitlyn, ru="", en="And you were smart enough to admit that. The direct leadership of this mission is on admiral Brighton, discuss all the details with him."),
        VoiceLine(460, Kaitlyn, ru="", en="Gentlemen..."),
        VoiceLine(470, Brighton, ru="", en="Trent, there is my battleship, Prince of Wales, on the orbit of the planet. Dock it, I will grant all the necessary passes and permits."),
        VoiceLine(480, Darcy, ru="", en="Trent, cya at \"Prince of Wales\"."),
    ]


class Msn8Osiris(Msn8, script.CutsceneProps):
    ALIAS = 'osiris'
    TITLE = 'Осирис'
    DESCRIPTION = ''
    VOICE_LINES = [
        VoiceLine(10, Hatcher, ru="", en="Mayo... uhhm... Sorry, general King, mayor Screw, Trent has been delivired."),
        VoiceLine(20, King, ru="", en="Thanks, Miss Hatcher."),
        VoiceLine(30, King, ru="", en="Mr.Trent, I know, it was a wild ... ehem... couple of days for you..."),
        VoiceLine(40, Trent, ru="", en="Weeks..."),
        VoiceLine(50, King, ru="",
                  en="Even mounths, but there are things beyond moral and physical exhaustion. At this moment it's very important to locate the tome of Proteus, so familiar to you, and the key. "),
        VoiceLine(60, King, ru="",
                  en="For this reason, tell me, please, everything that has happened to you since the moment Miss Hatcher ordered you to go to Sigma-19 with squad Delta."),
        VoiceLine(70, Trent, ru="", en="We were intercepted in Omicron Major, we didn't make it to Sigma-19."),
        VoiceLine(80, King, ru="", en="Intercepted by who?"),
        VoiceLine(90, Trent, ru="", en="I don't know, some tough guys from a battleship named \"Nebuchadnezzar\". Then captain Ceed helped us to escape it."),
        VoiceLine(100, King, ru="", en="Captain Ceed..."),
        VoiceLine(110, MajorScrew, ru="", en="Captain Ceed..."),
        VoiceLine(120, Trent, ru="", en="Then agent Rockford contacted me. Or rather I contacted him..."),
        VoiceLine(130, King, ru="", en="Rockford?"),
        VoiceLine(140, Trent, ru="",
                  en="Rockford. And he helped me retrieve the artifacts. But later it turned out he wanted to retrieve them to himself, and tried to destroy me. And he almost managed to."),
        VoiceLine(145, Trent, ru="", en="In the very last moment, I sliped and saved this:"),
        VoiceLine(150, King, ru="", en="So Rockford knows"),
        VoiceLine(160, MajorScrew, ru="", en="And in the game"),
        VoiceLine(170, King, ru="", en="And in the game ... yet... We need to fix that."),
        VoiceLine(180, MajorScrew, ru="",
                  en="At this moment he is somewhere around  state of New Order. We need an agent in New Order. An agent, that will track down his coordinates."),
        VoiceLine(190, King, ru="", en="And will you provide him to us?"),
        VoiceLine(200, MajorScrew, ru="",
                  en="No, I won't. There are only a few of my agents left in the Order, they are being shot like partridges there."),
        VoiceLine(210, King, ru="", en="Perhaps... Mr.Trent will help us?"),
        VoiceLine(220, Hatcher, ru="",
                  en="Trent has wasted two artifacts, one cover squadron, and what are we going to offer him? To become an agent in Order ... General King, are you out of your mind???"),
        VoiceLine(230, MajorScrew, ru="", en="Let alone he probably is an agent of Order."),
        VoiceLine(240, King, ru="",
                  en="But I trust this guy. Trent, let's do it this way: you're helping us, and we're going to erase your background before ASF and paying you triple the rate."),
        VoiceLine(250, Trent, ru="",
                  en="You know what? Screw you, general King. Lately, the only thing I'm doing is trying to fix my reputation and get big money."),
        VoiceLine(260, Trent, ru="",
                  en="But it always ends up with me being hunted and accused in even more severe crimes."),
        VoiceLine(270, MajorScrew, ru="",
                  en="General King, can you remind us what was the name of the agent we introduced into the Order before Trent?"),
        VoiceLine(280, King, ru="", en="Who cares? We lost contact to him, he must be dead."),
        VoiceLine(290, MajorScrew, ru="", en="Nevertheless, General."),
        VoiceLine(300, King, ru="", en="Alaric. I think, Alaric."),
        VoiceLine(310, Trent, ru="", en="Bastards! What happened to Alaric?"),
        VoiceLine(320, MajorScrew, ru="", en="We don't know. We lost contact to him somewhere at Kusari teritory. "),
        VoiceLine(330, Hatcher, ru="",
                  en="He almost made it. He had to transfer a data base to us, but he did not get in touch. We don't know who got their hands on Alaric and his information."),
        VoiceLine(340, King, ru="",
                  en="You can help us and your friend. Find him, transfer the date your friend was supposed to transfer and you're free."),
        VoiceLine(345, King, ru="", en="And don't even think about doing anything stupid, don't even think. "),
        VoiceLine(350, Trent, ru="", en="Fine..."),
        VoiceLine(360, King, ru="", en="Miss Hatcher, retrieve all data on Agent Alaric and hand it over to mister Trent."),
        VoiceLine(370, King, ru="",
                  en="Next, your task will be to escortthe  tome of Proteus along with Trent and Miss Darcy to the research base."),
        VoiceLine(380, Hatcher, ru="", en="Roger!"),
    ]

class Msn8Space(Msn8, script.SpaceVoiceProps):
    VOICE_LINES = [
        VoiceLine(0, Darcy,
                  ru='Привет, Трент! По поводу твоей просьбы... Встретимся на планете Авалон, все подробности на месте. До встречи.',
				  en="Hey, Trent! About your request... Let's meet on planet Avalon. I'll give you all the details in person. See you there."),
        VoiceLine(10, Darcy, ru='Трент, координаты линкора загружены в твою нейросеть. Давай быстрее.', en="Trent, the battleship's coordinates are loaded into your neural net. Step on it."),
        VoiceLine(15, Darcy, ru='После стыковки сразу готовь свой корабль к операции. Вылетай по готовности', en="Once you're docked, prep your ship for the op immediately. Launch as soon as you're ready!"),

        VoiceLine(7010, Brighton,
                  ru='В ваше задание внесены небольшие коррективы. Пришли новые данные от нашей разведки.',
				  en="Your mission parameters have been adjusted. We've received new intelligence."),
        VoiceLine(7020, Brighton,
                  ru='База ИРА в Тау-44 уничтожена, и есть подозрение, что в ее обломках нам оставили сюрприз.',
				  en="The IRA base in Tau-44 has been destroyed, and there is reason to believe a... surprise was left for us in the debris."),
        VoiceLine(7030, Brighton,
                  ru='С учетом этих обстоятельств, вам и Дерси, как частным лицам, предписывается вылететь в сектор и разобраться, что же там произошло.',
				  en="Given these circumstances, you and Darcy, operating as private contractors, are to proceed to the sector and investigate what happened."),
        VoiceLine(7040, Trent, ru='Ну если предписывается...', en="Well, if it's an order..."),
        VoiceLine(7050, Brighton, ru='Для вашего прикрытия я выделю отряд быстрого реагирования.', en="For your cover, I'm assigning a rapid response team to your position."),
        VoiceLine(7060, Darcy, ru='Вас поняли, адмирал.', en="Understood, Admiral."),

        VoiceLine(20, Trent, ru='Ничего себе местечко...', en="What a place..."),
        VoiceLine(30, Darcy, ru='Нужно провести разведку. Я отмечу навигационные точки в твоей нейросети.', en="We need to scout the area. I'm marking nav points in your neural net."),
        VoiceLine(40, Trent, ru='Подозрительно тихо', en="It's suspiciously quiet..."),
        VoiceLine(50, Darcy, ru='Трент, за мной! Я, кажется, нашла базу...', en="Trent, on me! I think I've found a base..."),
        VoiceLine(60, Trent,
                  ru='Да тут целое кладбище истребителей. У меня на радаре ничего кроме металлолома. У тебя как?', en="It's a whole graveyard of fighters. My scanners are picking up nothing but debris. You getting anything?"),
        VoiceLine(70, Darcy, ru='Аналогично. Обломки расположены очень плотно.', en="Same here. The wreckage is incredibly dense."),
        VoiceLine(80, Trent, ru='Судя по всему, их выпускали через шлюзы не штатно, не по одному, а по два.', en="Looks like they were deploying through the airlocks in an emergency protocol—not one at a time, but in pairs."),
        VoiceLine(90, Trent,
                  ru='Достаточно рискованный трюк, но если действовать четко и грамотно, позволяет увеличить скорость развертывания истребительных звеньев почти вдвое.',
				  en="It's a risky maneuver, but if executed precisely, it can double your fighter deployment rate."),
        VoiceLine(100, Darcy,
                  ru='Получается, вылетали по боевой тревоге, причем все произошло внезапно, у них не было времени на подготовку.', en="So they scrambled on a combat alert. Whatever happened, it was sudden. They had no time to prepare."),
        VoiceLine(110, Trent, ru='Дерси, смотри, у них тут неподалеку форпост... был...', en="Darcy, look. They had an outpost nearby... had."),
        VoiceLine(120, Darcy, ru='Похоже на научную лабораторию.', en="Looks like a science lab."),
        VoiceLine(130, Trent, ru='А изучали они вот это...', en="And they were studying... that."),
        VoiceLine(140, Darcy, ru='А, кстати, что это?', en="Yeah, by the way, what is that?"),
        VoiceLine(150, Brighton, ru='Дерси, сблизьтесь с объектом и проведите сканирование.', en="Darcy, move in closer and run a scan on the object."),
        VoiceLine(160, Darcy, ru='Сближаюсь...', en="Moving in..."),
        VoiceLine(170, Trent, ru='А черт его знает, что это. Похоже на гигантскую летающую тарелку.', en="Hell if I know what it is. Looks like a giant flying saucer."),
        VoiceLine(180, Brighton,
                  ru='Мы обнаружили вход в объект. Дерси, Трент, выдвигайтесь внутрь объекта, действуйте по обстановке.',
				  en="We've located an entrance to the object. Darcy, Trent, move inside and proceed as the situation dictates."),
        VoiceLine(190, Darcy, ru='Принято.', en="Acknowledged."),
        VoiceLine(200, Trent, ru='А это еще кто? Откуда здесь корабли Либерти?', en="And who are these guys? Since when does Liberty operate here?"),
        VoiceLine(210, Darcy, ru='Внимание неопознанным кораблям! С вами говорит…', en="Attention, unidentified vessels! This is..."),
        VoiceLine(220, Darcy, ru='А, черт!', en="Ah, damn it!"),
        VoiceLine(230, Trent, ru='А они вовсе не дружелюбные.', en="They're not friendly at all!"),
        VoiceLine(240, Trent, ru='О как. А в этой системе не жалуют долгие разговоры.', en="Well, well. Seems like folks in this system aren't big on long conversations."),
        VoiceLine(250, Brighton,
                  ru='Нам необходимо исследовать объект изнутри. С большой степенью вероятности, его поверхность значительно ослабляет все виды входящих и исходящих сигналов.',
				  en="We need to investigate the object's interior. It's highly probable that its hull significantly dampens all incoming and outgoing signals."),
        VoiceLine(260, Brighton,
                  ru='Звено прикрытия должно остаться у входа и работать в качестве ретрансляторов и, заодно, охранять вход на случай незваных гостей.',
				  en="The cover wing will remain at the entrance to act as relays and, additionally, guard the entrance against any uninvited guests."),
        VoiceLine(270, Trent, ru='Принято. Дерси, я веду, прикрывай мне задницу.', en="Roger that. Darcy, I'm on point, you watch my ass."),
        VoiceLine(280, Darcy, ru='Окей, грех не прикрыть такую задницу.', en="Okay, with an ass like that, it'd be a sin not to watch it."),
        VoiceLine(290, Darcy, ru='Эксперт, это место тебе ничего не напоминает?', en="Expert, does this place remind you of anything?"),
        VoiceLine(300, Trent, ru='Номадская Сфера.', en="A Nomad Sphere."),
        VoiceLine(310, Darcy, ru='Именно. Это объект кочевников.', en="Exactly. It's a Nomad construct."),
        VoiceLine(320, Trent, ru='Тупик. Твои предложения?', en="Dead end. Any ideas?"),
        VoiceLine(330, Darcy, ru='Трент, нам нужно пройти через эту дверь.', en="Trent, we need to go through this door."),
        VoiceLine(340, Trent, ru='Но её нет.', en="But there is no door."),
        VoiceLine(350, Darcy, ru='Ну так сделай её.', en="Well, then make one."),
        VoiceLine(360, Trent, ru='Женщина, я начинаю тебя бояться.', en="Woman, you're starting to scare me."),
        VoiceLine(370, Darcy, ru='Ядро? А, черт...', en="A core? Ah, damn it..."),
        VoiceLine(380, Trent, ru='Это мы удачно зашли.', en="Well, this is just perfect..."),
        VoiceLine(390, Tilton,
                  ru='Трент??? А ты здесь откуда? Да еще и в компании бретонского офицера. Я вас сюда не приглашал.',
				  en="Trent??? What are you doing here? And in the company of a Bretonian officer, no less. I didn't invite you!"),
        VoiceLine(400, Trent, ru='Тилтон. Ты сам-то здесь какими судьбами? И "здесь" - это где?', en="Tilton. What are you doing here yourself? And \"here\" being where, exactly?"),
        VoiceLine(410, Tilton,
                  ru='Я расскажу, Трент. Вы только не делайте резких движений, а то мои ребята тебя с твоей бретонкой вмиг испепелят.',
				  en="I'll tell you, Trent. Just don't make any sudden moves, or my boys will turn you and your Bretonian girlfriend to dust in a second."),
        VoiceLine(420, Darcy, ru='"Твоей бретонкой"? Ты кто такой...', en="Bretonian girlfriend? Who the hell do you think..."),
        VoiceLine(430, Trent, ru='Дерси, не сейчас.', en="Darcy, not now."),
        VoiceLine(440, Tilton,
                  ru='Да, Дерси, послушай своего голубка, целее будешь, перевес по стволам на моей стороне. Капитан Уорфиш, орудия крейсера готовы?',
				  en="Yes, Darcy, listen to your boyfriend, it's for your own good. I have the firepower advantage here. Captain Warfish, are the cruiser's batteries ready?"),
        VoiceLine(450, CruiserCaptain, ru='Накопители заряжены на сорок три процента.', en="Capacitors charged to forty-three percent."),
        VoiceLine(460, Tilton,
                  ru='У нас есть пара минут, Трент. Что такое "здесь"? "Здесь" - это Логово кочевников. Какими я здесь судьбами? По поручению моего правительства.',
				  en="We have a couple of minutes, Trent. What is \"here\"? \"Here\" is the Nomad's Lair. What am I doing here? On the orders of my government."),
        VoiceLine(470, Tilton,
                  ru='Орден предал нас. Правительство Либерти покровительствовало Ордену во время его становления как никакое другое, но как только Орден вошел в силу, все это было забыто.',
				  en="The Order betrayed us. The Liberty government patronized The Order during its formation like no other, but as soon as The Order gained power, all that was forgotten."),
        VoiceLine(480, Tilton,
                  ru='Все данные по технологиям кочевников были изъяты и засекречены верхушкой Ордена. После его раскола, нашим агентам удалось получить доступ к части архива СБА, относящейся к Логову кочевников.',
				  en="All data on Nomad technology was seized and classified by the Order's top brass. After the schism, our agents managed to access a part of the ASF archive related to the Nomad's Lair."),
        VoiceLine(490, Tilton,
                  ru='Это - огромный завод по производству ударных звеньев истребителей кочевников. Если я смогу его запустить, он будет бесконечно производить зерна кочевников.',
				  en="This is a massive factory for producing Nomad fighter wings. If I can activate it, it will endlessly produce Nomad seeds."),
        VoiceLine(500, Tilton,
                  ru='Каждое такое зерно, направленное в сторону противника, раскрывается в виде роя истребителей...',
				  en="Each such seed, directed at an enemy, unfolds into a swarm of fighters..."),
        VoiceLine(510, CruiserCaptain, ru='Накопители заряжены.', en="Capacitors are charged."),
        VoiceLine(520, Tilton, ru='И вам выпала честь присутствовать при этом историческом моменте.', en="And you have the honor of witnessing this historic moment."),
        VoiceLine(530, Darcy, ru='Сумасшедший ублюдок.', en="You crazy bastard."),
        VoiceLine(540, Trent,
                  ru='Тилтон, а ты уверен, что после "запуска" все будет так, как ты сказал? Что ничего не взорвется? Что там истребители кочевников не начнут атаковать нас?',
				  en="Tilton, are you sure that after the \"activation\" everything will go as you said? That nothing will explode? That the Nomad fighters won't start attacking us?"),
        VoiceLine(550, Tilton, ru='Капитан Уорфиш, огонь.', en="Captain Warfish, fire."),
        VoiceLine(560, CruiserCaptain, ru='Э-ээ... Коммандер Тилтон, вы точно уверены?', en="Uh... Commander Tilton, are you absolutely sure?"),
        VoiceLine(570, Tilton,
                  ru='Да! Твою мать, да! И если ты сейчас же не выстрелишь, Уорфиш, клянусь, я поднимусь к тебе на мостик и размозжу твою башку о ближайшую переборку.',
				  en="Yes! Goddammit, yes! And if you don't fire right now, Warfish, I swear I'll come up to your bridge and smash your head against the nearest console."),
        VoiceLine(580, Darcy, ru='Трент, пора валить отсюда, не находишь?', en="Trent, it's time to get the hell out of here, don't you think?"),
        VoiceLine(590, Trent, ru='Полностью согласен.', en="Couldn't agree more."),
        VoiceLine(600, Brighton, ru='Рад видеть вас целыми и невредимыми', en="Good to see you both in one piece."),
        VoiceLine(610, Darcy, ru='Брайтон... Линкор "Принц Уэльский"?', en="Brighton... The battleship \"Prince of Wales\"?"),
        VoiceLine(620, Brighton, ru='Мы решили вам чуточку помочь. Вытащить вас из этой передряги.', en="We thought we'd lend a hand. Get you out of this mess."),
        VoiceLine(630, Trent, ru='А вот эти ребята из Либерти с вами не согласны...', en="Well, the boys from Liberty seem to disagree with that plan..."),
        VoiceLine(640, Brighton,
                  ru='Переговоры с ребятами из Либерти беру на себя. Вы лучше скажите, что это за гадость регулярно вылетает из объекта?',
				  en="I'll handle the negotiations with the boys from Liberty. Why don't you tell me what that... nastiness is that keeps spewing out of the object?"),
        VoiceLine(650, Trent, ru='Зерна кочевников. У объекта спровоцировали зерноизвержение.', en="Those are Nomad seeds. We didn't just wake the beast... we gave it a damn seed-gasm."),
        VoiceLine(660, Brighton,
                  ru='Это большая проблема... Но наши энергетики подсказывают, что есть способ выключить это безобразие.',
				  en="This is a major problem... But our engineers suggest there's a way to shut this disgrace down."),
        VoiceLine(670, Brighton,
                  ru='Объект перенасыщен энергией, и процесс перенасыщения продолжается. Не знаю, что там сломали эти идиоты из Либерти, но нужно срочно все исправить, иначе никому мало не покажется...',
				  en="The object is oversaturated with energy, and the process is continuing. I don't know what those Liberty idiots broke in there, but we need to fix it now, or we're all in deep trouble..."),
        VoiceLine(680, Brighton,
                  ru='Трент, слушай внимательно. Энергия ядра объекта передается по специальным стойкам. Если их уничтожить, поступление энергии в ядро прекратится и последует разгрузка.',
				  en="Trent, listen carefully. The core's energy is channeled through specialized conduits. Destroy them, and the energy flow to the core will cease, forcing an emergency discharge."),
        VoiceLine(690, Brighton, ru='Трент, Дерси, срочно уничтожьте колонны.', en="Trent, Darcy, destroy the columns, now!"),
        VoiceLine(700, Trent, ru='Понял, работаю.', en="Understood, on it."),
        VoiceLine(710, Darcy, ru='Так точно!', en="Yes, sir!"),
        VoiceLine(720, Brighton, ru='Вот незадача... Всем покинуть корабль!!! Нас чуточку уничтожили...', en="Well, that's unfortunate... All hands, abandon ship!!! We've been... slightly destroyed."),
        VoiceLine(730, Trent, ru='Дерси, уходим, сейчас все рванет!', en="Darcy, we're leaving, this whole place is about to blow!"),
        VoiceLine(740, Darcy, ru='Трент, я за тобой. Брайтон эвакуируйся с корабля, мы тебя подберем!', en="Trent, I'm right behind you. Brighton, evacuate the ship, we'll pick you up!"),
        VoiceLine(750, Brighton,
                  ru='Дерси, капитан покидает тонущее судно последним. Следуйте за Трентом, это приказ.',
				  en="Darcy, the captain is the last to leave a sinking ship. Follow Trent, that's an order."),
        VoiceLine(760, Darcy, ru='Брайтон, ты последний, все его уже покинули!', en="Brighton, you ARE the last! Everyone else is gone!"),
        VoiceLine(770, Brighton, ru='Дерси, иногда капитан предпочитает пойти на дно вместе со своим кораблем.', en="Darcy, sometimes a captain prefers to go down with his ship."),
        VoiceLine(780, Darcy, ru='Почему, Брайтон?', en="Why, Brighton?"),
        VoiceLine(790, Brighton,
                  ru='Потому что так было с моим отцом во время восьмидесятилетней войны, с моим дедом, во время предыдущей войны и прадедом во время войны, которую уже никто не помнит.',
				  en="Because my father did during the Eighty Years' War. And my grandfather in the war before that. And my great-grandfather in a war nobody even remembers anymore."),
        VoiceLine(800, Brighton, ru='Ребятки, уходите отсюда как можно дальше, сдается мне, сейчас чуточку рванет...', en="Kids, get as far away from here as you can. I have a feeling things are about to get... slightly explosive..."),
        VoiceLine(810, Darcy,
                  ru='Трент, Брайтон был единственным... Единственным человеком... Единственным стоящим человеком среди всех этих...',
				  en="Trent, Brighton was the only... The only man... The only decent man among all these..."),
        VoiceLine(820, Trent, ru='Я понимаю, Дерси, но нам надо...', en="I know, Darcy, but we need to..."),
        VoiceLine(830, Hatcher, ru='Вам надо замереть на месте и даже не дышать.', en="What you need to do is freeze. Don't even breathe."),
        VoiceLine(840, Trent, ru='Хетчер.', en="Hatcher"),
        VoiceLine(850, Hatcher, ru='Мистер Трент. Вы меня не забыли?', en="Mister Trent. You haven't forgotten me, I hope?"),
        VoiceLine(860, Trent, ru='Мисс Хетчер, вы незабываемы.', en="Miss Hatcher, you are... unforgettable."),
        VoiceLine(870, Hatcher,
                  ru='Ну ты и засранец, Трент. Красный-один, держите этого персонажа на мушке, если рыпнется - разрешаю открыть огонь на поражение. Отвечаешь за него головой...',
				  en="You're a real piece of work, Trent. Red Leader, keep your sights locked on this character. If he twitches, you are weapons-free. You are personally responsible for him."),
        VoiceLine(880, RedLeader, ru='Принял.', en="Copy that."),
        VoiceLine(890, Hatcher,
                  ru='Итак, что тут случилось? И, Трент, почему, стоит мне увидеть на горизонте прорыв какого-нибудь дерьма, ты обязательно оказываешься рядом? Ты ассенизатор? Сантехник? КТО ТЫ, ТВОЮ МАТЬ???',
				  en="So, what happened here? And Trent, why is it that every time some shit hits the fan on the horizon, you're always nearby? Are you a shit-magnet? A plumber? WHO THE HELL ARE YOU?!"),
        VoiceLine(900, Darcy,
                  ru='Наверное, лучше я расскажу. Один из ваших - коммандер Тилтон - решил запустить фабрику кочевников по производству боевых истребителей.',
				  en="Perhaps it's better if I explain. One of your own — Commander Tilton — decided to activate a Nomad factory to produce fighter wings."),
        VoiceLine(910, Darcy,
                  ru='Но вместо этого перегрузил ее и пустил вразнос, при этом погиб его крейсер, линкор "Принц Уэльский" пришедший к нам на выручку, и куча людей с обеих сторон.',
				  en="Instead, he overloaded it and caused a chain reaction, which resulted in the destruction of his cruiser, the battleship Prince of Wales that came to our aid, and countless people on both sides."),
        VoiceLine(920, Hatcher,
                  ru='Тилтон... Больной ублюдок с манией величия... Я надеюсь, он мучился перед смертью.',
				  en="Tilton... A sick bastard with a god complex... I hope he suffered."),
        VoiceLine(930, Hatcher,
                  ru='Хорошо. Вы проследуете со мной до нашей базы. Красный-один, вы остаетесь рядом с обломками объекта, начните поверхностное изучение, я пришлю вам с базы яйцеголовых в помощь.',
				  en="Fine. You will accompany me to our base. Red Leader, you are to remain here with the object's debris and begin a preliminary survey. I'll send some eggheads from the base to assist you."),
        VoiceLine(940, RedLeader, ru='Так точно!', en="Yes, ma'am!"),
        VoiceLine(950, Hatcher, ru='Дерси, вы успели побывать внутри объекта до его активации?', en="Darcy, were you inside the object before it was activated?"),
        VoiceLine(960, Darcy, ru='Да.', en="Yes."),
        VoiceLine(970, Hatcher, ru='Не приходит на ум никаких аналогий между увиденным там и...', en="Does anything you saw inside remind you of..."),
        VoiceLine(980, Trent, ru='Хетчер, может спросишь у меня?', en="Hatcher, why don't you ask me?"),
        VoiceLine(990, Hatcher,
                  ru='Я? Нет, на базе тебя будет допрашивать группа гораздо более умелых людей. И допросят тебя с пристрастием, не сомневайся.',
				  en="Me? No. At the base, a team of far more skilled interrogators will be asking you the questions. And they will be VERY thorough, I assure you."),
        VoiceLine(1000, Darcy, ru='Где это мы? Энтерпрайз?', en="Where are we? The Enterprise?"),
        VoiceLine(1010, Hatcher, ru='Да. Основная база СБА.', en="Yes. The primary ASF headquarters."),
        VoiceLine(1020, Darcy, ru='Шансы на то, что меня отсюда выпустят живой близятся к нулю.', en="My chances of leaving this place alive are approaching zero."),
        VoiceLine(1030, Hatcher, ru='Это будет зависеть от тебя.', en="That depends entirely on you."),
        VoiceLine(1040, Trent, ru='Это будет зависеть от хозяев мисс Хетчер.', en="That depends on Miss Hatcher's superiors."),
        VoiceLine(1050, Darcy, ru='Я думала, Энтерпрайз - это станция, а оказалось, это - целая система.', en="I thought the Enterprise was a station. Turns out it's an entire system."),
        VoiceLine(1060, Trent, ru='Зря ты это сказала. Теперь тебя точно не выпустят отсюда живой.', en="You shouldn't have said that. Now they'll definitely never let you leave alive."),
        VoiceLine(1070, Hatcher, ru='Не обращайте внимания на Трента, он, по своему обыкновению, паясничает.', en="Ignore Trent. He's clowning around, as usual."),
        VoiceLine(1080, Trent, ru='А что, нас даже не убьют?', en="What, you're not even going to kill us?"),
        VoiceLine(1090, Hatcher, ru='Если бы моя воля - то непременно, а так - как себя вести будете.', en="If it were up to me, absolutely. But as it stands, it depends on your behavior."),
        VoiceLine(1100, Trent, ru='Хетчер, теперь ты можешь мне спокойно рассказать, что же произошло с Алариком?', en="Hatcher, can you calmly tell me now what happened to Alaric?"),
        VoiceLine(1110, Hatcher,
                  ru='Могу, но тебе не понравится. Когда ты исчез в неизвестном направлении, Аларик, как будто взбесился.',
				  en="I can, but you won't like it. After you vanished, Alaric... went berserk."),
        VoiceLine(1120, Hatcher,
                  ru='Говорил, что его друг - герой, и он должен соответствовать. Его было решено использовать как агента в Ордене.',
				  en="Said his friend was a hero and that he had to measure up. The decision was made to use him as an agent within The Order."),
        VoiceLine(1130, Hatcher,
                  ru='Тем более, что такой обалдуй прижился там буквально сразу же. Перед тем как связь оборвалась, он обещал нам переслать некие секретные документы, но мы их так и не получили.',
				  en="And that fool managed to fit in there almost immediately. Right before his comms went dead, he promised to send us some secret documents, but we never received them."),
        VoiceLine(1140, Hatcher,
                  ru='Мы в системе Сириус. Направляемся к планете Спрага. Мисс Дэрси, не могли бы вы связаться с вашим штабом и рассказать про бой в Тау-44.',
				  en="We're in the Sirius system, heading for the planet Sprague. Miss Darcy, could you contact your command and brief them about the engagement in Tau-44?"),
        VoiceLine(1150, Darcy, ru='Уже. Мое начальство одобрило сотрудничество с СБА и с вами конкретно.', en="Already done. My superiors have approved cooperation with the ASF, and with you specifically."),
        VoiceLine(1160, Trent, ru='Какая милота. Я вам не мешаю?', en="How adorable. Am I interrupting?"),
        VoiceLine(1170, Darcy, ru='Трент, не будь ребенком.', en="Trent, don't be a child."),
        VoiceLine(4900, Darcy, ru='У моего двигателя мощность упала почти вдвое. Какая же тут мощная гравитация.', en="My engine output just dropped by half. The gravity in here is insane."),
        VoiceLine(4910, Darcy, ru='Трент, не попади под лопасти этой странной мельницы!', en="Trent, don't get caught in the blades of that damn mill!"),
        VoiceLine(5000, Darcy, ru='Сейчас тут всё нахрен взорвётся! Трент, шевелись! Не отставай!', en="This whole place is about to blow! Trent, move it! Don't fall behind!"),
        VoiceLine(5010, Darcy, ru='Черт! Проход закрыт! Трент, гляди! Слева еще тоннель! Летим туда!', en="Damn it! The passage is blocked! Trent, look! Another tunnel on the left! Let's go!"),
        VoiceLine(5020, Darcy, ru='Осторожно, Трент, тут эти вертящиеся мельницы.', en="Watch out, Trent, more of those spinning mills ahead."),
        VoiceLine(5030, Darcy, ru='Чё за нафиг! Впереди двойная мельница!', en="Fuck me! A double mill straight ahead!"),
    ]


class Mission8(Msn8, script.StoryMission):
    MISSION_INDEX = 8
    CUTSCENES = []
    SPACE_CLASS = Msn8Space
    SYNC_SPACE = True

    MISSION_TITLE = 'Миссия 8. Эксперт по Кочевникам'
