from universe.audio.pilot import PilotVoice
from universe.audio.pilot_line import PilotLine as L
from universe.audio.parse_rule import RuleNNVoice


class NNVoice(PilotVoice):
    LINES = [
        L('nag_leaving_mission_area_01-', 'Внимание! Вы покид+аете зону м+иссии!', RuleNNVoice),
        L('nag_dst_ship_01-', 'Внимание! Вы покид+аете з+ону сражения! Вернитесь в з+ону сражения. Иначе ваша миссия может быть про+играна!', RuleNNVoice),
        L('nag_dst_base_01-', 'Внимание! Вы покид+аете з+ону миссии! Соверш+ите стык+овку с б+азой, чтобы прод+олжить!', RuleNNVoice),
        L('nag_dst_gate_01-', 'Внимание! Вы покид+аете з+ону миссии! Соверш+ите стык+овку с гиперврат+ами, чтобы прод+олжить!', RuleNNVoice),
        L('nag_dst_tl_01-', 'Внимание! Вы покид+аете з+ону м+иссии! Соверш+ите стык+овку с торг+овой л+инией, чтобы прод+олжить!', RuleNNVoice),
        L('nag_pos_01-', 'Внимание! Направл+яйтесь к т+очке пут+и, ин+аче м+ожете проигр+ать!', RuleNNVoice),
        L('nnv_anomaly_detected', 'Обнар+ужена аном+алия!', RuleNNVoice),
        L('nnv_cruise_disrupted', 'Нар+ушена раб+ота кру+изного дв+игателя', RuleNNVoice),
        # L('nnv_dock_denied_destination_hostile', 'Стык+овка отклонен+а. Точка назнач+ения вражд+ебна', RuleNNVoice),
        # L('nnv_dock_denied_standing_by', 'Стык+овка отклонен+а. Точка назнач+ения вражд+ебна', RuleNNVoice),
        # L('nnv_formation_request_denied', '', RuleNNVoice),
        # L('nnv_free_flight', '', RuleNNVoice),
        # L('nnv_jump_gate_access_denied', '', RuleNNVoice),
        # L('nnv_jump_gate_access_granted', '', RuleNNVoice),
        L('shield_restored', 'Щит восстан+овлен', RuleNNVoice),
        L('nnv_shield_restored', 'Щит восстан+овлен', RuleNNVoice),
        L('nnv_shield_failed', 'Щит отключ+ён', RuleNNVoice),
        L('nnv_shield_destroyed', 'Щит уничт+ожен', RuleNNVoice),
        L('shield_destroyed', 'Щит уничт+ожен', RuleNNVoice),
        L('nnv_volatile_gases_detected', 'Обнар+ужены оп+асные г+азовые облак+а!', RuleNNVoice),
        L('volatile_gases_detected', 'Обнар+ужены оп+асные г+азовые облак+а!', RuleNNVoice),
        # L('nnv_trade_lane_end_docking_not_allowed', '', RuleNNVoice),
        # L('nnv_trade_lane_access_denied', '', RuleNNVoice),
        # L('nnv_released_from_formation', '', RuleNNVoice),
        # L('all_systems_normal', '', RuleNNVoice),
        L('ship_purchase_complete', 'Пок+упка корабл+я усп+ешно завершена', RuleNNVoice),
        # L('amsn_accepted', '', RuleNNVoice),
        L('cancelled', 'Отменено', RuleNNVoice),
        L('cannot_dock', 'Стык+овка отклонена', RuleNNVoice),
        L('cargo_expired', 'Срок г+одности гр+уза ист+ёк', RuleNNVoice),
        # L('cmsn_accepted', '', RuleNNVoice),
        L('component_destroyed', 'Компонент корабля уничтожен', RuleNNVoice),
        L('countermeasure_dropper_destroyed', 'Постановщик помех уничтожен', RuleNNVoice),
        L('danger', 'Опасность!', RuleNNVoice),
        L('mines_detected', 'Обнаружены мины!', RuleNNVoice),
        L('deactivated', 'Деактивирован', RuleNNVoice),
        L('destination_reached', 'Достигнута точка назначения', RuleNNVoice),
        L('dock', 'Стык+овка', RuleNNVoice),
        L('dock_disallowed', 'Стыковка невозможна', RuleNNVoice),
        # L('docking_ring_cleared', '', RuleNNVoice),
        L('engine_destroyed', 'Двигатель уничтожен', RuleNNVoice),
        # L('evade', '', RuleNNVoice),
        # L('face', '', RuleNNVoice),
        L('goto', 'Направляться', RuleNNVoice),
        L('gun_destroyed', 'Пушка уничтожена', RuleNNVoice),
        L('hull_breach_imminent', 'Пробоина корпуса неизбежна!', RuleNNVoice),
        L('insufficient_cargo_space', 'Недостаточно места в трюме', RuleNNVoice),
        # L('launch_procedure_complete', '', RuleNNVoice),
        L('launcher_destroyed', 'Пусковая установка уничтожена', RuleNNVoice),
        L('loaded_into_cargo_hold', 'Добавлено в грузовой отсек', RuleNNVoice),
        # L('mission_complete', '', RuleNNVoice),
        # L('mission_data_received', '', RuleNNVoice),
        # L('mission_failed', '', RuleNNVoice),
        L('mounted', 'Устан+овлено', RuleNNVoice),
        L('must_have_mounted_engine_to_launch', 'Невозможно взлететь без двигателя', RuleNNVoice),
        L('must_have_mounted_power_plant_to_launch', 'Невозможно взлететь без генератора', RuleNNVoice),
        L('must_have_mounted_scanner_to_launch', 'Невозможно взлететь без сканера', RuleNNVoice),
        # L('new_coordinates_received', '', RuleNNVoice),
        # L('nnvoice_end_of_trade_lane', '', RuleNNVoice),
        L('nnvoice_trade_lane_disrupted', 'Нарушена работа торговой линии', RuleNNVoice),
        L('nnv_dock_too_far', 'Стыковка отклонена. Точка назначения находится слишком далеко', RuleNNVoice),
        L('nnv_formation_lost', 'Формация потеряна', RuleNNVoice),
        # L('no_place_to_mount', '', RuleNNVoice),
        # L('none_available', '', RuleNNVoice),
        # L('not_enough_money', '', RuleNNVoice),
        # L('not_interested', '', RuleNNVoice),
        # L('objective_complete', '', RuleNNVoice),
        # L('objective_destroyed', '', RuleNNVoice),
        # L('objective_detected', '', RuleNNVoice),
        # L('objective_failed', '', RuleNNVoice),
        # L('objective_reached', '', RuleNNVoice),
        # L('playerstrafe', '', RuleNNVoice),
        # L('repair_droid_activated', '', RuleNNVoice),
        # L('repair_droid_deactivated', '', RuleNNVoice),
        # L('repair_droid_exhausted', '', RuleNNVoice),
        L('repair_complete', 'Ремонт выполнен', RuleNNVoice),
        # L('scanning', '', RuleNNVoice),
        L('scanning_cargo', 'Сканирование трюма...', RuleNNVoice),
        L('target_reached', 'Преодолена точка назначения', RuleNNVoice),
        L('thruster_destroyed', 'Форсаж уничтожен', RuleNNVoice),
        # L('tradelane', '', RuleNNVoice),
        # L('trail', '', RuleNNVoice),
        L('waiting_to_dock', 'Стыковочный узел занят. Входим в очередь на стыковку', RuleNNVoice),
        L('weapon_destroyed', 'Орудие уничтожено', RuleNNVoice),
        # L('object_planet', '', RuleNNVoice),
        # L('object_sun', '', RuleNNVoice),
        # L('object_docking_ring', '', RuleNNVoice),
        # L('object_jump_gate', '', RuleNNVoice),
        # L('object_tradelane_ring', '', RuleNNVoice),
        # L('object_station', '', RuleNNVoice),
        # L('object_waypoint', '', RuleNNVoice),
        # L('object_jump_hole', '', RuleNNVoice),
        # L('object_fighter', '', RuleNNVoice),
        # L('object_freighter', '', RuleNNVoice),
        # L('object_gunboat', '', RuleNNVoice),
        # L('object_cruiser', '', RuleNNVoice),
        # L('object_transport', '', RuleNNVoice),
        # L('object_capital_ship', '', RuleNNVoice),
        # L('object_mining_ship', '', RuleNNVoice),
        # L('goto_ship_dealer', '', RuleNNVoice),
        # L('ship_dealer', '', RuleNNVoice),
        # L('goto_commodity_dealer', '', RuleNNVoice),
        # L('commodity_dealer', '', RuleNNVoice),
        # L('goto_equipment_dealer', '', RuleNNVoice),
        # L('equipment_dealer', '', RuleNNVoice),
        # L('goto_bar', '', RuleNNVoice),
        # L('bar', '', RuleNNVoice),
        # L('goto_launch', '', RuleNNVoice),
        # L('launch_pad', '', RuleNNVoice),
        # L('goto_deck', '', RuleNNVoice),
        # L('deck', '', RuleNNVoice),
        # L('job_board', '', RuleNNVoice),
        # L('look_at_news', '', RuleNNVoice),
        # L('launch_to_space', '', RuleNNVoice),
        # L('repair', '', RuleNNVoice),
        # L('turret_destroyed', '', RuleNNVoice),
        # L('mine_dropper_destroyed', '', RuleNNVoice),
        L('shield_activated', 'Щит активирован', RuleNNVoice),
        L('shield_deactivated', 'Щит деактивирован', RuleNNVoice),
        # L('tractor_activated', '', RuleNNVoice),
        # L('tractor_deactivated', '', RuleNNVoice),
        L('nnv_tractor_failure', 'Ошибка магнитного луча', RuleNNVoice),
        L('target_out_of_range', 'Цель находится слишком далеко', RuleNNVoice),
        L('engine_critical', 'Критические повреждения двигателя', RuleNNVoice),
        L('cargo_jettisoned', 'Груз сброшен', RuleNNVoice),
        L('incoming_torpedo', 'Приближается торпеда', RuleNNVoice),
        L('incoming_missile', 'Приближается ракета', RuleNNVoice),
        L('warning', 'Внимание!', RuleNNVoice),
        L('sensor_efficiency_reduced', 'Точность сэнсоров снижена', RuleNNVoice),
        L('radiation_damage_detected', 'Обнаружена зона радиоактивных повреждений', RuleNNVoice),
        L('increased_drag_detected', 'Обнаружена зона с повышенным трением, скорость корабля снижена', RuleNNVoice),
        L('entering_sun_corona', 'Вход в солнечную корону', RuleNNVoice),
        L('entering_atmosphere', 'Вход в атмосферу', RuleNNVoice),
        # L('cmsn_failed', '', RuleNNVoice),
        # L('pmsn_accepted', '', RuleNNVoice),
        # L('dmsn_accepted', '', RuleNNVoice),
        # L('obj_travel', '', RuleNNVoice),
        # L('obj_deliver', '', RuleNNVoice),
        # L('obj_find', '', RuleNNVoice),
        # L('info_data_received', '', RuleNNVoice),
        # L('info_obj_detected', '', RuleNNVoice),
        # L('info_obj_destroyed', '', RuleNNVoice),
        # L('info_obj_complete', '', RuleNNVoice),
        # L('info_obj_reached', '', RuleNNVoice),
        # L('info_obj_failed', '', RuleNNVoice),
        # L('info_target_reached', '', RuleNNVoice),
        # L('info_target_in_range', '', RuleNNVoice),
        # L('info_out_of_area', '', RuleNNVoice),
        L('info_access_denied', 'Доступ запрещён', RuleNNVoice),
        # L('info_ship_destroyed', '', RuleNNVoice),
        # L('info_sol_destroyed', '', RuleNNVoice),
        # L('info_incoming_hostiles', '', RuleNNVoice),
        # L('gen_msn_complete', '', RuleNNVoice),
        # L('gen_msn_failed', '', RuleNNVoice),
    ]
    # STEOS_ID = 549  # Filatova
    STEOS_ID = 219  # Yennifer
    FOLDER = 'nnvoice'
