from tools.crc import crc32
from tools.utf_xml import XML_UTF


ICON_TEMPLATE = '''<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- XML generated by UTFXML Version 2.2 built 19-Aug-2010 -->
<UTFXML filename="{file_name}">
   <UTF_ROOT>
      <VMeshLibrary>
         <{vms_name}>
           <VMeshData type="VMeshData" format="1" surface="4">


      <mesh count="1">
         <!-- Mesh Triangle  First   Last Count   Pad  Material -->
         <!--   0      0 -->     0,     3,    6, 0xcc, {material_crc}
      </mesh>
      <index count="6">
         <!-- Triangle  Vtx1, Vtx2, Vtx3 -->
         <!--     0 -->    0,    1,    2
         <!--     1 -->    1,    3,    2
      </index>
      <vertex FVF="0x112" count="4">
         <!-- Vertex           X                  Y                  Z               X Normal        Y Normal        Z Normal          U                 V      -->
         <!--     0 -->      0.0355230050,     -0.0340723880,    -105.66328e-09;   0.0000000000, -7.5181674e-09,   1.0000000000;     0.9995002700,    499.51673e-06
         <!--     1 -->      0.0355230050,      0.0340722280,    -105.15095e-09;  591.32154e-18, -7.5181674e-09,   1.0000000000;     0.9995005100,     0.9995003300
         <!--     2 -->     -0.0355230120,     -0.0340723880,    -105.66328e-09;  591.32154e-18, -7.5181674e-09,   1.0000000000;    499.51673e-06,    499.84455e-06
         <!--     3 -->     -0.0355230120,      0.0340722170,    -105.15095e-09;  1.1826431e-15, -7.5181683e-09,   1.0000000000;    499.69554e-06,     0.9995005100
      </vertex>

           </VMeshData>
        </{vms_name}>

      </VMeshLibrary>
      <VMeshPart>
         <VMeshRef type="VMeshRef">
            <!-- header size  --> 60,
            <!-- vmesh lib    --> {vms_name},
            <!-- start vert   --> 0,
            <!-- num verts    --> 4,
            <!-- start index  --> 0,
            <!-- num indices  --> 6,
            <!-- start mesh   --> 0,
            <!-- num meshes   --> 1,
            <!-- bounding box -->  0.035523005,    0.034072228,    0,
                                  -0.035523012,   -0.034072388, -105.66328e-9,
            <!-- center       --> -3.7252903e-9, -80.093741e-9,  -52.831638e-9,
            <!-- radius       --> 0.049222011
         </VMeshRef>
      </VMeshPart>
      <Material_library name="Material library">
         <Material_count name="Material count" type="int">1</Material_count>
         <{material_name}>
            <Type type="text">DcDt</Type>
            <Dt_name type="text">{texture_name}</Dt_name>
            <Dt_flags type="int">0x40</Dt_flags>
         </{material_name}>
      </Material_library>
      <Texture_library name="Texture library">
         <{texture_name}>
            <MIP0 type="file" filename="bh_elite_3db\\bh_elite_mip0.tga"/>
         </{texture_name}>
      </Texture_library>
   </UTF_ROOT>
</UTFXML>
'''

ICONS_COUNT = 50

xmls = []
for i in range(1, ICONS_COUNT+1):
    material_name = f'icon_new_{i:02d}'
    tpl = {
        'file_name': f'{material_name}.3db',
        'vms_name': f'my_new_icons.new_icon{i:02d}.lod0-112.vms',
        'material_name': material_name,
        'material_crc': hex(crc32(bytes(material_name, 'utf-8'))),
        'texture_name': f'ICON_new_{i:02d}.tga',
    }
    xmls.append(ICON_TEMPLATE.format(**tpl)) 

XML_UTF.process_xmls(xmls)
