from universe.audio.pilot_line import PilotLine as L
from universe.audio import parse_rule as R

from text.strings import MultiString as MS


LINES = [
    L('gcs_combat_announce_allclear_01-', 'Противников не обнаружено.'),
    L('gcs_combat_announce_allclear_02-', 'На сканерах больше нет неприятелей.'),
    L('gcs_combat_announce_allclear_03-', 'Зона зачищена.'),
    L('gcs_combat_announce_allclear_04-', 'Врагов не видно.'),
    L('gcs_combat_announce_allclear_05-', 'Зона в зеленом статусе. Врагов не обнаружено.'),
    L('gcs_combat_announce_allclear_06-', 'Зона чиста. Враждебные контакты отсутствуют.'),
    L('gcs_combat_announce_combatdrift_01-', 'Этот контакт отвлечет нас от задания. Давайте не отвлекаться на него',
      R.RuleNormalAction),
    L('gcs_combat_announce_combatdrift_02-', 'Держать строй, мы постараемся избежать сражения', R.RuleNormalAction),
    L('gcs_combat_announce_combatdrift_03-',
      'Концентрируемся на нашей задаче, у нас нет времени отвлекаться на каждого неприятеля', R.RuleNormalAction),
    L('gcs_combat_announce_enemysighted_01-', 'Вижу нового неприятеля.', R.RuleNormalAction),
    L('gcs_combat_announce_enemysighted_02-', 'На радаре новый противник.', R.RuleNormalAction),
    L('gcs_combat_announce_enemysighted_03-', 'Замечена новая угроза. Неприятель.', R.RuleNormalAction),
    L('gcs_combat_announce_enemysighted_04-', 'На сканере замечены неприятели!', R.RuleNormalAction),
    L('gcs_combat_announce_ff_01-', 'Смотри куда стреляешь!', R.RuleAngry),
    L('gcs_combat_announce_ff_02-', 'Прекрати стрелять, фрилансер!', R.RuleAngry),
    L('gcs_combat_announce_ff_03-', 'Хватит стрелять по мне!', R.RuleAngry),
    L('gcs_combat_announce_flee_01-', 'Уходим!', R.RuleHighAction),
    L('gcs_combat_announce_flee_02-', 'Я улетаю!', R.RuleHighAction),
    L('gcs_combat_announce_flee_03-', 'К чёрту всё, я улетаю отсюда.', R.RuleHighAction),
    L('gcs_combat_announce_flee_04-', 'Я отступаю.', R.RuleHighAction),
    L('gcs_combat_announce_flee_05-', 'Мне нужна перегрупировка.', R.RuleHighAction),
    L('gcs_combat_announce_flee_06-', 'Я сваливаю отсюда.', R.RuleHighAction),
    L('gcs_combat_askengage_01-', 'Разрешите атаковать.', R.RuleNormalAction),
    L('gcs_combat_askengage_02-', 'Запрашиваю открыть огонь.', R.RuleNormalAction),
    L('gcs_combat_askengage_03-', 'Ожидаю приказа на перехват.', R.RuleNormalAction),
    L('gcs_combat_askengage_04-', 'Запрашиваю разрешение открыть огонь!', R.RuleNormalAction),
    L('gcs_combat_askforhelp_01-', 'Мне нужна поддержка!', R.RuleHighAction),
    L('gcs_combat_askforhelp_02-', 'Запрашиваю поддержку!', R.RuleHighAction),
    L('gcs_combat_askforhelp_03-', 'Прикройте меня!', R.RuleHighAction),
    L('gcs_combat_askforhelp_04-', 'Нужна поддержка!', R.RuleHighAction),
    L('gcs_combat_askforhelp_05-', 'Запрашиваю дополнительную поддержку!', R.RuleHighAction),
    L('gcs_combat_brag_01-', 'Неприятель уничтожен.', R.RuleNormalAction),
    L('gcs_combat_brag_02-', 'Враг уничтожен.', R.RuleNormalAction),
    L('gcs_combat_brag_03-', 'Вражеская цель ликвидирована.', R.RuleNormalAction),
    L('gcs_combat_brag_04-', 'Неприятель ликвидирован.', R.RuleNormalAction),
    L('gcs_combat_brag_05-', 'Враг нейтрализован.', R.RuleNormalAction),
    L('gcs_combat_brag_06-', 'Неприятель был нейтрализован.', R.RuleNormalAction),
    L('gcs_combat_comingin_p_01-', 'Мы на пути к тебе.', R.RuleNormalAction),
    L('gcs_combat_comingin_p_02-', 'Подожди, скоро будем тут.', R.RuleNormalAction),
    L('gcs_combat_comingin_p_03-', 'Жди, летим к тебе.', R.RuleNormalAction),
    L('gcs_combat_comingin_s_01-', 'Я скоро буду здесь.', R.RuleNormalAction),
    L('gcs_combat_comingin_s_02-', 'Я в пути.', R.RuleNormalAction),
    L('gcs_combat_comingin_s_03-', 'Жди, я лечу к тебе.', R.RuleNormalAction),
    L('gcs_combat_deathsympathy_01-', 'Нашего сбили!', R.RuleHighAction),
    L('gcs_combat_deathsympathy_02-', 'Я потеряла вед+омого!', R.RuleHighAction),
    L('gcs_combat_deathsympathy_03-', 'Член крыла убит!', R.RuleHighAction),
    L('gcs_combat_deathsympathy_04-', 'Моего сбили!', R.RuleHighAction),
    L('gcs_combat_engaging_01+', 'Готовлюсь к перехвату', R.RuleEndTo),
    L('gcs_combat_engaging_02+', 'Я перехватываю', R.RuleEndTo),
    L('gcs_combat_engaging_03+', 'Перехватываю', R.RuleEndTo),
    L('gcs_combat_engaging_04+', 'Приступаю к перехвату', R.RuleEndTo),
    L('gcs_combat_fleereason_damaged_01-', 'Я сильно повреждена', R.RuleHighAction),
    L('gcs_combat_fleereason_damaged_02-', 'Мои повреждения критические', R.RuleHighAction),
    L('gcs_combat_fleereason_damaged_03-', 'Мой корабль повреждён', R.RuleHighAction),
    L('gcs_combat_fleereason_noweapons_01-', 'Я потеряла пушки', R.RuleHighAction),
    L('gcs_combat_fleereason_noweapons_02-', 'У меня больше нет пушек', R.RuleHighAction),
    L('gcs_combat_fleereason_noweapons_03-', 'Я потеряла своё вооружение', R.RuleHighAction),
    L('gcs_combat_fleereason_other_01-', 'Дел+а плохи, в+алим', R.RuleHighAction),
    L('gcs_combat_fleereason_other_02-', 'Пор+а сваливать, тут делать нечего', R.RuleHighAction),
    L('gcs_combat_fleereason_other_03-', 'Наше положение ужасное', R.RuleHighAction),
    L('gcs_combat_fleereason_tough_01-', 'Ситуация ужасная', R.RuleHighAction),
    L('gcs_combat_fleereason_tough_02-', 'Всё очень плохо, сражаться бессмысленно', R.RuleHighAction),
    L('gcs_combat_fleereason_tough_03-', 'Не вижу смысла продолжать сражение', R.RuleHighAction),
    L('gcs_combat_hasinsights_01-', 'Контакт в радиусе видимости', R.RuleNormalAction),
    L('gcs_combat_hasinsights_02-', 'Наблюдаю противника', R.RuleNormalAction),
    L('gcs_combat_hasinsights_03-', 'Визуальный контакт. Готовлюсь к атаке', R.RuleNormalAction),
    L('gcs_combat_hasinsights_04-', 'Рядом враг', R.RuleNormalAction),
    L('gcs_combat_hasinsights_05-', 'Противник вблиз+и от меня', R.RuleNormalAction),
    L('gcs_combat_hasinsights_06-', 'Направляюсь к вражеской цели', R.RuleNormalAction),
    L('gcs_combat_inflicting_damage_01-', 'Враг на мушке', R.RuleNormalAction),
    L('gcs_combat_inflicting_damage_02-', 'Противник повреждён!', R.RuleNormalAction),
    L('gcs_combat_inflicting_damage_03-', 'Противник терпит повреждения!', R.RuleNormalAction),
    L('gcs_combat_inflicting_damage_04-', 'Наношу повреждения противнику!', R.RuleNormalAction),
    L('gcs_combat_inflicting_damage_05-', 'Попал по нему!', R.RuleNormalAction),
    L('gcs_combat_inflicting_damage_06-', 'Враг под моим огнём!', R.RuleNormalAction),
    L('gcs_combat_inflicting_damage_worst_01-', 'Враг почти уничтожен', R.RuleNormalAction),
    L('gcs_combat_inflicting_damage_worst_02-', 'Цель горит!', R.RuleNormalAction),
    L('gcs_combat_inflicting_damage_worst_03-', 'Враг больше не выдержит', R.RuleNormalAction),
    L('gcs_combat_inflicting_damage_worst_04-', 'Почти убила его', R.RuleNormalAction),
    L('gcs_combat_inflicting_damage_worst_05-', 'Противник почти убит', R.RuleNormalAction),
    L('gcs_combat_inflicting_damage_worst_06-', 'Цель почти уничтожена', R.RuleNormalAction),
    L('gcs_combat_insights_01-', 'Преследую врага', R.RuleNormalAction),
    L('gcs_combat_insights_02-', 'Враг на прицеле', R.RuleNormalAction),
    L('gcs_combat_insights_03-', 'Вражеская цель захвачена', R.RuleNormalAction),
    L('gcs_combat_insights_04-', 'Иду за врагом', R.RuleNormalAction),
    L('gcs_combat_insights_05-', 'Взяла цель', R.RuleNormalAction),
    L('gcs_combat_insights_06-', 'Преследую его', R.RuleNormalAction),
    L('gcs_combat_noengagereason_toofar_01-', 'Он улетел слишком далеко', R.RuleNormalAction),
    L('gcs_combat_noengagereason_toofar_02-', 'Не вижу смысла догонять его', R.RuleNormalAction),
    L('gcs_combat_noengagereason_toofar_03-', 'Кажется враг что-то задумал, давайте не поддаваться на это',
      R.RuleNormalAction),
    L('gcs_combat_noengagereason_tootough_01-', 'Слишком опасно', R.RuleNormalAction),
    L('gcs_combat_noengagereason_tootough_02-', 'У нас нет столько сил', R.RuleNormalAction),
    L('gcs_combat_noengagereason_tootough_03-', 'Мне это не нравится', R.RuleNormalAction),
    L('gcs_combat_noengaging_01+', 'Я не преследую', R.RuleNormalAction),
    L('gcs_combat_noengaging_02+', 'Нет, я не преследую', R.RuleNormalAction),
    L('gcs_combat_offerhelp_01-', 'Кажется тебе нужна помощь?', R.RuleNormalAction),
    L('gcs_combat_offerhelp_02-', 'Подкрепление прибыло.', R.RuleNormalAction),
    L('gcs_combat_offerhelp_03-', 'Мы пришли на помощь', R.RuleNormalAction),
    L('gcs_combat_offerhelp_04-', 'Я думаю вам нужна поддержка', R.RuleNormalAction),
    L('gcs_combat_offerhelp_05-', 'Эй, друг, нужна помощь?', R.RuleNormalAction),
    L('gcs_combat_order_disengage_01-', 'Прекратить атаку, пилоты', R.RuleNormalAction),
    L('gcs_combat_order_disengage_02-', 'Звено, отменить атаку', R.RuleNormalAction),
    L('gcs_combat_order_disengage_03-', 'Прекратить стрельбу', R.RuleNormalAction),
    L('gcs_combat_order_disengage_04-', 'Звено, прекратить стрильбу', R.RuleNormalAction),
    L('gcs_combat_order_disengage_05-', 'Пилоты, прекращаем атаку', R.RuleNormalAction),
    L('gcs_combat_order_engage_01-', 'Огонь на поражение', R.RuleNormalAction),
    L('gcs_combat_order_engage_02-', 'Огонь по готовности!', R.RuleNormalAction),
    L('gcs_combat_order_engage_03-', 'Открыть огонь!', R.RuleNormalAction),
    L('gcs_combat_order_engage_04-', 'Преследуем!', R.RuleNormalAction),
    L('gcs_combat_order_engage_05-', 'Атакуем!', R.RuleNormalAction),
    L('gcs_combat_order_engage_06-', 'Уничтожить!', R.RuleNormalAction),
    L('gcs_combat_order_noengage_01-', 'Не преследуйте вражескую цель', R.RuleNormalAction),
    L('gcs_combat_order_noengage_02-', 'Внимание всем, запрещаю атаковать вражескую цель!', R.RuleNormalAction),
    L('gcs_combat_order_noengage_03-', 'Не стрелять! Остановить атаку!', R.RuleNormalAction),
    L('gcs_combat_order_noengage_04-', 'Не стреляем', R.RuleNormalAction),
    L('gcs_combat_order_retreattowards_01+', 'Уходим, направляемся к', R.RuleNormalActionWithEnd),
    L('gcs_combat_order_retreattowards_02+', 'Прекращаем атаку и возвращаемся к', R.RuleNormalActionWithEnd),
    L('gcs_combat_order_retreattowards_03+', 'Все назад к', R.RuleNormalActionWithEnd),
    L('gcs_combat_order_retreattowards_04+', 'Приказываю орстановить операцию, летим к', R.RuleNormalActionWithEnd),
    L('gcs_combat_order_retreattowards_05+', 'Уходим к', R.RuleNormalActionWithEnd),
    L('gcs_combat_order_retreattowards_06+', 'Приказ направляться к', R.RuleNormalActionWithEnd),
    L('gcs_combat_rejoiningform_01-', 'Отменяю цель и возвращаюсь в формацию', R.RuleNormalAction),
    L('gcs_combat_rejoiningform_02-', 'Возвращаюсь в формацию', R.RuleNormalAction),
    L('gcs_combat_resume_patrol_01-', 'Возвращаемся к нашему патрулированию', R.RuleNormalAction),
    L('gcs_combat_resume_patrol_02-', 'Возобновляем патруль', R.RuleNormalAction),
    L('gcs_combat_resume_patrol_03-', 'Приступаем к плану патрулированию', R.RuleNormalAction),
    L('gcs_combat_resume_patrol_04-', 'Возобновляем наш патруль', R.RuleNormalAction),
    L('gcs_combat_resume_trade_01+', 'Возвращаемся к нашей торговой миссии', R.RuleNormalAction),
    L('gcs_combat_resume_trade_02+', 'Возобновляем торговую миссию', R.RuleNormalAction),
    L('gcs_combat_resume_trade_03+', 'Приступаем к нашей торговой миссии', R.RuleNormalAction),
    L('gcs_combat_resume_trade_04+', 'Возобновляем движение по торговому пути', R.RuleNormalAction),
    L('gcs_combat_scream_01-', R.SCREAM_1, R.RuleScream),
    L('gcs_combat_scream_02-', R.SCREAM_2, R.RuleScream),
    L('gcs_combat_scream_03-', R.SCREAM_3, R.RuleScream),
    L('gcs_combat_scream_04-', R.SCREAM_4, R.RuleScream),
    L('gcs_combat_scream_05-', R.SCREAM_5, R.RuleScream),
    L('gcs_combat_scream_06-', R.SCREAM_6, R.RuleScream),
    L('gcs_combat_scream_07-', R.SCREAM_7, R.RuleScream),
    L('gcs_combat_scream_08-', R.SCREAM_8, R.RuleScream),
    L('gcs_combat_taking_damage_01-', 'Я поврежден!', R.RuleHighAction),
    L('gcs_combat_taking_damage_02-', 'Меня атаковали!', R.RuleHighAction),
    L('gcs_combat_taking_damage_03-', 'Я под огнём!', R.RuleHighAction),
    L('gcs_combat_taking_damage_04-', 'Противник стреляет по мне!', R.RuleHighAction),
    L('gcs_combat_taking_damage_05-', 'Я атакован, но вроде в порядке!', R.RuleHighAction),
    L('gcs_combat_taking_damage_06-', 'Меня преследуют!', R.RuleHighAction),
    L('gcs_combat_taking_damage_07-', 'Противник атакует меня!', R.RuleHighAction),
    L('gcs_combat_taking_damage_08-', 'Я под вражеским огнём!', R.RuleHighAction),
    L('gcs_combat_taking_damage_worst_01-', 'Системы едва функционируют!', R.RuleHighAction),
    L('gcs_combat_taking_damage_worst_02-', 'Я не выдерживаю!', R.RuleHighAction),
    L('gcs_combat_taking_damage_worst_03-', 'Системы обеспечения отказывают!', R.RuleHighAction),
    L('gcs_combat_taking_damage_worst_04-', 'Я под огнём! Корабль горит!', R.RuleHighAction),
    L('gcs_combat_taking_damage_worst_05-', 'Я на грани!', R.RuleHighAction),
    L('gcs_combat_taking_damage_worst_06-', 'Повреждения критичны...', R.RuleHighAction),
    L('gcs_combat_taking_damage_worst_07-', 'Я почти уничтожен!', R.RuleHighAction),
    L('gcs_combat_taking_damage_worst_08-', 'Я теряю контроль!', R.RuleHighAction),
    L('gcs_combat_takinglead_01-', 'Я беру контроль на себя', R.RuleNormalAction),
    L('gcs_combat_takinglead_02-', 'Теперь я вед+у звен+о', R.RuleNormalAction),
    L('gcs_combat_takinglead_03-', 'Беру командование на себя', R.RuleNormalAction),
    L('gcs_combat_takinglead_04-', 'Я вед+у звен+о', R.RuleNormalAction),
    L('gcs_dhail_angry_response_01-', 'А ну отвали, тебе тут нечего смотреть!', R.RuleAngry),
    L('gcs_dockhail_hailee_datasubmit_01-', 'Высылаю данные'),
    L('gcs_dockhail_hailee_datasubmit_02-', 'Начинаю отсылать данные'),
    L('gcs_dockrequest_goingto_01+', 'Мы движемся к', R.RuleEndObject),
    L('gcs_dockrequest_jumpgatedelayed_01-', 'Мы не единственные, кто движется к', R.RuleEndObject),
    L('gcs_dockrequest_jumpgateopen_01-', 'Ребята, доступ открыт, движемся к', R.RuleEndObject),
    L('gcs_dockrequest_jumpgateopenafterdelay_01-', 'Доступ получен, теперь наш черёд'),
    L('gcs_dockrequest_request_01+', 'Мне нужно провести', R.RuleEndThing),
    L('gcs_dockrequest_request_02+', 'Я запрашиваю', R.RuleEndThing),
    L('gcs_dockrequest_thankshelp_01-', 'спасибо за помощь', R.RuleContinueRequest),
    L('gcs_dockrequest_thisourstop_01-', 'Так, здесь наша остановка'),
    L('gcs_dockrequest_todock-', 'стыковку', R.RuleDockContinueRequest),
    L('gcs_dockrequest_toland-', 'посадку', R.RuleDockContinueRequest),
    L('gcs_dockrequest_tomoor-', 'швартовку', R.RuleDockContinueRequest),
    L('gcs_dockrequest_tradelanestart_01-', 'Запускаю торговую линию'),
    L('gcs_fidget_patrol_wpremainquery_01-', 'Как много точек пути нам нужно пролететь?'),
    L('gcs_fidget_patrolrumor_01-', 'Когда-то и меня вел+а дорога приключений. А потом мне прострелили колено'),
    L('gcs_fidget_patrolsimple_01-', 'У нас обычная патрульная миссия, спокойно выполняем операцию'),
    L('gcs_fidget_saystatus_damagelarge_01-', 'Повреждения корабля значительны, не знаю как я долечу до базы'),
    L('gcs_fidget_saystatus_damagemedium_01-', 'Корабль заметно повреждён, но функционирует'),
    L('gcs_fidget_saystatus_damagenone_01-', 'Статус корабля: все системы работают штатно'),
    L('gcs_fidget_saystatus_damagesmall_01-', 'Меня потрепало, но в целом всё в порядке'),
    L('gcs_fidget_talkcargo_01-', 'обещает хорошую выручку'),
    L('gcs_fidget_trade_ihear_01+', 'Я слышал о месте, полном...'),
    L('gcs_fidget_trade_simple_01-', 'С этим грузом я заработаю себе билет в новую жизнь!'),
    L('gcs_fidget_trade_simple_02-', 'Надеюсь в этот раз на нас никто не нападёт'),
    L('gcs_fidget_trade_simple_03-', 'Доделаю эту торговую миссию и займусь чем-то более спокойным...'),
    L('gcs_fidget_traderumor_01-', 'Я слышал можно заработать на перепродаже особых сплавов'),
    L('gcs_fidget_whatstatus_01-', 'Команда, доложите ситуацию. Какой наш статус?'),

    L('gcs_misc_ack_01-', 'Подтверждаю'),
    L('gcs_misc_ack_02-', 'Цель понял'),
    L('gcs_misc_ack_03-', 'Так точно'),
    L('gcs_misc_attentionallwingmen_01+', 'Внимание всем участникам звена'),
    L('gcs_misc_goingto_p_01+', 'мы направляемся'),
    L('gcs_misc_goingto_s_01+', 'я движусь'),
    L('gcs_patrol_finished_p_01-', 'Мы завершаем наш патруль'),
    L('gcs_patrol_finished_s_01-', 'Я завершаю патрулирование'),
    L('gcs_patrol_idhome_p_01+', 'Мы на пути из', R.RuleEndTo),
    L('gcs_patrol_idhome_p_02+', 'Мы в патруле из', R.RuleEndTo),
    L('gcs_patrol_idhome_s_01+', 'Я направляюсь из', R.RuleEndTo),
    L('gcs_patrol_idhome_s_02+', 'Я в патруле из', R.RuleEndTo),
    L('gcs_patrol_ihave+', 'Мне осталось', R.RuleEndNumber),
    L('gcs_patrol_ihaveonly+', 'Мне осталась только', R.RuleEndNumber),
    L('gcs_patrol_morewpstogo-', 'точек пути', R.RuleStartNumber),
    L('gcs_patrol_morewptogo-', 'точка пути', R.RuleStartNumberSingle),
    L('gcs_patrol_wehave+', 'Нам осталось', R.RuleEndNumber),
    L('gcs_patrol_wehaveonly+', 'Нам осталась', R.RuleEndNumber),
    L('gcs_phail_blowoff_01-', 'Тебе нужно что-то еще?', R.RuleAngry),
    L('gcs_phail_blowoff_02-', 'Я уже тебе всё рассказал!', R.RuleAngry),
    L('gcs_phail_combatblowoff_01-', 'Хватит меня отвлекать, я в бо+ю!', R.RuleHighAction),

    L('gcs_misc_dash', 'дэш', R.RuleDash),
    L('gcs_misc_from', 'из', R.RuleFrom),
    L('gcs_misc_to', 'к', R.RuleTo),
    L('gcs_misc_thisis+', 'говорит', R.RuleThisIs),

    L('gcs_trade_carrying_p_01+', 'Вы везем', R.RuleEndCargo),
    L('gcs_trade_carrying_s_01+', 'Я везу', R.RuleEndCargo),
    L('gcs_trade_idhome_p_01+', 'Наш торговый конвой направляется из точки', R.RuleEndObject),
    L('gcs_trade_idhome_p_02+', 'Мы на торговой миссии из точки', R.RuleEndObject),
    L('gcs_trade_idhome_s_01+', 'Я торговец с пункта', R.RuleEndObject),
    L('gcs_trade_idhome_s_02+', 'Я выполняю торговую миссию из пункта', R.RuleEndObject),
    L('gcs_trade_wanttoget_p_01+', 'Мы планируем загрузить', R.RuleEndCargo),
    L('gcs_trade_wanttoget_s_01+', 'Я хочу загрузить', R.RuleEndCargo),

    L('gcs_scan_angry_01-', 'Ты совершил очень больш+ую ошибку...', R.RuleAngry),
    L('gcs_scan_angry_02-', 'Штож, ты не оставил мне выбора.', R.RuleAngry),
    L('gcs_scan_angry_03-', 'Ты теперь попал по полной...', R.RuleAngry),
    L('gcs_scan_announce_01-', 'Сейчас я просканирую твой трюм на наличие контрабанды.'),
    L('gcs_scan_announce_02-', 'Стой на месте, я сканирую трюм твоего корабля.'),
    L('gcs_scan_announce_03-', 'Я исполняю приказ на сканирование твоего трюма.'),
    L('gcs_scan_comply_01-', 'Ладно, ч+ёрт с тобой, лети. Но я тебя не забуду и точно найду'),
    L('gcs_scan_comply_02-', 'Ты можешь улететь с этим грузом, но тебе от нас не уйти. Мы тебя найдём везде'),
    L('gcs_scan_comply_03-', 'Ну штож, таким образом ты нарушаешь закон. Ты это понимаешь?'),
    L('gcs_scan_happy_01-', 'Ты сделал правильный выбор'),
    L('gcs_scan_happy_02-', 'Это ты правильно поступил.'),
    L('gcs_scan_happy_03-', 'Отлично. Спасибо за сотрудничество'),
    L('gcs_scan_lootdestroyed_01-', 'Да блин, мы потеряли груз', R.RuleAngry),
    L('gcs_scan_lootdestroyed_02-', 'Чёрт, груз уничтожен.', R.RuleAngry),
    L('gcs_scan_lootdestroyed_03-', 'Мы потеряли груз...', R.RuleAngry),
    L('gcs_scan_nothingfound_01-', 'Трюм чист, ты свободен.'),
    L('gcs_scan_nothingfound_02-', 'Всё в порядке, можешь продолжать движение.'),
    L('gcs_scan_nothingfound_03-', 'Всё хорошо. Ничего запрещенного не обнаружено.'),
    L('gcs_scan_orderdrop_01-', 'Так, так, так... Что тут у нас. А ну давай выбрасывай запрещенный груз. Быстро!',
      R.RuleAngry),
    L('gcs_scan_orderdrop_02-', 'Внимание всем, у нас тут неопознанный груз! Фрилансер, выкидывай груз. Это приказ!',
      R.RuleAngry),
    L('gcs_scan_orderdrop_03-', 'Я нашел то что искал. Давай выбрасывай груз из трюма. Иначе тебе не поздоровится',
      R.RuleAngry),
    L('gcs_scan_refuse_01-', 'Отказ, ты от меня ничего не получишь'),
    L('gcs_scan_refuse_02-', 'Ни за что, ты не имеешь такого права, так что я тебе ничего не выдам'),
    L('gcs_scan_refuse_03-', 'Отказано, я не пойду на сотрудничество'),

    L('rms_bigshiptaunt_01-', 'Ты совсем берега попутал?', R.RuleAngry),
    L('rms_bigshiptaunt_02-', 'Тебе не понравится то, что сейчас будет', R.RuleAngry),
    L('rms_bigshiptaunt_03-', 'Не слишком ли ты много на себя взял?', R.RuleAngry),
    L('rms_defendleader_01-', 'Тебе не достать нашего командира!', R.RuleAngry),
    L('rms_defendleader_02-', 'Чтобы добраться до моего командира, тебе надо сначала сразиться со мной, ут+ырок',
      R.RuleAngry),
    L('rms_defendleader_03-', 'Пока я здесь, ты не достигнешь своей цели, урод', R.RuleAngry),
    L('rms_defendsolar_01-', 'Наша база тебе не по зубам!', R.RuleAngry),
    L('rms_defendsolar_02-', 'Тебе не совладать с нашей базой!', R.RuleAngry),
    L('rms_defendsolar_03-', 'Я с удовольствием отобью твои нат+ужные поп+ытки атаковать нашу базу!', R.RuleAngry),
    L('rms_friendlyarrival_01-', 'Нужна помощь?'),
    L('rms_friendlyarrival_02-', 'Подкрепление прибыло'),
    L('rms_friendlyarrival_03-', 'Мы тебе поможем'),
    L('rms_friendlyarrival_04-', 'Я думаю, поддержка лишней не будет'),
    L('rms_friendlywelcome_01-', 'Отлично, мы вас заждались!'),
    L('rms_friendlywelcome_02-', 'Вы как раз вовремя!'),
    L('rms_friendlywelcome_03-', 'Мы бы без вас не справились!'),
    L('rms_friendlywelcome_04-', 'Рад вас видеть!'),
    L('rms_shiprunning_01-', 'Даже не пытайся догнать меня', R.RuleAngry),
    L('rms_shiprunning_02-', 'Я бы советовал тебе не следовать за мной', R.RuleAngry),
    L('rms_shiprunning_03-', 'Лучше не пытайся преследовать меня', R.RuleAngry),
    L('rms_smallshiptaunt_01-', 'Друган, ты попал', R.RuleAngry),
    L('rms_smallshiptaunt_02-', 'Сейчас ты получишь удар правосудием по полной', R.RuleAngry),
    L('rms_smallshiptaunt_03-', 'Я не собираюсь церемониться с тобой', R.RuleAngry),
    L('rms_smallshiptaunt_04-', 'Будет больно, не беспокойся', R.RuleAngry),
    L('rms_targetrunning_01-', 'А ну отвали, ублюдок!', R.RuleAngry),
    L('rms_targetrunning_02-', 'Иди к ч+ёрту!', R.RuleAngry),
    L('rms_targetrunning_03-', 'А ну прекрати стрелять, пока можешь!', R.RuleAngry),
    L('rms_targetrunning_04-', 'Ты сильнее, чем я думал...', R.RuleAngry),

    # GENERICS
    # L('gcs_refer_base_Br01_01_base-', ),
    # L('gcs_refer_system_Br01-', ),
    # L('gcs_gen_commodity_alienartifacts', ),
    # L('gcs_refer_faction_br_m_short', ),

    L('gcs_refer_base_testbase-', 'Станция Т+эрра', R.RuleBase),
    # L('gcs_gen_commodity_gold', 'з+олото', R.RuleCommodity),
    L('gcs_refer_faction_rh_short', 'Р+эйнланд', R.RuleFaction),
    L('gcs_refer_faction_rx_short', 'Г+ессенцы', R.RuleFaction),
    L('gcs_refer_faction_test_short', 'Фракция', R.RuleFaction),
    L('gcs_refer_faction_player_short', 'Фрил+ансер', R.RulePlayer),

    L('mod_refer_base_liner-', MS('точка лайнер', 'point liner'), R.RuleBase),
    L('mod_refer_base_freeport-', 'точка фрипорт', R.RuleBase),
    L('mod_refer_base_prison-', 'точка тюрьма', R.RuleBase),
    L('mod_refer_base_outpost-', 'точка аванпост', R.RuleBase),
    L('mod_refer_base_battleship-', 'точка линкор', R.RuleBase),
    L('mod_refer_base_military-', 'точка военная база', R.RuleBase),
    L('mod_refer_base_research-', 'точка исследовательская станция', R.RuleBase),
    L('mod_refer_base_shipyard-', 'точка верфь', R.RuleBase),
    L('mod_refer_base_factory-', 'точка фабрика', R.RuleBase),
    L('mod_refer_base_station-', 'точка станция', R.RuleBase),
    L('mod_refer_base_border-', 'точка пограничный аванпост', R.RuleBase),
    L('mod_refer_base_roid_miner-', MS('добывающее судно', 'Roid Miner'), R.RuleBase),
    L('mod_refer_base_gas_miner-', MS('газодобытчик', 'Gas Miner'), R.RuleBase),
    L('mod_refer_base_solar_plant-', MS('солнечный генератор', 'Solar Plant'), R.RuleBase),
    L('mod_refer_base_research_base-', MS('исследовательская база', 'Research Base'), R.RuleBase),

]
