from text.strings import MultiString as MS

import text.content.mineable_info_ru as RU
import text.content.mineable_info_en as EN

HOW_TO_HACK = MS(RU.HOW_TO_HACK, EN.HOW_TO_HACK)

ROID_MINER = MS(RU.ROID_MINER, EN.ROID_MINER)

GAS_MINER_OLD = MS(RU.GAS_MINER_OLD, EN.GAS_MINER_OLD)

ASTEROID_ICE = MS(RU.ASTEROID_ICE, EN.ASTEROID_ICE)

ASTEROID_ROCK = MS(RU.ASTEROID_ROCK, EN.ASTEROID_ROCK)

DEBRIS_MANUFACTORING = MS(RU.DEBRIS_MANUFACTORING, EN.DEBRIS_MANUFACTORING)

BATTLESHIP_HACKABLE = MS(RU.BATTLESHIP_HACKABLE, EN.BATTLESHIP_HACKABLE)

BATTLESHIP_LOCKED = MS(RU.BATTLESHIP_LOCKED, EN.BATTLESHIP_LOCKED)

LUXURY_LOCKED = MS(RU.LUXURY_LOCKED, EN.LUXURY_LOCKED)

HACKABLE_LUXURY = MS(RU.HACKABLE_LUXURY, EN.HACKABLE_LUXURY)

HACKABLE_SOLAR_PLANT = MS(RU.HACKABLE_SOLAR_PLANT, EN.HACKABLE_SOLAR_PLANT)

SOLAR_PLANT = MS(RU.SOLAR_PLANT, EN.SOLAR_PLANT)

STATION_RUINS = MS(RU.STATION_RUINS, EN.STATION_RUINS)

HACKABLE_STATION = MS(RU.HACKABLE_STATION, EN.HACKABLE_STATION)
