import random
from tools.create_id import CreateId


class SpaceVoice(object):
    VOICE_MALE = 'atc_leg_m01'
    VOICE_FEMALE = 'atc_leg_f01'
    VOICE_ROBOT = 'atc_leg_f01a'
    DEFAULT = VOICE_MALE

    FREEPORT = 'mod_refer_base_freeport'
    PRISON = 'mod_refer_base_prison'
    OUTPOST = 'mod_refer_base_outpost'
    BATTLESHIP = 'mod_refer_base_battleship'
    MILITARY = 'mod_refer_base_military'
    RESEARCH = 'mod_refer_base_research'
    SHIPYARD = 'mod_refer_base_shipyard'
    FACTORY = 'mod_refer_base_factory'
    STATION = 'mod_refer_base_station'
    BORDER_STATION = 'mod_refer_base_border'
    MINING = 'mod_refer_base_mining'
    MINING_PLANET = 'mod_refer_base_mining_planet'
    ASTEROID = 'mod_refer_base_asteroid_station'
    RH_PLANET = 'mod_refer_base_rheinland_planet'
    LI_PLANET = 'mod_refer_base_liberty_planet'
    BR_PLANET = 'mod_refer_base_bretonia_planet'
    KU_PLANET = 'mod_refer_base_kusari_planet'
    CO_PLANET = 'mod_refer_base_corsairs_planet'
    OU_PLANET = 'mod_refer_base_outcasts_planet'
    PI_PLANET = 'mod_refer_base_pirates_planet'
    RH_GASMINER = 'mod_refer_base_rheinland_gasmining'
    LI_GASMINER = 'mod_refer_base_liberty_gasmining'
    BR_GASMINER = 'mod_refer_base_bretonia_gasmining'
    KU_GASMINER = 'mod_refer_base_kusari_gasmining'
    CO_GASMINER = 'mod_refer_base_corsairs_gasmining'
    PI_GASMINER = 'mod_refer_base_pirates_gasmining'


class SpaceCostume(object):
    DEFAULT = 'rh_captain_head, rh_male_guard_body, prop_hat_male_rh_grd_visor, prop_neuralnet_b_right'
    ROBOT_A = ', robot_body_A'
    ROBOT_B = ', robot_body_B'
    ROBOT_C = ', robot_body_C'
    ROBOT_D = ', robot_body_D'
    ROBOT_E = ', robot_body_E'

    ROBOTS = [
        ROBOT_A, ROBOT_B, ROBOT_C, ROBOT_D, ROBOT_E
    ]

    @staticmethod
    def random_robot():
        return random.choice(SpaceCostume.ROBOTS)


class L(object):
    def __init__(self, code, ru_text, kind=None):
        self.code = code
        self.ru_text = ru_text
        self.kind = kind


NAME_AT_END = 1


class ShipVoice(object):
    LINES = [
        L('gcs_combat_announce_allclear_01-', 'Противников не обнаружено'),
        L('gcs_combat_announce_allclear_02-', 'На сканерах больше нет неприятелей'),
        L('gcs_combat_announce_allclear_03-', 'Зона зачищена'),
        L('gcs_combat_announce_allclear_04-', 'Врагов не видно'),
        L('gcs_combat_announce_allclear_05-', 'Зона в зеленом статусе. Врагов не обнаружено'),
        L('gcs_combat_announce_allclear_06-', 'Зона чиста. Враждебные контактсы отсутствуют'),
        # L('gcs_combat_announce_combatdrift_01-', ),
        # L('gcs_combat_announce_combatdrift_02-', ),
        # L('gcs_combat_announce_combatdrift_03-', ),
        L('gcs_combat_announce_enemysighted_01-', 'Вижу нового неприятеля'),
        L('gcs_combat_announce_enemysighted_02-', 'На радаре новый противник'),
        L('gcs_combat_announce_enemysighted_03-', 'Замечена новая угроза. Неприятель'),
        L('gcs_combat_announce_enemysighted_04-', 'На сканере замечены неприятели!'),
        L('gcs_combat_announce_ff_01-', 'Смотри куда стреляешь!'),
        L('gcs_combat_announce_ff_02-', 'Прекрати стрелять, фрилансер!'),
        L('gcs_combat_announce_ff_03-', 'Хватит стрелять по мне!'),
        L('gcs_combat_announce_flee_01-', 'Уходим!'),
        L('gcs_combat_announce_flee_02-', 'Я улетаю!'),
        L('gcs_combat_announce_flee_03-', 'К чёрту всё, я улетаю отсюда'),
        L('gcs_combat_announce_flee_04-', 'Я отступаю'),
        L('gcs_combat_announce_flee_05-', 'Мне нужна прегрупировка'),
        L('gcs_combat_announce_flee_06-', 'Я сваливаю отсюда'),
        L('gcs_combat_askengage_01-', 'Разрешите атаковать'),
        L('gcs_combat_askengage_02-', 'Запрашиваю открыть огонь'),
        L('gcs_combat_askengage_03-', 'Ожидаю приказа на перехват'),
        L('gcs_combat_askengage_04-', 'Запрашиваю разрешение открыть огонь!'),
        L('gcs_combat_askforhelp_01-', 'Мне нужна поддержка!'),
        L('gcs_combat_askforhelp_02-', 'Запращиваю поддержку!'),
        L('gcs_combat_askforhelp_03-', 'Прикройте меня!'),
        L('gcs_combat_askforhelp_04-', 'Нужна поддержка!'),
        L('gcs_combat_askforhelp_05-', 'Запрашиваю дополнительную поддержку!'),
        L('gcs_combat_brag_01-', 'Неприятель уничтожен'),
        L('gcs_combat_brag_02-', 'Враг уничтожен'),
        L('gcs_combat_brag_03-', 'Вражеская цель ликвидирована'),
        L('gcs_combat_brag_04-', 'Неприятель ликвидирован'),
        L('gcs_combat_brag_05-', 'Враг нейтрализован'),
        L('gcs_combat_brag_06-', 'Неприятель был нейтрализован'),
        L('gcs_combat_comingin_p_01-', 'Мы на пути к тебе'),
        L('gcs_combat_comingin_p_02-', 'Подожди, скоро будем тут'),
        L('gcs_combat_comingin_p_03-', 'Жди, летим к тебе'),
        L('gcs_combat_comingin_s_01-', 'Я скоро буду здесь'),
        L('gcs_combat_comingin_s_02-', 'Я в пути'),
        L('gcs_combat_comingin_s_03-', 'Жди, я лечу к тебе'),
        L('gcs_combat_deathsympathy_01-', 'Нашего сбили!'),
        L('gcs_combat_deathsympathy_02-', 'Я потерял ведомого!'),
        L('gcs_combat_deathsympathy_03-', 'Член крыла убит!'),
        L('gcs_combat_deathsympathy_04-', 'Моего сбили!'),
        L('gcs_combat_engaging_01+', 'Готовлюсь к перехвату', NAME_AT_END),
        L('gcs_combat_engaging_02+', 'Я перехватываю', NAME_AT_END),
        L('gcs_combat_engaging_03+', 'Перехватываю', NAME_AT_END),
        L('gcs_combat_engaging_04+', 'Приступаю к перехвату', NAME_AT_END),
        # L('gcs_combat_fleereason_damaged_01-', ),
        # L('gcs_combat_fleereason_damaged_02-', ),
        # L('gcs_combat_fleereason_damaged_03-', ),
        # L('gcs_combat_fleereason_noweapons_01-', ),
        # L('gcs_combat_fleereason_noweapons_02-', ),
        # L('gcs_combat_fleereason_noweapons_03-', ),
        # L('gcs_combat_fleereason_other_01-', ),
        # L('gcs_combat_fleereason_other_02-', ),
        # L('gcs_combat_fleereason_other_03-', ),
        # L('gcs_combat_fleereason_tough_01-', ),
        # L('gcs_combat_fleereason_tough_02-', ),
        # L('gcs_combat_fleereason_tough_03-', ),
        # L('gcs_combat_hasinsights_01-', ),
        # L('gcs_combat_hasinsights_02-', ),
        # L('gcs_combat_hasinsights_03-', ),
        # L('gcs_combat_hasinsights_04-', ),
        # L('gcs_combat_hasinsights_05-', ),
        # L('gcs_combat_hasinsights_06-', ),
        # L('gcs_combat_inflicting_damage_01-', ),
        # L('gcs_combat_inflicting_damage_02-', ),
        # L('gcs_combat_inflicting_damage_03-', ),
        # L('gcs_combat_inflicting_damage_04-', ),
        # L('gcs_combat_inflicting_damage_05-', ),
        # L('gcs_combat_inflicting_damage_06-', ),
        # L('gcs_combat_inflicting_damage_worst_01-', ),
        # L('gcs_combat_inflicting_damage_worst_02-', ),
        # L('gcs_combat_inflicting_damage_worst_03-', ),
        # L('gcs_combat_inflicting_damage_worst_04-', ),
        # L('gcs_combat_inflicting_damage_worst_05-', ),
        # L('gcs_combat_inflicting_damage_worst_06-', ),
        # L('gcs_combat_insights_01-', ),
        # L('gcs_combat_insights_02-', ),
        # L('gcs_combat_insights_03-', ),
        # L('gcs_combat_insights_04-', ),
        # L('gcs_combat_insights_05-', ),
        # L('gcs_combat_insights_06-', ),
        # L('gcs_combat_noengagereason_toofar_01-', ),
        # L('gcs_combat_noengagereason_toofar_02-', ),
        # L('gcs_combat_noengagereason_toofar_03-', ),
        # L('gcs_combat_noengagereason_tootough_01-', ),
        # L('gcs_combat_noengagereason_tootough_02-', ),
        # L('gcs_combat_noengagereason_tootough_03-', ),
        # L('gcs_combat_noengaging_01+', ),
        # L('gcs_combat_noengaging_02+', ),
        # L('gcs_combat_offerhelp_01-', ),
        # L('gcs_combat_offerhelp_02-', ),
        # L('gcs_combat_offerhelp_03-', ),
        # L('gcs_combat_offerhelp_04-', ),
        # L('gcs_combat_offerhelp_05-', ),
        # L('gcs_combat_order_disengage_01-', ),
        # L('gcs_combat_order_disengage_02-', ),
        # L('gcs_combat_order_disengage_03-', ),
        # L('gcs_combat_order_disengage_04-', ),
        # L('gcs_combat_order_disengage_05-', ),
        # L('gcs_combat_order_engage_01-', ),
        # L('gcs_combat_order_engage_02-', ),
        # L('gcs_combat_order_engage_03-', ),
        # L('gcs_combat_order_engage_04-', ),
        # L('gcs_combat_order_engage_05-', ),
        # L('gcs_combat_order_engage_06-', ),
        # L('gcs_combat_order_noengage_01-', ),
        # L('gcs_combat_order_noengage_02-', ),
        # L('gcs_combat_order_noengage_03-', ),
        # L('gcs_combat_order_noengage_04-', ),
        # L('gcs_combat_order_retreattowards_01+', ),
        # L('gcs_combat_order_retreattowards_02+', ),
        # L('gcs_combat_order_retreattowards_03+', ),
        # L('gcs_combat_order_retreattowards_04+', ),
        # L('gcs_combat_order_retreattowards_05+', ),
        # L('gcs_combat_order_retreattowards_06+', ),
        # L('gcs_combat_rejoiningform_01-', ),
        # L('gcs_combat_rejoiningform_02-', ),
        # L('gcs_combat_resume_patrol_01-', ),
        # L('gcs_combat_resume_patrol_02-', ),
        # L('gcs_combat_resume_patrol_03-', ),
        # L('gcs_combat_resume_patrol_04-', ),
        # L('gcs_combat_resume_trade_01+', ),
        # L('gcs_combat_resume_trade_02+', ),
        # L('gcs_combat_resume_trade_03+', ),
        # L('gcs_combat_resume_trade_04+', ),
        # L('gcs_combat_scream_01-', ),
        # L('gcs_combat_scream_02-', ),
        # L('gcs_combat_scream_03-', ),
        # L('gcs_combat_scream_04-', ),
        # L('gcs_combat_scream_05-', ),
        # L('gcs_combat_scream_06-', ),
        # L('gcs_combat_scream_07-', ),
        # L('gcs_combat_scream_08-', ),
        # L('gcs_combat_taking_damage_01-', ),
        # L('gcs_combat_taking_damage_02-', ),
        # L('gcs_combat_taking_damage_03-', ),
        # L('gcs_combat_taking_damage_04-', ),
        # L('gcs_combat_taking_damage_05-', ),
        # L('gcs_combat_taking_damage_06-', ),
        # L('gcs_combat_taking_damage_07-', ),
        # L('gcs_combat_taking_damage_08-', ),
        # L('gcs_combat_taking_damage_worst_01-', ),
        # L('gcs_combat_taking_damage_worst_02-', ),
        # L('gcs_combat_taking_damage_worst_03-', ),
        # L('gcs_combat_taking_damage_worst_04-', ),
        # L('gcs_combat_taking_damage_worst_05-', ),
        # L('gcs_combat_taking_damage_worst_06-', ),
        # L('gcs_combat_taking_damage_worst_07-', ),
        # L('gcs_combat_taking_damage_worst_08-', ),
        # L('gcs_combat_takinglead_01-', ),
        # L('gcs_combat_takinglead_02-', ),
        # L('gcs_combat_takinglead_03-', ),
        # L('gcs_combat_takinglead_04-', ),
        # L('gcs_dhail_angry_response_01-', ),
        # L('gcs_dockhail_hailee_datasubmit_01-', ),
        # L('gcs_dockhail_hailee_datasubmit_02-', ),
        # L('gcs_dockrequest_goingto_01+', ),
        # L('gcs_dockrequest_jumpgatedelayed_01-', ),
        # L('gcs_dockrequest_jumpgateopen_01-', ),
        # L('gcs_dockrequest_jumpgateopenafterdelay_01-', ),
        # L('gcs_dockrequest_request_01+', ),
        # L('gcs_dockrequest_request_02+', ),
        # L('gcs_dockrequest_thankshelp_01-', ),
        # L('gcs_dockrequest_thisourstop_01-', ),
        # L('gcs_dockrequest_todock-', ),
        # L('gcs_dockrequest_toland-', ),
        # L('gcs_dockrequest_tomoor-', ),
        # L('gcs_dockrequest_tradelanestart_01-', ),
        # L('gcs_fidget_patrol_wpremainquery_01-', ),
        # L('gcs_fidget_patrolrumor_01-', ),
        # L('gcs_fidget_patrolsimple_01-', ),
        # L('gcs_fidget_saystatus_damagelarge_01-', ),
        # L('gcs_fidget_saystatus_damagemedium_01-', ),
        # L('gcs_fidget_saystatus_damagenone_01-', ),
        # L('gcs_fidget_saystatus_damagesmall_01-', ),
        # L('gcs_fidget_talkcargo_01-', ),
        # L('gcs_fidget_trade_ihear_01+', ),
        # L('gcs_fidget_trade_simple_01-', ),
        # L('gcs_fidget_trade_simple_02-', ),
        # L('gcs_fidget_trade_simple_03-', ),
        # L('gcs_fidget_traderumor_01-', ),
        # L('gcs_fidget_whatstatus_01-', ),
        # L('gcs_gen_commodity_alienartifacts', ),
        # L('gcs_gen_commodity_alienorganisms', ),
        # L('gcs_gen_commodity_basicalloys', ),
        # L('gcs_gen_commodity_beryllium', ),
        # L('gcs_gen_commodity_boron', ),
        # L('gcs_gen_commodity_cardamine', ),
        # L('gcs_gen_commodity_cobalt', ),
        # L('gcs_gen_commodity_constmachinery', ),
        # L('gcs_gen_commodity_consumergoods', ),
        # L('gcs_gen_commodity_copper', ),
        # L('gcs_gen_commodity_diamonds', ),
        # L('gcs_gen_commodity_enginecomponents', ),
        # L('gcs_gen_commodity_fertilizers', ),
        # L('gcs_gen_commodity_foodrations', ),
        # L('gcs_gen_commodity_gold', ),
        # L('gcs_gen_commodity_hfuel', ),
        # L('gcs_gen_commodity_hightempalloys', ),
        # L('gcs_gen_commodity_hullpanels', ),
        # L('gcs_gen_commodity_hydrocarbon', ),
        # L('gcs_gen_commodity_luxuryfoods', ),
        # L('gcs_gen_commodity_luxurygoods', ),
        # L('gcs_gen_commodity_miningmachinery', ),
        # L('gcs_gen_commodity_moxfuel', ),
        # L('gcs_gen_commodity_niobium', ),
        # L('gcs_gen_commodity_opticalchips', ),
        # L('gcs_gen_commodity_optronics', ),
        # L('gcs_gen_commodity_oxygen', ),
        # L('gcs_gen_commodity_pharmaceuticals', ),
        # L('gcs_gen_commodity_polymers', ),
        # L('gcs_gen_commodity_scrapmetal', ),
        # L('gcs_gen_commodity_sidearms', ),
        # L('gcs_gen_commodity_silver', ),
        # L('gcs_gen_commodity_superalloys', ),
        # L('gcs_gen_commodity_superconductors', ),
        # L('gcs_gen_commodity_terraforminggases', ),
        # L('gcs_gen_commodity_toxicwaste', ),
        # L('gcs_gen_commodity_tradelaneparts', ),
        # L('gcs_gen_commodity_water', ),
        # L('gcs_misc_ack_01-', ),
        # L('gcs_misc_ack_02-', ),
        # L('gcs_misc_ack_03-', ),
        # L('gcs_misc_attentionallwingmen_01+', ),
        # L('gcs_misc_dash', ),
        # L('gcs_misc_from', ),
        # L('gcs_misc_goingto_p_01+', ),
        # L('gcs_misc_goingto_s_01+', ),
        # L('gcs_misc_number_0', ),
        # L('gcs_misc_number_0-', ),
        # L('gcs_misc_number_1', ),
        # L('gcs_misc_number_1-', ),
        # L('gcs_misc_number_10', ),
        # L('gcs_misc_number_10-', ),
        # L('gcs_misc_number_11', ),
        # L('gcs_misc_number_11-', ),
        # L('gcs_misc_number_12', ),
        # L('gcs_misc_number_12-', ),
        # L('gcs_misc_number_13', ),
        # L('gcs_misc_number_13-', ),
        # L('gcs_misc_number_14', ),
        # L('gcs_misc_number_14-', ),
        # L('gcs_misc_number_15', ),
        # L('gcs_misc_number_15-', ),
        # L('gcs_misc_number_16', ),
        # L('gcs_misc_number_16-', ),
        # L('gcs_misc_number_17', ),
        # L('gcs_misc_number_17-', ),
        # L('gcs_misc_number_18', ),
        # L('gcs_misc_number_18-', ),
        # L('gcs_misc_number_19', ),
        # L('gcs_misc_number_19-', ),
        # L('gcs_misc_number_2', ),
        # L('gcs_misc_number_2-', ),
        # L('gcs_misc_number_20', ),
        # L('gcs_misc_number_20-', ),
        # L('gcs_misc_number_3', ),
        # L('gcs_misc_number_3-', ),
        # L('gcs_misc_number_4', ),
        # L('gcs_misc_number_4-', ),
        # L('gcs_misc_number_5', ),
        # L('gcs_misc_number_5-', ),
        # L('gcs_misc_number_6', ),
        # L('gcs_misc_number_6-', ),
        # L('gcs_misc_number_7', ),
        # L('gcs_misc_number_7-', ),
        # L('gcs_misc_number_8', ),
        # L('gcs_misc_number_8-', ),
        # L('gcs_misc_number_9', ),
        # L('gcs_misc_number_9-', ),
        # L('gcs_misc_thisis+', ),
        # L('gcs_misc_to', ),
        # L('gcs_patrol_finished_p_01-', ),
        # L('gcs_patrol_finished_s_01-', ),
        # L('gcs_patrol_idhome_p_01+', ),
        # L('gcs_patrol_idhome_p_02+', ),
        # L('gcs_patrol_idhome_s_01+', ),
        # L('gcs_patrol_idhome_s_02+', ),
        # L('gcs_patrol_ihave+', ),
        # L('gcs_patrol_ihaveonly+', ),
        # L('gcs_patrol_morewpstogo-', ),
        # L('gcs_patrol_morewptogo-', ),
        # L('gcs_patrol_wehave+', ),
        # L('gcs_patrol_wehaveonly+', ),
        # L('gcs_phail_blowoff_01-', ),
        # L('gcs_phail_blowoff_02-', ),
        # L('gcs_phail_combatblowoff_01-', ),
        # L('gcs_refer_base_AstMiner_base-', ),
        # L('gcs_refer_base_Br01_01_base-', ),
        # L('gcs_refer_base_Br01_02_base-', ),
        # L('gcs_refer_base_Br01_03_base-', ),
        # L('gcs_refer_base_Br01_04_base-', ),
        # L('gcs_refer_base_Br01_05_base-', ),
        # L('gcs_refer_base_Br01_06_base-', ),
        # L('gcs_refer_base_Br01_07_base-', ),
        # L('gcs_refer_base_Br01_08_base-', ),
        # L('gcs_refer_base_Br02_01_base-', ),
        # L('gcs_refer_base_Br02_02_base-', ),
        # L('gcs_refer_base_Br02_03_base-', ),
        # L('gcs_refer_base_Br02_04_base-', ),
        # L('gcs_refer_base_Br02_05_base-', ),
        # L('gcs_refer_base_Br03_01_base-', ),
        # L('gcs_refer_base_Br03_02_base-', ),
        # L('gcs_refer_base_Br03_03_base-', ),
        # L('gcs_refer_base_Br03_04_base-', ),
        # L('gcs_refer_base_Br04_01_base-', ),
        # L('gcs_refer_base_Br04_02_base-', ),
        # L('gcs_refer_base_Br04_03_base-', ),
        # L('gcs_refer_base_Br04_04_base-', ),
        # L('gcs_refer_base_Br04_05_base-', ),
        # L('gcs_refer_base_Br04_06_base-', ),
        # L('gcs_refer_base_Br05_01_base-', ),
        # L('gcs_refer_base_Br05_02_base-', ),
        # L('gcs_refer_base_Br05_03_base-', ),
        # L('gcs_refer_base_Br05_04_base-', ),
        # L('gcs_refer_base_Br05_05_base-', ),
        # L('gcs_refer_base_Br06_01_base-', ),
        # L('gcs_refer_base_Br06_02_base-', ),
        # L('gcs_refer_base_Br06_03_base-', ),
        # L('gcs_refer_base_Br06_04_base-', ),
        # L('gcs_refer_base_Bw01_02_base-', ),
        # L('gcs_refer_base_Bw01_03_base-', ),
        # L('gcs_refer_base_Bw01_04_base-', ),
        # L('gcs_refer_base_Bw02_01_base-', ),
        # L('gcs_refer_base_Bw02_02_base-', ),
        # L('gcs_refer_base_Bw03_01_base-', ),
        # L('gcs_refer_base_Bw03_02_base-', ),
        # L('gcs_refer_base_Bw03_03_base-', ),
        # L('gcs_refer_base_Bw04_01_base-', ),
        # L('gcs_refer_base_Bw04_02_base-', ),
        # L('gcs_refer_base_Bw05_01_base-', ),
        # L('gcs_refer_base_Bw05_02_base-', ),
        # L('gcs_refer_base_Bw05_03_base-', ),
        # L('gcs_refer_base_Bw06_01_base-', ),
        # L('gcs_refer_base_Bw06_02_base-', ),
        # L('gcs_refer_base_Bw07_01_base-', ),
        # L('gcs_refer_base_Bw07_02_base-', ),
        # L('gcs_refer_base_Bw08_01_base-', ),
        # L('gcs_refer_base_Bw08_02_base-', ),
        # L('gcs_refer_base_Bw08_03_base-', ),
        # L('gcs_refer_base_Bw09_01_base-', ),
        # L('gcs_refer_base_Bw09_02_base-', ),
        # L('gcs_refer_base_Bw09_03_base-', ),
        # L('gcs_refer_base_Bw10_01_base-', ),
        # L('gcs_refer_base_Bw10_02_base-', ),
        # L('gcs_refer_base_Ew01_01_base-', ),
        # L('gcs_refer_base_Ew01_02_base-', ),
        # L('gcs_refer_base_Ew02_01_base-', ),
        # L('gcs_refer_base_Ew03_01_base-', ),
        # L('gcs_refer_base_Ew03_02_base-', ),
        # L('gcs_refer_base_Ew04_01_base-', ),
        # L('gcs_refer_base_GasMiner_base-', ),
        # L('gcs_refer_base_Hi01_01_base-', ),
        # L('gcs_refer_base_Hi02_01_base-', ),
        # L('gcs_refer_base_Hi02_02_base-', ),
        # L('gcs_refer_base_Iw01_01_base-', ),
        # L('gcs_refer_base_Iw01_02_base-', ),
        # L('gcs_refer_base_Iw02_01_base-', ),
        # L('gcs_refer_base_Iw02_02_base-', ),
        # L('gcs_refer_base_Iw03_01_base-', ),
        # L('gcs_refer_base_Iw03_02_base-', ),
        # L('gcs_refer_base_Iw04_01_base-', ),
        # L('gcs_refer_base_Iw04_02_base-', ),
        # L('gcs_refer_base_Iw05_01_base-', ),
        # L('gcs_refer_base_Iw05_02_base-', ),
        # L('gcs_refer_base_Iw06_01_base-', ),
        # L('gcs_refer_base_Iw06_02_base-', ),
        # L('gcs_refer_base_Ku01_01_base-', ),
        # L('gcs_refer_base_Ku01_02_base-', ),
        # L('gcs_refer_base_Ku01_03_base-', ),
        # L('gcs_refer_base_Ku01_04_base-', ),
        # L('gcs_refer_base_Ku01_05_base-', ),
        # L('gcs_refer_base_Ku01_06_base-', ),
        # L('gcs_refer_base_Ku01_07_base-', ),
        # L('gcs_refer_base_Ku02_01_base-', ),
        # L('gcs_refer_base_Ku02_02_base-', ),
        # L('gcs_refer_base_Ku02_03_base-', ),
        # L('gcs_refer_base_Ku02_04_base-', ),
        # L('gcs_refer_base_Ku02_05_base-', ),
        # L('gcs_refer_base_Ku03_01_base-', ),
        # L('gcs_refer_base_Ku03_02_base-', ),
        # L('gcs_refer_base_Ku03_03_base-', ),
        # L('gcs_refer_base_Ku03_04_base-', ),
        # L('gcs_refer_base_Ku03_05_base-', ),
        # L('gcs_refer_base_Ku04_01_base-', ),
        # L('gcs_refer_base_Ku04_02_base-', ),
        # L('gcs_refer_base_Ku04_03_base-', ),
        # L('gcs_refer_base_Ku04_04_base-', ),
        # L('gcs_refer_base_Ku04_05_base-', ),
        # L('gcs_refer_base_Ku04_06_base-', ),
        # L('gcs_refer_base_Ku05_01_base-', ),
        # L('gcs_refer_base_Ku05_02_base-', ),
        # L('gcs_refer_base_Ku05_03_base-', ),
        # L('gcs_refer_base_Ku05_04_base-', ),
        # L('gcs_refer_base_Ku06_01_base-', ),
        # L('gcs_refer_base_LI01_01_BASE-', ),
        # L('gcs_refer_base_LI01_02_BASE-', ),
        # L('gcs_refer_base_LI01_03_BASE-', ),
        # L('gcs_refer_base_LI01_06_BASE-', ),
        # L('gcs_refer_base_LI01_07_BASE-', ),
        # L('gcs_refer_base_LI01_08_BASE-', ),
        # L('gcs_refer_base_LI01_09_BASE-', ),
        # L('gcs_refer_base_LI01_10_BASE-', ),
        # L('gcs_refer_base_LI01_11_BASE-', ),
        # L('gcs_refer_base_LI01_12_BASE-', ),
        # L('gcs_refer_base_Li01_13_base-', ),
        # L('gcs_refer_base_Li01_14_base-', ),
        # L('gcs_refer_base_Li02_01_base-', ),
        # L('gcs_refer_base_Li02_02_base-', ),
        # L('gcs_refer_base_Li02_03_base-', ),
        # L('gcs_refer_base_Li02_04_base-', ),
        # L('gcs_refer_base_Li02_05_base-', ),
        # L('gcs_refer_base_Li02_06_base-', ),
        # L('gcs_refer_base_Li03_01_base-', ),
        # L('gcs_refer_base_Li03_02_base-', ),
        # L('gcs_refer_base_Li03_03_base-', ),
        # L('gcs_refer_base_Li03_04_base-', ),
        # L('gcs_refer_base_Li04_01_base-', ),
        # L('gcs_refer_base_Li04_02_base-', ),
        # L('gcs_refer_base_Li04_03_base-', ),
        # L('gcs_refer_base_Li04_04_base-', ),
        # L('gcs_refer_base_Li04_05_base-', ),
        # L('gcs_refer_base_Rh01_01_base-', ),
        # L('gcs_refer_base_Rh01_02_base-', ),
        # L('gcs_refer_base_Rh01_03_base-', ),
        # L('gcs_refer_base_Rh01_04_base-', ),
        # L('gcs_refer_base_Rh01_05_base-', ),
        # L('gcs_refer_base_Rh01_06_base-', ),
        # L('gcs_refer_base_Rh01_07_base-', ),
        # L('gcs_refer_base_Rh01_08_base-', ),
        # L('gcs_refer_base_Rh02_01_base-', ),
        # L('gcs_refer_base_Rh02_02_base-', ),
        # L('gcs_refer_base_Rh02_03_base-', ),
        # L('gcs_refer_base_Rh02_04_base-', ),
        # L('gcs_refer_base_Rh02_05_base-', ),
        # L('gcs_refer_base_Rh02_06_base-', ),
        # L('gcs_refer_base_Rh03_01_base-', ),
        # L('gcs_refer_base_Rh03_02_base-', ),
        # L('gcs_refer_base_Rh03_03_base-', ),
        # L('gcs_refer_base_Rh03_04_base-', ),
        # L('gcs_refer_base_Rh03_05_base-', ),
        # L('gcs_refer_base_Rh03_06_base-', ),
        # L('gcs_refer_base_Rh04_01_base-', ),
        # L('gcs_refer_base_Rh04_02_base-', ),
        # L('gcs_refer_base_Rh04_03_base-', ),
        # L('gcs_refer_base_Rh04_04_base-', ),
        # L('gcs_refer_base_Rh04_05_base-', ),
        # L('gcs_refer_base_Rh05_01_base-', ),
        # L('gcs_refer_base_Rh05_02_base-', ),
        # L('gcs_refer_base_Rh05_03_base-', ),
        # L('gcs_refer_base_Rh05_04_base-', ),
        # L('gcs_refer_base_yourplanet-', ),
        # L('gcs_refer_base_yourstation-', ),
        # L('gcs_refer_faction_br_m_short', ),
        # L('gcs_refer_faction_br_n_short', ),
        # L('gcs_refer_faction_br_p_short', ),
        # L('gcs_refer_faction_co_alg_short', ),
        # L('gcs_refer_faction_co_be_short', ),
        # L('gcs_refer_faction_co_hsp_short', ),
        # L('gcs_refer_faction_co_ic_short', ),
        # L('gcs_refer_faction_co_khc_short', ),
        # L('gcs_refer_faction_co_kt_short', ),
        # L('gcs_refer_faction_co_me_short', ),
        # L('gcs_refer_faction_co_ni_short', ),
        # L('gcs_refer_faction_co_nws_short', ),
        # L('gcs_refer_faction_co_os_short', ),
        # L('gcs_refer_faction_co_rs_short', ),
        # L('gcs_refer_faction_co_shi_short', ),
        # L('gcs_refer_faction_co_ss_short', ),
        # L('gcs_refer_faction_co_ti_short', ),
        # L('gcs_refer_faction_co_vr_short', ),
        # L('gcs_refer_faction_fc_b_short', ),
        # L('gcs_refer_faction_fc_bd_short', ),
        # L('gcs_refer_faction_fc_c_short', ),
        # L('gcs_refer_faction_fc_fa_short', ),
        # L('gcs_refer_faction_fc_g_short', ),
        # L('gcs_refer_faction_fc_gc_short', ),
        # L('gcs_refer_faction_fc_h_short', ),
        # L('gcs_refer_faction_fc_j_short', ),
        # L('gcs_refer_faction_fc_lh_short', ),
        # L('gcs_refer_faction_fc_lr_short', ),
        # L('gcs_refer_faction_fc_lwb_short', ),
        # L('gcs_refer_faction_fc_m_short', ),
        # L('gcs_refer_faction_fc_or_short', ),
        # L('gcs_refer_faction_fc_ou_short', ),
        # L('gcs_refer_faction_fc_rh_short', ),
        # L('gcs_refer_faction_fc_u_short', ),
        # L('gcs_refer_faction_fc_x_short', ),
        # L('gcs_refer_faction_gd_bh_short', ),
        # L('gcs_refer_faction_gd_gm_short', ),
        # L('gcs_refer_faction_gd_im_short', ),
        # L('gcs_refer_faction_gd_z_short', ),
        # L('gcs_refer_faction_ku_n_short', ),
        # L('gcs_refer_faction_ku_p_short', ),
        # L('gcs_refer_faction_li_lsf_short', ),
        # L('gcs_refer_faction_li_n_short', ),
        # L('gcs_refer_faction_li_p_short', ),
        # L('gcs_refer_faction_player_short', ),
        # L('gcs_refer_faction_rh_m_short', ),
        # L('gcs_refer_faction_rh_n_short', ),
        # L('gcs_refer_faction_rh_p_short', ),
        # L('gcs_refer_faction_rh_short', ),
        # L('gcs_refer_formationdesig_01', ),
        # L('gcs_refer_formationdesig_02', ),
        # L('gcs_refer_formationdesig_03', ),
        # L('gcs_refer_formationdesig_04', ),
        # L('gcs_refer_formationdesig_05', ),
        # L('gcs_refer_formationdesig_06', ),
        # L('gcs_refer_formationdesig_07', ),
        # L('gcs_refer_formationdesig_08', ),
        # L('gcs_refer_formationdesig_09', ),
        # L('gcs_refer_formationdesig_10', ),
        # L('gcs_refer_formationdesig_11', ),
        # L('gcs_refer_formationdesig_12', ),
        # L('gcs_refer_formationdesig_13', ),
        # L('gcs_refer_formationdesig_14', ),
        # L('gcs_refer_formationdesig_15', ),
        # L('gcs_refer_formationdesig_16', ),
        # L('gcs_refer_formationdesig_17', ),
        # L('gcs_refer_formationdesig_18', ),
        # L('gcs_refer_formationdesig_19', ),
        # L('gcs_refer_formationdesig_20', ),
        # L('gcs_refer_formationdesig_21', ),
        # L('gcs_refer_formationdesig_22', ),
        # L('gcs_refer_formationdesig_23', ),
        # L('gcs_refer_formationdesig_24', ),
        # L('gcs_refer_formationdesig_25', ),
        # L('gcs_refer_formationdesig_26', ),
        # L('gcs_refer_formationdesig_27', ),
        # L('gcs_refer_formationdesig_28', ),
        # L('gcs_refer_formationdesig_29', ),
        # L('gcs_refer_system_Br01-', ),
        # L('gcs_refer_system_Br02-', ),
        # L('gcs_refer_system_Br03-', ),
        # L('gcs_refer_system_Br04-', ),
        # L('gcs_refer_system_Br05-', ),
        # L('gcs_refer_system_Br06-', ),
        # L('gcs_refer_system_Bw01-', ),
        # L('gcs_refer_system_Bw02-', ),
        # L('gcs_refer_system_Bw03-', ),
        # L('gcs_refer_system_Bw04-', ),
        # L('gcs_refer_system_Bw05-', ),
        # L('gcs_refer_system_Bw06-', ),
        # L('gcs_refer_system_Bw07-', ),
        # L('gcs_refer_system_Bw08-', ),
        # L('gcs_refer_system_Bw09-', ),
        # L('gcs_refer_system_Bw10-', ),
        # L('gcs_refer_system_Ew01-', ),
        # L('gcs_refer_system_Ew02-', ),
        # L('gcs_refer_system_Ew03-', ),
        # L('gcs_refer_system_Ew04-', ),
        # L('gcs_refer_system_hi01-', ),
        # L('gcs_refer_system_hi02-', ),
        # L('gcs_refer_system_Iw01-', ),
        # L('gcs_refer_system_Iw02-', ),
        # L('gcs_refer_system_Iw03-', ),
        # L('gcs_refer_system_Iw04-', ),
        # L('gcs_refer_system_Iw05-', ),
        # L('gcs_refer_system_Iw06-', ),
        # L('gcs_refer_system_Ku01-', ),
        # L('gcs_refer_system_Ku02-', ),
        # L('gcs_refer_system_Ku03-', ),
        # L('gcs_refer_system_Ku04-', ),
        # L('gcs_refer_system_Ku05-', ),
        # L('gcs_refer_system_Ku06-', ),
        # L('gcs_refer_system_Ku07-', ),
        # L('gcs_refer_system_Li01-', ),
        # L('gcs_refer_system_Li02-', ),
        # L('gcs_refer_system_Li03-', ),
        # L('gcs_refer_system_Li04-', ),
        # L('gcs_refer_system_Li05-', ),
        # L('gcs_refer_system_Rh01-', ),
        # L('gcs_refer_system_Rh02-', ),
        # L('gcs_refer_system_Rh03-', ),
        # L('gcs_refer_system_Rh04-', ),
        # L('gcs_refer_system_Rh05-', ),
        # L('gcs_refer_system_St01-', ),
        # L('gcs_scan_angry_01-', ),
        # L('gcs_scan_angry_02-', ),
        # L('gcs_scan_angry_03-', ),
        # L('gcs_scan_announce_01-', ),
        # L('gcs_scan_announce_02-', ),
        # L('gcs_scan_announce_03-', ),
        # L('gcs_scan_comply_01-', ),
        # L('gcs_scan_comply_02-', ),
        # L('gcs_scan_comply_03-', ),
        # L('gcs_scan_happy_01-', ),
        # L('gcs_scan_happy_02-', ),
        # L('gcs_scan_happy_03-', ),
        # L('gcs_scan_lootdestroyed_01-', ),
        # L('gcs_scan_lootdestroyed_02-', ),
        # L('gcs_scan_lootdestroyed_03-', ),
        # L('gcs_scan_nothingfound_01-', ),
        # L('gcs_scan_nothingfound_02-', ),
        # L('gcs_scan_nothingfound_03-', ),
        # L('gcs_scan_orderdrop_01-', ),
        # L('gcs_scan_orderdrop_02-', ),
        # L('gcs_scan_orderdrop_03-', ),
        # L('gcs_scan_refuse_01-', ),
        # L('gcs_scan_refuse_02-', ),
        # L('gcs_scan_refuse_03-', ),
        # L('gcs_trade_carrying_p_01+', ),
        # L('gcs_trade_carrying_s_01+', ),
        # L('gcs_trade_idhome_p_01+', ),
        # L('gcs_trade_idhome_p_02+', ),
        # L('gcs_trade_idhome_s_01+', ),
        # L('gcs_trade_idhome_s_02+', ),
        # L('gcs_trade_wanttoget_p_01+', ),
        # L('gcs_trade_wanttoget_s_01+', ),
        # L('rms_bigshiptaunt_01-', ),
        # L('rms_bigshiptaunt_02-', ),
        # L('rms_bigshiptaunt_03-', ),
        # L('rms_defendleader_01-', ),
        # L('rms_defendleader_02-', ),
        # L('rms_defendleader_03-', ),
        # L('rms_defendsolar_01-', ),
        # L('rms_defendsolar_02-', ),
        # L('rms_defendsolar_03-', ),
        # L('rms_friendlyarrival_01-', ),
        # L('rms_friendlyarrival_02-', ),
        # L('rms_friendlyarrival_03-', ),
        # L('rms_friendlyarrival_04-', ),
        # L('rms_friendlywelcome_01-', ),
        # L('rms_friendlywelcome_02-', ),
        # L('rms_friendlywelcome_03-', ),
        # L('rms_friendlywelcome_04-', ),
        # L('rms_shiprunning_01-', ),
        # L('rms_shiprunning_02-', ),
        # L('rms_shiprunning_03-', ),
        # L('rms_smallshiptaunt_01-', ),
        # L('rms_smallshiptaunt_02-', ),
        # L('rms_smallshiptaunt_03-', ),
        # L('rms_smallshiptaunt_04-', ),
        # L('rms_targetrunning_01-', ),
        # L('rms_targetrunning_02-', ),
        # L('rms_targetrunning_03-', ),
        # L('rms_targetrunning_04-', ),
    ]

    @classmethod
    def get_id_map(cls):
        map = []
        for line in cls.LINES:
            map.append(
                (
                    line.code.lower(),
                    CreateId.get_hex_id(line).lower()
                )
            )
        return map


