

;RH_SHIP
[Ship]
{{ rfr.root }}
LODranges = 0, 1000, 5000, 10000
msg_id_prefix = gcs_refer_shiparch_Rhef
mission_property = can_use_berths
type = FIGHTER
DA_archetype = ships\rheinland\rh{{ prefix }}_freighter\rh{{ prefix }}_freighter.cmp
material_library = ships\rheinland\rh{{ prefix }}_playerships.mat
material_library = fx\envmapbasic.mat
envmap_material = envmapship
cockpit = cockpits\rheinland\r_freighter.ini
pilot_mesh = generic_pilot
linear_drag = 1.000000
max_bank_angle = 1 ;15
camera_offset = 13, 52
camera_angular_acceleration = 0.025000
camera_horizontal_turn_angle = 20
camera_vertical_turn_up_angle = 5
camera_vertical_turn_down_angle = 20
camera_turn_look_ahead_slerp_amount = 1.000000
explosion_arch = explosion_rh
steering_torque = 48000.000000, 48000.000000, 104000.000000
angular_drag = 60000.000000, 60000.000000, 60000.000000
rotation_inertia = 16800.000000, 16800.000000, 16800.000000
nudge_force = 100000.000000
bay_door_anim = Sc_rh_freighter
bay_doors_open_snd = cargo_doors_open
bay_doors_close_snd = cargo_doors_close
HP_bay_surface = HpBayDoor01
HP_bay_external = HpBayDoor02
HP_tractor_source = HpTractor_Source
num_exhaust_nozzles = 2

[CollisionGroup]
obj = rh_port_side_lod1
separable = true
parent_impulse = 60.000000
child_impulse = 11.000000
debris_type = debris_small_ship
dmg_hp = DpPort_side panel
dmg_obj = rh_freighter_dmg_port_side_panel_cap
separation_explosion = explosion_small_ship_breakoff
mass = 5.000000
type = Port_Side_Panel
{{ rfr.panel1 }}

[CollisionGroup]
obj = rh_star_side_lod1
separable = true
parent_impulse = 60.000000
child_impulse = 11.000000
debris_type = debris_small_ship
dmg_hp = DpStarboard_side panel
dmg_obj = rh_freighter_dmg_starboard_side_panel_cap
separation_explosion = explosion_small_ship_breakoff
mass = 5.000000
type = Starboard_Side_Panel
{{ rfr.panel2 }}

[CollisionGroup]
obj = port_engine_lod1
separable = true
parent_impulse = 250.000000
child_impulse = 7.000000
debris_type = debris_small_ship
dmg_hp = DpPort_Engine
dmg_obj = rh_freighter_dmg_portengine_cap
separation_explosion = explosion_small_ship_breakoff
mass = 5.000000
type = Port_Engine
{{ rfr.eng1 }}

[CollisionGroup]
obj = starboard_engine_lod1
separable = true
parent_impulse = 250.000000
child_impulse = 7.000000
debris_type = debris_small_ship
dmg_hp = DpStarBoard_engine
dmg_obj = rh_freighter_dmg_starengine_cap
separation_explosion = explosion_small_ship_breakoff
mass = 5.000000
type = StarBoard_Engine
{{ rfr.eng2 }}
