FACTION_RH = 1
FACTION_LI = 2
FACTION_BR = 3
FACTION_KU = 4
FACTION_CO = 5

# GUNS

LIGHTGUN = 'light'
HEAVYGUN = 'heavy'
CIVGUN = 'civilian'
PIRATEGUN = 'pirate'
HUNTERGUN = 'hunter'
SHIELDGUN = 'shield'

WEAPON_RH = 'rh'
WEAPON_LI = 'li'
WEAPON_BR = 'br'
WEAPON_KU = 'ku'
WEAPON_BW = 'bw'

# MISC EQUIP TYPES

RH_MAIN = 1
RH_CIV = 2
RH_PIRATE = 3

LI_MAIN = 4
LI_CIV = 5
LI_PIRATE = 6

BR_MAIN = 7
BR_CIV = 8
BR_PIRATE = 9

KU_MAIN = 10
KU_CIV = 11
KU_PIRATE = 12

CO_ORDER = 13
CO_CORSAIR = 14
CO_OUTCAST = 15

# COMMODITY

TERRAFORM_MINERALS = 'terraform_minerals'
TERRAFORM_GASES = 'terraform_gases'
LASER_BEAM_PARS = 'laserbeam_parts'

BASIC_WATER = 'water'
BASIC_OXYGEN = 'oxygen'
BASIC_FOOD = 'food'
BASIC_CONSUMER = 'consumer'
BASIC_MEDS = 'meds'
BASIC_WEAPONS = 'weapons'
BASIC_TOXIC = 'toxic'

METAL = 'metal'
POWER_SOLAR_EMPTY = 'power_solar_empty'
POWER_SOLAR = 'power_solar'
ALLOY_BASIC = 'alloy'
GAS_BALLOONS = 'gas_balloons'
WATER_EXTRA = 'water_extra'
GAS_FUEL = 'gas_fuel'

DIAMONDS = 'diamonds'
LUXURY_DIAMONDS = 'luxury_diamonds'
NIOBIUM = 'niobium'
PROD_MACHINES = 'prod_machines'
STATION_PANELS = 'station_panels'
ALLOY_HEAVY = 'alloy_heavy'
ROID_MINER_PARTS = 'roid_miner_parts'
SMELTER_PARTS = 'smelter_parts'
SHIP_HULL_PANELS = 'ship_hull_panels'

BERILIUM = 'berilium'
NICOLLUM = 'nicollum'
LUXURY_GOODS = 'luxury_goods'
TLR_PARTS = 'tlr_parts'
ENGINE_PARTS = 'engine_parts'
JUMPGATE_PARTS = 'jumpgate_parts'
ALLOY_TEMPERATURE = 'alloy_temperature'
MINING_EQUIPMENT = 'mining_equipment'
POLYMERS = 'polymers'

URANIUM = 'uranium'
PLUMBUM = 'plumbum'
REACTORS = 'reactors'
MOX_FUEL = 'mox_fuel'
AMMUNITION = 'ammunition'
LUXURY_FOOD = 'luxury_food'
ALLOY_RADIATION = 'alloy_radiation'
GREENHOUSE_PARTS = 'greenhouse_parts'
DEFENCE_SYSTEMS = 'defence_systems'

GOLD = 'gold'
SILVER = 'silver'
ELECTRONICS = 'electronics'
LUXURY_GOLD = 'luxury_gold'
OPTICAL_CHIPS = 'optical_chips'
ALLOY_CONDUCTOR = 'alloy_conductor'
GAS_MINER_PARTS = 'gas_miner_parts'
SOLAR_PLANT_PARTS = 'solar_plant_parts'
RESEARCH_EQUIP = 'research_equip'

PRODUCT_RELATIONS = {
    LUXURY_DIAMONDS: [DIAMONDS, PROD_MACHINES],
    PROD_MACHINES: [DIAMONDS],
    STATION_PANELS: [ALLOY_HEAVY],
    ROID_MINER_PARTS: [ALLOY_HEAVY, PROD_MACHINES],
    SMELTER_PARTS: [ALLOY_HEAVY, ALLOY_TEMPERATURE, PROD_MACHINES],

    LUXURY_GOODS: [POLYMERS],
    TLR_PARTS: [ALLOY_TEMPERATURE, PROD_MACHINES],
    ENGINE_PARTS: [ALLOY_TEMPERATURE, ALLOY_RADIATION, PROD_MACHINES],
    JUMPGATE_PARTS: [ALLOY_TEMPERATURE, PROD_MACHINES],
    MINING_EQUIPMENT: [ALLOY_HEAVY, PROD_MACHINES],

    REACTORS: [ALLOY_RADIATION, PROD_MACHINES],
    AMMUNITION: [ALLOY_TEMPERATURE, ALLOY_RADIATION, PROD_MACHINES],
    LUXURY_FOOD: [TERRAFORM_MINERALS],
    GREENHOUSE_PARTS: [POLYMERS, TERRAFORM_MINERALS],
    DEFENCE_SYSTEMS: [ELECTRONICS, OPTICAL_CHIPS, POLYMERS],

    ELECTRONICS: [GOLD, SILVER, ALLOY_CONDUCTOR, PROD_MACHINES, POLYMERS],
    LUXURY_GOLD: [GOLD, SILVER],
    OPTICAL_CHIPS: [PROD_MACHINES, ALLOY_CONDUCTOR, PROD_MACHINES],
    GAS_MINER_PARTS: [ALLOY_HEAVY, PROD_MACHINES],
    SOLAR_PLANT_PARTS: [ALLOY_CONDUCTOR, PROD_MACHINES],
    RESEARCH_EQUIP: [OPTICAL_CHIPS, ELECTRONICS, PROD_MACHINES],
}
