RH_SHIP = '''Rheinland ships have the lowest mass due to a reduced cargo hold'''
LI_SHIP = '''Liberty ships possess excellent maneuverability, but at the cost of having the weakest armor'''
BR_SHIP = '''Bretonian ships have the most durable hull due to low maneuverability'''
KU_SHIP = '''Kusari ships have additional nanobot and shield battery capacity at the expense of reduced strafe speed'''
BW_SHIP = '''Border Worlds ships have a significantly increased cargo hold volume, but can store fewer nanobots and shield batteries'''

GF1 = '''The Starflier is the simplest of the available ships. Nimble and agile, it is capable of getting out of the most difficult situations in the hands of an experienced pilot. And it can help out a poor pilot when there's no money for something more worthy.'''
GF2 = '''This ship has proven itself as the best tool for civilian pilots. Simple, light, unpretentious. It can be an excellent support ship when convoying civilian transports.'''
GF3 = '''The Starblazer is the most advanced ship in the civilian series. With the help of an additional engine and stabilizers, it can match the characteristics of the best heavy fighters.'''

GF4 = '''The light fighter "Hawk" is the base ship of the civilian series version 2. Although slightly less maneuverable, it is capable of performing more complex tasks than other analogues of civilian light fighters, which has earned it a reputation among both Kusari mercenaries and pirates.'''
GF5 = '''Efficient and maneuverable, the "Falcon" is considered one of the best civilian-type heavy fighters. Its characteristics are highly rated by the Black Dragon mercenaries, allowing it to capture a large share of the Kusari heavy fighter market.'''
GF6 = '''The "Eagle" is one of the best heavy fighters in its class. It not only possesses excellent firepower, hull, and characteristics, but also retains the agility and lightness characteristic of light fighters in its class. With the "Eagle", you can complete any task, not only in the calm worlds of Kusari but also in the nearby borderlands.'''

BW_FR = '''Simple and unpretentious, the "Dromedary" allows one to get a true cargo monster for quite a reasonable price, capable of delivering a huge amount of cargo and giving its owner a chance to earn their first capital. But it is good not only in trade - in battle, it will fight back any bandits who stand in its owner's way.'''

BW_F = '''The "X" series light fighter is a characteristic example of Rheinland engineering. It is not only light and maneuverable, but also lighter than its competitors, although it pays for this with a smaller cargo hold volume. Nevertheless, with its greater agility, it can become a formidable opponent to enemy raiders and has also proven itself well in the service of Rheinland mercenaries.'''
BW_E = '''The "Stiletto" is the most popular Rheinland fighter. The "X" series heavy fighter boasts excellent combat power and defensive characteristics, which has earned it a good reputation within the PMC "Asgard". These capabilities are appreciated not only by legal organizations. The "Stiletto" is lighter than its counterparts, although it carries less cargo. This makes it a less effective trader but a more effective combatant.'''
BW_E2 = '''The best representative of the "X" series, the "Sabre" is an unsurpassed heavy fighter with the lowest mass. Although it pays for this with a smaller cargo hold, its firepower and combat capabilities make it an indispensable representative of border worlds ships.'''

BH_F = '''Small and light, the "Piranha" is considered a very dangerous light fighter. Capable of sharp turns and sudden attacks, it is actively used by the PMC "Shield" as a standard means of escort and patrol within Liberty territory. But other organizations are also happy to use the "Piranha", giving due credit to its convenience and low maintenance.'''
BH_E = '''A very popular ship on the Liberty market, the "Barracuda" is considered a formidable opponent, as it not only has excellent combat power but also retains excellent maneuverability. The "Barracuda" can be used to maintain order in Liberty's border territories, but it is also often used by pirates. The "Barracuda" is especially popular with the "Starline" gang, which is trying by all means to buy up a significant batch of the ship, which greatly affects its availability in stores.'''
BH_E2 = '''The "Hammerhead" is one of the most powerful and maneuverable ships available, both in Liberty and Sirius. The ship uses its characteristics for attacks and evasions in such a way that the opponent has the least opportunity to fight back against such a formidable foe. With the "Hammer", you can not only conduct surveillance in the most dangerous corners of Liberty but also literally dominate in the remote corners of the outer worlds and borderlands.'''

EX_CO_F = '''The "Legionnaire" is a sturdy and capable ship among organizations operating in Bretonia. Its most important features are durability and moderate maneuverability. The "Legionnaire" can withstand more damage, which can put an opponent in a very awkward position. The ship has proven itself both in civilian service and with separatists. Counterfeit copies are available on the market, but they are impossible to distinguish from the original, as Irish engineers have tried to preserve all the best characteristics of this machine.'''
EX_CO_E = '''The PMC "Royal Force" uses the "Centurion" for most operations in Bretonia, giving this ship huge publicity. It is not without reason that it has a reputation as the most dangerous of Bretonian ships, as it boasts a very durable hull, although it is less maneuverable than its counterparts. Nevertheless, such fame has allowed the ship to become popular not only in legal circles but also among pirates.'''
EX_CO_E2 = '''The "Titan" is considered one of the most durable ships in Sirius. Thanks to a unique recombination system, it can remain compact on the longest flights and is also low-maintenance, as engineers can easily access the most vulnerable and damage-prone parts of the ship. This allows the ship's hull to be kept as strong as possible in any situation. However, this system, although very innovative, still significantly reduces the ship's maneuverability. And yet, this still makes the "Titan" the most popular and effective ship both locally in Bretonia and in any border territory.'''

RH_F = '''Designed for a doctrine of expansion and dominance, the "Banshee" is one of the most dangerous light fighters. Although not as maneuverable, its low mass allows it to achieve maximum speed very quickly, especially when combining acceleration with reverse thrust. The "Banshee's" cargo hold is smaller than that of other fighters, but this does not prevent it from being successful in most possible scenarios.'''
RH_E = '''A masterpiece of Rheinland military industry, the "Valkyrie" is considered a symbol of the Kaiser's military might. Thanks to reduced mass, this ship is capable of any conceivable aggressive operation. It brakes easily, accelerates easily, changes direction easily, attacks, and dominates, as required by Rheinland military doctrine. At the same time, the "Valkyrie" has a smaller cargo hold, but this is not a particular problem, as its main task is destruction; let civilians who follow deal with trade.'''
RH_FR = '''The "Humpback" rightfully has an excellent reputation as Rheinland's workhorse. Although it has a smaller cargo hold, it accelerates faster than other freighters. This gives it a not too great, but still very positive advantage in combat.'''

LI_F = '''The light "Patriot" is not without reason considered one of the most compact fighters. One of the best maneuverability rates on the market, along with excellent firepower, will not allow the enemy to catch up with it before the "Patriot" itself deals with the adversary.'''
LI_E = '''The pride of Liberty shipbuilders, the "Defender" is the fastest and most maneuverable heavy fighter available. With its capabilities, it can eliminate any enemy of freedom and justice and maintain order both within Liberty territory and in its satellite territories.'''
LI_FR = '''No state can manage without a reliable freighter. The "Rhino" can transport huge amounts of cargo, while being maneuverable enough for its class and quite capable of fighting back even the most aggressive opponents. This allows one to be calm not only for one's life but also for the delivery of the cargo.'''
LI_E2 = '''The "Ranger" is a modified officer version of the "Defender". It significantly expands the capabilities of the original, allowing for the elimination of a wider range of Liberty's enemies, not only within the home territories but also beyond them, in the distant frontier.'''

BR_F = '''A light fighter guarding Her Majesty Queen Carina, the "Cavalier" is considered one of the most durable light fighters. This negatively affects its maneuverability characteristics but does not change the overall situation. In the "Cavalier", you can emerge victorious from the most difficult situations. This makes it an important combat unit of the Bretonian fleet.'''
BR_E = '''The "Crusader" is considered one of the most durable ships in the Sirius sector. Its hull can withstand a huge amount of damage. Although it pays for this with lower maneuverability, it is capable of solving a huge range of combat tasks in the name of Her Majesty, the Queen of Bretonia.'''
BR_FR = '''One of the most durable freighters, the "Clydesdale", possesses sufficiently acceptable maneuverability. This ship will allow you to fly through the most dangerous zones of the Sirius sector, while delivering both its crew and cargo safe and sound.'''

KU_F = '''The light fighter "Drake" rightfully holds the status of one of the most maneuverable ships. Fast, capable of accelerating easily, it can deliver the sharpest and most dangerous blows to its opponents. It is one of the best support ships. This keeps the borders of Kusari under reliable protection from the provocations of any adversary. However, it has some problems with lateral movement, which is compensated for by a huge number of nanobots.'''
KU_E = '''The "Dragon" is the main military force of the Kusari Shogunate. It is a very powerful fighter, capable of the boldest and most dangerous operations. And in case of unforeseen situations, the "Dragon" possesses a huge number of nanobots and shield batteries, compensating for some of its problems with lateral engine speed. Nevertheless, the "Dragon" is the most important element of the military might of both the Shogun and Kusari as a whole.'''
KU_FR = '''Bulky and clumsy, the "Drone" is considered a quite good freighter, as, possessing all relevant characteristics, it is also capable of carrying a huge number of nanobots and shield batteries in case of unforeseen situations, which the Sirius sector is full of. In this case, its only problem is a lack of lateral speed, which, given its level of maneuverability, is not a particular issue.'''

CO_F = '''Dangerous and swift, the "Bloodhound" is the most dangerous and aggressive representative of Corsair ships. Although formally a light fighter, the ship has not only excellent firepower but also a huge cargo hold, allowing it to gain the greatest benefits from offensive operations. It pays for this with a reduced number of nanobots, which is not so important. A good raid should be fast and efficient.'''
CO_E = '''The heavy "Wolfhound" is one of the most dangerous and bloodthirsty representatives of Sirius. This marvel of technology is specifically designed for aggressive raids, so although it has a shortage of nanobots, it boasts a simply enormous cargo hold, making any of its attacks maximally effective. This beast has come for real prey and does not intend to scavenge for scraps, so it will try to carry away all the enemy's cargo with it.'''
CO_FR = '''The "Mule" is a rather controversial freighter with admirable potential. First, note that it has the largest cargo hold among freighters in the Sirius sector. But at the same time, any flight of the "Mule" is best conducted in a safe zone, as it has a significant shortage of nanobots. Nevertheless, the risk is usually worth it. Therefore, although the "Mule" suits risk-takers, this risk is usually always justified.'''

OR_E = '''Anibus is the main Order fighter.'''

CSV = '''The abbreviation CSV stands for "Combat Support Vessel". This makes the CSV one of the most effective freighters, as it is specifically designed for engineering tasks in the heat of the most serious battles. But at the same time, the ship is equipped with a special manipulator that allows it not only to deal additional damage to shields but also to most efficiently harvest gas from dense gas clouds. Use the CSV if you want the most versatile engineering ship in the Sirius sector.'''
AT = '''The Armored Transport is the most protected way to transport cargo, goods, and passengers in the Sirius sector. However, it is not invulnerable. For this reason, big shots prefer to fly on something larger, like a cruiser or even a battleship. But for ordinary citizens, it is the safest way to travel or deliver.'''
CRUISER = '''The Cruiser is the most mobile means of demonstrating state power in this system. The cruiser's unparalleled firepower allows it to effectively protect critical house assets from pirate attacks, as well as encroachments from other houses, which sometimes also become hostile.'''
GUNBOAT = '''The Gunboat is a light, gun-laden means of engaging the enemy. Gunboats are usually used against other cruisers, destroyers, and even stations. They are not as protected as other heavy ships but still allow for inflicting high damage on insufficiently maneuverable enemy ships.'''
TRANSPORT = '''Container shipping is the most efficient way to deliver goods in the Sirius sector. Transports are usually tied to specific systems and routes to simplify repair and logistics. Usually, transports arrive at docks awaiting loading and, after receiving the goods, depart back to their home port so that upon return, they receive the necessary servicing and are ready for future runs.'''
TRAIN = '''Heavy trains are used to deliver huge amounts of cargo throughout Sirius territory. Using a system of wagon couplings, they can easily leave their cargo at the dock and immediately proceed to the next task. Specifically for this, trains have several crews on board to ensure almost round-the-clock use of their capabilities. Usually, trains are assigned to a certain territory and try not to fly beyond their area of responsibility. Upon reaching the final station, the train will prefer to load up with cargo that needs to be returned to the point of its previous departure. This way, it can reach the servicing facilities to which it is assigned.'''
BATTLESHIP = ''''''
DESTROYER = '''Destroyers are designed to eliminate '''
