from text.strings import MultiString as MS

ASTERISK = '*'  # MANDATORY to show up in history
RU_ROOT = f'{ASTERISK}ЛИЧНАЯ ЗАПИСЬ:'
EN_ROOT = f'{ASTERISK}PERSONAL ENTRY:'


class HistRecord:
    def __init__(self, index, ru, en):
        self.index = index
        self.ru = ru
        self.en = en


class HistoryItem:
    def __init__(self, ids, record):
        self.ids = ids
        self.record = record
        self.name = self.ids.new_name(MS(
            f'{RU_ROOT}\\n{self.record.ru}',
            f'{EN_ROOT}\\n{self.record.en}',
        ))

    def show(self):
        return f'Act_NNIds = {self.name}, HISTORY'


HistRecord(index="h001", ru="Русский текст", en='English text'),


history_records = [
    HistRecord(index="h001",
               ru="Время заводить дневник! Это модная тема для фрилансеров. В космосе опасно, твой корабль могут взорвать. А чтобы хоть какая-то осталась память, рядом с черным ящиком останется твой дневник, который можно будет почитать. Попробуем что-нибудь тут написать. Как раз повод изменить жизнь, ведь я сейчас уже в ожидании посадки на транспортное судно.",
               en="Time to start a log! It's the trendy thing among freelancers. Space is dangerous, your ship can get blown to bits. At least with a personal log, something remains. It'll stay right next to the black box for someone to read. Let's try writing something. A good excuse to turn my life around, especially since I'm currently awaiting docking with a transport ship."),

    HistRecord("h002",
               ru="Возможно, у дневника должна быть своя предыстория. Честно говоря, у меня такое ощущение, что я живу в какой-то параллельной реальности. Вот работаешь ишачишь. Смотришь на имена, людей и думаешь, а вдруг в другой реальности это было немного другим... Вот зовут меня Эдисон Трент. Взбрело в голову моей мамаше, которую я ни разу не видел, взять и назвать в честь старого героя неизвестной войны. Долгое время мы считали её сказками, что вот мол 50 лет назад жил да был Эдисон Трент, у него была подружка Джуни, а их прикрывал Кинг. И вот кому-то в тех местах, где я родился, взбрело в голову подумать «а ведь похож на того героя, которого на картинках показывали». И назвал один в один. Теперь только и делают, что сбиваются. Так уж получилось, что сходство действительно есть. Поэтому теперь меня постоянно путают и перепроверяют, а то ли я самый персонаж. И грустно сказать, что нет. Не он. Хотелось бы? Конечно!",
               en="Maybe this log needs some backstory. Honestly, I feel like I'm living in some alternate reality. You work your tail off. You look at names, faces, and wonder if in another reality things were slightly different... Take me, Edison Trent. My mother, whom I've never seen, got it into her head to name me after some old hero from a forgotten war. For the longest time, we thought those were just tall tales—that fifty years ago there lived an Edison Trent, he had a partner named Juni, and they were backed by a man called King. Then someone back where I was born took one look and thought, 'Hey, he kinda looks like that hero from the holos.' And they named me exactly the same. Now it's all anyone talks about. Turns out, the resemblance is real. So I get constant double-takes and security checks—'Are you *the* guy?' Sadly, no. I'm not him. Would I want to be? Hell yes!"),

    HistRecord("h003",
               ru="Это не первая моя попытка уйти во фриланс. В тех местах, где я бывал, почти все уходили с фрилансерами. Мы с моим другом Алариком сразу пошли в лётную школу, но его карьера пошла лучше. Летали мы вроде неплохо, но мне не повезло, я потерял груз и попал на деньги. Осел на Калифорнии и стал искать как выплатить долги. Последнее время только и делал, что пахал на местного бармена. У него есть простенькие заказы, платил мало, но стабильно. Вот теперь я точно выплатил долг и можно пробовать начинать карьеру заново. Как раз снова вышел на связь Аларик. Говорит, есть у него интересное дело. В этом я не сомневаюсь, что он же тот еще любитель поработать на всякие спецслужбы. Но в этот раз дело должно быть не пыльненьким, ведь он обещал мне корабль. Да, простой. Но зато будет на чём полетать.",
               en="This isn't my first shot at going freelance. Where I come from, almost everyone ends up with the freelancers eventually. My friend Alaric and I went straight to flight school, but his career took off faster. We were decent pilots, but I got unlucky—lost a cargo run and wound up in debt. Got stuck on California, scrambling to pay it off. Lately, I've just been grinding odd jobs for the local barkeep. Simple runs, low pay, but steady. Now the debt's finally cleared, and I can try starting over. And just like that, Alaric gets back in touch. Says he's got an interesting job. No surprise there—he's always had a taste for working with... let's say, 'special interests.' But this time it should be worthwhile; he promised me a ship. An old one, sure. But at least it's something to fly."),

    HistRecord("h004",
               ru="Чартерные перевозки — это то еще удовольствие. Рядом сидели непонятные вонючие ребята. Болтали про какие-то мутные дела. Надеюсь, что они просто контрабандисты, а не какие-нибудь подельники из банды Дикси. Вроде бы всё обошлось. Нас не перехватили пираты. Даже полиция не досматривала.",
               en="Charter flights are a real joy. Had some shady, smelly characters sitting next to me. Chatting about some dubious business. Hopefully, they're just smugglers and not some Dixie Gang associates. Seems we got through clean, though. No pirate interdiction. Not even a police scan."),

    HistRecord("h100",
               ru="Магдебург, ну и дыра. И как тут люди живут. К счастью, я тут ненадолго. Аларик обещал ждать меня в местном баре. Посмотрим, что за работу он мне предложит.",
               en="Magdeburg. What a hole. How do people even live here? Thankfully, I'm not staying long. Alaric said he'd meet me at the local bar. Let's see what kind of job he's got lined up."),

    HistRecord("h101",
               ru="Сегодня Аларик подозрительно щедрый. Он мне вручил свой старый пепелац, о котором он давно рассказывал. На этом корыте когда-то катался его дядя. Он называл корабль «Гран Торино», даже не знаю почему. По тем временам это была та еще рухлядь, сейчас тем более. Но двигатель и генератор вроде работают. Летать сможет. Еще посмотрю, может стоит чего сразу заменить. Может там поставить более мощный форсаж для начала, что компенсировать слабую мощность движка. Если этот раритет долетит до Берлина, то я буду большим везунчиком.",
               en="Alaric's being suspiciously generous today. He handed over that old rustbucket he's always talked about. His uncle used to fly this thing. He called it the 'Gran Torino'—no idea why. Even back in its day it was a heap, and now... well. But the engine and generator seem functional. She'll fly. I'll check if anything needs replacing right off the bat. Maybe a more powerful thruster to compensate for the weak engine. If this relic makes it to Berlin, I'll count myself damn lucky."),

    HistRecord("h102",
               ru="Сигма-13. Полёт нормальный. Пиратов нет, трейдлейны работают, гиперврата активируются. А вот на влёте в Берлин что-то пошло не так. Тут происходит какая-то контртеррористическая операция, всех осматривают, изучают. Я то чистый, но всё равно не комфортно. А вдруг чего-нибудь мне лишнего припишут и потом доказывай, что ты не дромадер со станции гималайской.",
               en="Sigma-13. Flight's normal. No pirates, trade lanes humming, jump gates activating. But the approach to Berlin... something's off. There's some counter-terrorist op going on. Everyone's being scanned, scrutinized. I'm clean, but it's still unsettling. What if they pin something on me? Try proving you're not a Himalaya Station Dromedary after that."),

    HistRecord("h103",
               ru="А вот и те самые террористы! Агрессивные ребята. Зачем-то разнесли целый крейсер. При том управляет террористами какой-то местный товарищ. Вот интересно, зачем ему устраивать этот балаган? У крейсера ведь точно был экипаж из местных военных. Если хочет выбить себе какое-то особое звание, то спасибо ему потом не скажут. Видимо у него совсем далеко идущие планы.",
               en="And there are the terrorists! Aggressive bunch. For some reason, they blew a whole cruiser to pieces. And they're led by some local hotshot. I wonder what his angle is? That cruiser had a full military crew. If he's trying to earn himself a fancy promotion, 'thank you' isn't what he'll be getting. His plans must run deeper."),

    HistRecord("h104",
               ru="Нашли мы этих двух чубриков, которых надо конвоировать до Бисмарка. На вид неплохие ребята. Обычные такие торговцы. Старший из них как будто заикается, но совсем незаметно. По самому Берлину погулять особо не успел. Огромная промышленная планета. Надо запомнить цены, может потом будет смысл закупиться тут чем-нибудь промышленным, чтобы потом где-нибудь перепродать.",
               en="Found the two guys we're supposed to escort to Bismarck. Seem decent enough. Regular traders. The older one seems to have a slight stutter, but it's barely noticeable. Didn't get to see much of Berlin itself. Huge industrial planet. Should remember the prices here—might be worth buying some industrial gear to flip elsewhere later."),

    HistRecord("h105",
               ru="Поговорили мы тут с нашими конвоируемыми про террориста Дитриха и всё равно ничего не поняли. Какой-то больно агрессивный он для оппозиционера. Но если уж меня попросили не лезть в местную политику, то и не буду. Меня больше волнует, что до такой достаточно внутренней локации спокойно долетают корсары. Не к добру это.",
               en="We chatted with our charges about the terrorist, Dietrich, and I'm none the wiser. He seems awfully aggressive for an 'opposition figure.' But they asked me to stay out of local politics, so I will. What bothers me more is that Corsairs are operating this deep in core space. That's a bad sign."),

    HistRecord("h106",
               ru="Наши конвоируемые ребята совсем чёкнутые. Мы говорим – полетели по торговому пути. Это безопасно или хотя бы помощь быстро вызовем. А они полетели в астероиды! Или они сильно молчат про груз, который везут. Или точно знают, что их на дороге к Штарке кто-то ждёт. Самое забавное, что их ждали и у астероидов. Заварушка вышла не хилая, а аванпост был очень далеко. Но вроде отбились, хоть мне и казалось, что стоит мне поперхнуться, как генератор корабля сгорит окончательно. Но вроде выдержал. Летим дальше.",
               en="Our charges are completely nuts. We say, 'Let's take the trade lane. It's safe, or at least we can call for help fast.' They head straight into the asteroid field! Either they're dead silent about their cargo, or they know someone's waiting for them on the way to Stark. The funny part is, someone *was* waiting in the asteroids. It got pretty hot out there, and the outpost was way too far. But we held them off, even though I thought my ship's generator would give out any second. It held. Onwards."),

    HistRecord("h107",
               ru="Аларик мне написал текстом, что зря я предложил отправить Луца за подмогой в полицию. Но я с Алариком не согласен. С виду корабль Луца гораздо лучше моего, но летать Луц не умеет совсем. Я больше боялся, что он или протаранит кого-нибудь, или его просто сожгут быстрее, чем меня. Аделмар то ладно, у него броня. Но вроде самое сложно осталось позади. Надеюсь. Дальше полиция должна быть на каждом шагу, никто больше не посмеет напасть среди бела дня. Если только снова не появятся друганы того террориста.",
               en="Alaric texted me, said it was a mistake to send Lutz to the police for backup. I disagree. Lutz's ship looks better than mine, but the guy can't fly for crap. I was more afraid he'd ram someone or get blown up faster than me. Adelmar's fine—he's got armor. But the worst seems behind us. Hopefully. From here on, police should be everywhere. No one's dumb enough to attack in broad daylight. Unless that terrorist's buddies show up again."),

    HistRecord("h108",
               ru="Конвой доставлен, поболтали с народом в баре Бисмарка. Заплатили в целом неплохо. Всё-таки интересно, а что же у них был за груз. Луцу только не понравился мой корабль. Летать бы сначала научился на своём! И критикует ещё. Но я с Алариком соглашусь, что моё корыто тоже ни на что не способно. Главное только не забыть, что я могу улучшать элементы корабля прямо сейчас. Генератор может и слабый, но можно поставить посильнее. Как и щит. Надо пробовать. Только главное всегда помнить, что важнее всего в корабле генератор. Если поставлю крутой двигатель или щит со слабым генератором, то далеко улететь со всеми этим счастьем я не смогу. Так что надо быть аккуратном в выборе оборудования. Но вроде бы мне повыпадало несколько устройств с пиратов. Может среди этого есть что-нибудь, что я могу поставить себе. Надо лишь будет только эту оборудку отремонтировать.",
               en="Convoy delivered. Had a chat with folks at the Bismarck bar. Pay was decent, all things considered. Still wonder what their cargo was. Lutz didn't like my ship, though. He should learn to fly his own first! And he's criticizing? I agree with Alaric—my bucket isn't much either. Key thing is to remember I can upgrade ship components now. The generator's weak, but I can install a better one. Same with the shield. Gotta try. But always remember, the generator is the heart of the ship. If I slap on a fancy engine or shield with a weak generator, I won't get far with all that 'happiness.' So I need to be smart about gear. I did loot a few bits from those pirates. Maybe there's something usable in there. Just need to repair it first."),

    HistRecord("h200",
               ru="Лечу себе спокойно лечу. И прилетает какое-то непонятное текстовое сообщение от странного челика по имени Вильгельм. Зовёт, чтобы предложить задание на рейнландском линкоре. Видимо военный. А военные платят хорошо.",
               en="Flying along, minding my own business, when I get a strange text from a guy named Wilhelm. Wants to offer a job on a Rheinland battleship. Military, then. And the military pays well."),

    HistRecord("h201",
               ru="Этот Вильгельм какой-то кудесник. Плетёт интриги, стёр сообщение с моего КПК. А вот задание вроде простое. Нужно что-то где-то найти и принести Вильгельму обратно. Есть информатор, который знает, что и где искать. Моя задача просто не светиться рейнландскими погонами. Вроде ничего сложного.",
               en="This Wilhelm is some kind of spook. Plays games, erased the message from my PDA. The job seems straightforward, though. Find something, somewhere, and bring it back to Wilhelm. There's an informant who knows what and where. My job is just to keep a low profile—no Rheinland insignia. Shouldn't be too hard."),

    HistRecord("h202",
               ru="Шахтерская община. Сегодня побудем рудокопом. Вечно на таких базах требуется что-то да открыть. Пока не добудешь платиновый кусок астероида, тебе посадку не выдадут. Дело то не трудное. Разбиваем кусок астероида. Если мой интерфейс отметит, что этот астероид верный, то бьем до конца, пока не найдем нужный платиновый кусок. И тогда можно сразу садиться на рудодобывающее судно. Всё еще не понимаю, зачем это они делают. Хотят видимо сделать тебе испытание, проверку на вшивость. Чтобы все подряд не заходили. И так в каждой общине. Что с газодобытчиками, что у переработчиков мусора. Всё одно и тоже. Интересней только со взломом. Там надо вскрыть местную панель, активировав блоки нужного цвета. Самое лёгкое по мне — это найти ключик на обломках в минном поле. Мало кто знает, что ключик отмечается в интерфейсе. Сканируй объекты на дальнем расстоянии, перебирай объекты с помощью кнопки Т, находи истребитель с синим элементиком, лети к нему, а потом забрав ключ садись на местную базу. Я слышал, что совсем отчаянные фрилансеры перебирали все корабли руками. В новостях рассказывали, что банда чёрных копателей подорвалась на минах во время раскопок. Помянем отчаянных искателей приключений.",
               en="Mining community. Playing asteroid cracker today. These outposts always make you jump through hoops. Won't let you dock until you fetch a platinum chunk. Simple enough. Blast an asteroid apart. If my HUD marks it as the right one, keep hitting it till the platinum core pops out. Then you can dock with the mining barge. Still don't get why they do this. Probably a test, a 'prove you're not a complete idiot' check. Keeps the riff-raff out. Same story with every community—gas miners, scrap processors. All the same. The hacking gigs are more interesting. You crack a local panel by activating the right colored blocks. Easiest one, in my book, is finding a key in a wreck within a minefield. Few know the key shows up on your HUD. Long-range scan, cycle targets with 'T', find the fighter with a blue component, fly to it, grab the key, then dock at the local base. I've heard of desperate freelancers manually checking every wreck. News said a band of black diggers got blown up by mines during their 'excavation.' Here's to the daring adventurers."),

    HistRecord("h203",
               ru="Типичный хиккан программист с ноутбуком. Вот это и есть наш Джакобо. Но вроде он действительно информатор и имя Вильгельма на него повлияло. Так что быстро собрал монатки и отправился показывать мне нужные обломки истребителей. Вылетаем.",
               en="Typical hacker type with a laptop. That's our Jacobo. But he seems like a genuine informant, and Wilhelm's name got his attention. He packed his gear fast and is leading me to the right fighter wrecks. Let's move."),

    HistRecord("h204",
               ru="Я сначала не сильно обратил внимание на фразу Джакобо, что мол Вильгельм любит сидеть далеко и отдавать другим грязную работу. А работа была очень грязной! Прямо засаленной в машинной смазке, потому что нас там встретили Мусорщики! Их было много. Прям очень много. Но я всех успешно раскидал. Нужный корабль мы нашли, так что снял с него чёрный ящик и везу к Вильгельму. Джакобо, кстати, попросил сохранить мой контакт, чтобы предложить какую-нибудь работу в будущем. Звучит перспективно. Вот так и работают социальные связи!",
               en="Didn't pay much mind to Jacobo's comment about Wilhelm liking to sit far away and let others do the dirty work. The work was *filthy*! Greased up with engine sludge, because we were met by Scavengers! A whole lot of them. But I scattered them all. Found the right ship, pulled its black box, and now I'm hauling it to Wilhelm. Jacobo, by the way, asked to keep my contact for future jobs. Sounds promising. That's how you network!"),

    HistRecord("h205",
               ru="При встрече Вильгельм был во все оружии. Целый отряд рейнландских военных кораблей, готовых к военной операции. И они приготовились не зря, ведь с моего чёрного ящика они даже что-то нашли. Вильгельм предложил мне поучаствовать. Я уже было сомневался... Но... Социальные связи же. Если сейчас помогу, то завтра получу вдвойне. Так что решил полететь. Посмотрим, как ведут себя рейнландцы в действии.",
               en="Wilhelm was armed to the teeth when we met. A full Rheinland military squadron, prepped for combat. And for good reason—they found something on that black box. Wilhelm offered me a spot in the op. I hesitated... But... Networking, right? Help now, get paid double later. So I'm in. Let's see the Rheinlanders in action."),

    HistRecord("h206",
               ru="Мы устроили облаву на какие-то склады. Куча корсаров, все разлетелись в рассыпную. Мы перехватили самых мелких, а вот грузовик смылся. Казалось бы, вот и косяк. Но Вильгельм не дурак, он отправил разведчика за грузовиком. Разведчик успешно преследовал его и по итогу нашел какую-то базу. Да, прям так рейнландский боец и закричал «база, вижу базу». Мы толпой отправились на помощь нашему разведчику.",
               en="We raided some storage depots. A bunch of Corsairs, they scattered like roaches. We picked off the small fry, but a big hauler got away. Seems like a screw-up. But Wilhelm's no fool; he sent a scout after the hauler. The scout tailed it successfully and found a base. Yeah, just like that, a Rheinland trooper yells, 'Base! I see a base!' We all piled in to back him up."),

    HistRecord("h207",
               ru="У корсаров тут действительно приличная база. Окружена орудийными платформами, я получил задачу нейтрализовать их. Врагов было много, платформы плотные и с мощными турелями. Но вроде отбились. Следом люди Вильгельма выпустили торпеды и раскатали эту базу к чёртовой матери. Теперь корсары в ближайшее время не побеспокоят людей в этой системе. Казалось бы, моя миссия выполнена, но Вильгельм попросил меня отправиться обратно на Шарнхорст. Не вижу причину отказываться в таком предложении.",
               en="The Corsairs have a solid base here. Ringed with gun platforms, and my job was to take them out. Plenty of enemies, dense platforms with heavy turrets. But we held. Then Wilhelm's boys launched torpedoes and turned that base into cosmic dust. Corsairs won't be bothering folks in this system anytime soon. Mission accomplished, you'd think. But Wilhelm asked me to head back to Scharnhorst. Don't see a reason to say no."),

    HistRecord("h208",
               ru="На Шарнхорсте нас встретил целый рейнландский адмирал Райхман. Очень важная шишка. Лысый и с прикрепленной нейросетью. Видимо в прямом эфире раздает приказы своему адмиралтейству. Он был очень любезен, а под конец вообще сказал Вильгельму удвоить мой гонорар. Какая же душка этот адмирал! Социальные связи работают. Если так дело пойдёт, то скоро буду не простым рейнландским фрилансером, а целым генералом фельдмаршалом. А почему бы и да! Кто тут в фельдмаршалы крайний? Никого? Так я первый буду!",
               en="On Scharnhorst, we were greeted by a full Rheinland Admiral—Reichmann. A real bigwig. Bald, with a neural interface grafted on. Probably issuing orders to his admiralty in real-time. He was very gracious, and at the end, he even told Wilhelm to double my pay. What a sweetheart! Networking pays off. At this rate, I won't just be a Rheinland freelancer; I'll be a General Field Marshal! Why not? Who's last in line for Field Marshal? Nobody? Then I'll be first!"),

    HistRecord("h300",
               ru="Вильгельм снова вышел на связь. Предлагает миссию, но теперь в необычном месте. Система Сигма-8, станция Штарке. Видимо планируется что-то интересное.",
               en="Wilhelm's back in touch. Offering another mission, this time in an unusual spot. Sigma-8 system, Stark Station. Something interesting's brewing."),

    HistRecord("h301",
               ru="Вильгельм познакомил меня с местным глав-солдафоном по имени Хасслер. Они нашли Дитриха и собираются штурмовать место его текущего обитания. Некая заброшенная станция в неизвестной мне системе Кёнигсберг. Никогда не слышал о такой, а вот о развалинах станции Регенсбург я слышал. Была когда-то у Рейнланда весёлая заварушка с Кусари в том месте. Только станцию Кёнигсберг никто не разрушал, а там еще и поселился Дитрих. Так что наше дело его оттуда выкурить.",
               en="Wilhelm introduced me to the local head honcho soldier, Hassler. They've located Dietrich and are planning to storm his current hideout—some abandoned station in a system called Königsberg. Never heard of it. Heard of the Regensburg ruins, though. Rheinland had a nasty tussle with the Kusari there once. But Königsberg wasn't destroyed; Dietrich just moved in. Our job is to smoke him out."),

    HistRecord("h302",
               ru="Да тут оказывается собрался целый рейнландский флот с целым линкором! Неплохо, операция будет по настоящему масштабной. Мы с Хасслером будем мобильной диверсионной группой. Попробуем нарушить работу станции перед тем, как прибудет основной флот. На самом деле, работа вполне себе опасная. Надеюсь, они заказали фрилансера не для того, чтобы воспользоваться им как пушечным мясом. Хотя надо вспомнить, а когда было иначе.",
               en="Turns out there's a whole Rheinland fleet here, with a battleship! Not bad; this is a real large-scale operation. Hassler and I will be the mobile strike team. Try to disrupt the station before the main fleet arrives. Honestly, it's pretty dangerous work. I hope they didn't hire a freelancer just for cannon fodder. Then again, when has it ever been different?"),

    HistRecord("h303",
               ru="У Хасслера есть интересное устройство, которое активировало дыру в этот самый Кёнигсберг. Знать бы откуда он его нашел. Было бы забавно, если бы это как раз было бы тем грузом, который мы везли в конвое с Аделмаром. Но это было совсем уж сильное совпадение. Хотя мне бы в будущем такое устройство тоже бы пригодилось.",
               en="Hassler's got a nifty device that activated a jump hole right to Königsberg. Wonder where he got it. Would be funny if it was the same cargo we were escorting with Adelmar. But that's too much of a coincidence. Still, a gadget like that could come in handy for me someday."),

    HistRecord("h304",
               ru="А вот и сам Кёнигсберг. При влёте в систему нам пришлось повоевать с защитниками системы, поэтому враг уже знает о нашем присутствии и начинает заряжать щит. Щит у Кёнигсберга действительно громный. Еще бы знать, зачем он такой огромный. Там может поместиться целый корабельный флот и еще пара торговых флотов с припасами. Можно предположить, что для этого этот щит такой большой и есть. Это его плюс и недостаток. На первом этапе щит слишком слабый и мы еще в силах атаковать его генераторы. Направляюсь к первому генератору, а второе звено мародёров отправилось сбивать второй генератор. Скоро Дитриху не поздоровиться.",
               en="And there's Königsberg. We had to fight through system defenders on entry, so the enemy knows we're here and is charging up the shield. Königsberg's shield is massive. Wonder why it's so huge. Could fit a whole battle fleet and a couple of supply convoys in there. Probably why the shield's that big. That's both its strength and weakness. In the first phase, the shield is still weak, and we can attack its generators. Heading for Generator One, while another team goes for Generator Two. Dietrich's about to have a bad day."),

    HistRecord("h305",
               ru="Мы сбили первый генератор, но Дитрих оказался не так прост, как... Да он всегда был какой-то чокнутый интриган, так что он нас подловил и сбил наше второе звено. Кстати, судя по разговору, они с Хасслером были когда-то корешами. К счастью, Хасслер дезертировать не планирует, так что мы летим выполнять работу мародёров. Нас там точно ждёт толпа корсаров и людей Дитриха, но мы их в любом случае раскидаем.",
               en="We took out the first generator, but Dietrich wasn't as easy as... Well, he's always been a crazy schemer, so he set a trap and took out our second team. Funny thing, from the chatter, it sounds like he and Hassler used to be buddies. Thankfully, Hassler isn't planning to defect, so we're flying in to finish the job. A whole crowd of Corsairs and Dietrich's men are waiting, but we'll scatter them regardless."),

    HistRecord("h306",
               ru="Генератору кранты! И прилетел Вильгельм с Райхманом. Пока щит ослабевал, мы успели раскидать корсаров, а потом началось бегство. Весь гарнизон Кёнигсберга ломанулся во все стороны и Дитрих в том числе. Я получил задачу преследовать этого террорюгу. В какой-то момент Дитрих нажал тормоз, развернулся и атаковал нас. При этом грузовик из его звена продолжил движения. Это было весьма странно, но пока надо разобраться с Дитрихом. У него какой-то временный супер-мега-щит, поэтому надо попытаться его разнести. Пока Дитрих уязвим, я всё еще могу повреждать навесное оборудование его корабля. Если сбить его спойлер, то он потеряет как турель, так и минную установку. Тогда его уничтожить будет гораздо проще. Надо попробовать.",
               en="Generator's toast! And in comes Wilhelm with Reichmann. While the shield was failing, we mopped up the Corsairs, then the rout began. The entire Königsberg garrison bolted in every direction, Dietrich included. My job is to chase down this terrorist. At one point, Dietrich hit the brakes, spun around, and attacked us. Meanwhile, a hauler from his group kept going. Very strange, but Dietrich's the priority. He's got some temporary super-mega-shield, so we need to punch through. While he's vulnerable, I can still damage his ship's components. Knock out his 'spoiler,' and he loses both a turret and a mine launcher. That'll make him much easier to finish. Let's try it."),

    HistRecord("h307",
               ru="Дитрих всё! Не спасла его хвалёная система защиты. Но Райхман был явно не рад тому, что грузовик ушел. Так что Хасслер получил по шапке, а мы толпой полетели вслед за грузовиком. Я совсем не верю в успех, ведь Дитриха мы ковыряли очень долго, а облаву на грузовик никто не планировал. А зря!",
               en="Dietrich's finished! His fancy protection system didn't save him. But Reichmann was clearly unhappy about that hauler getting away. So Hassler got chewed out, and we all piled after the hauler. I have little faith we'll catch it—we were tied up with Dietrich for so long, and nobody planned an intercept for the hauler. A mistake!"),

    HistRecord("h308",
               ru="Я был прав, грузовик смылся. Мы теперь направляемся на местную базу. Да, полетим прямо к пиратам. Видимо у Хасслера всё совсем хорошо со связями, если даже пираты его боятся.",
               en="I was right, the hauler got away. Now we're heading to a local base. Yeah, flying straight to the pirates. Guess Hassler's connections are really good if even the pirates are afraid of him."),

    HistRecord("h309",
               ru="Вот тебе и социальные связи. Миссию выполнил, Дитриха убил. Можно уже становиться героем. А из-за этого грузовика мне даже не планируют выплачивать всю сумму. Отдали две копейки, а Хасслер обещал с этим разобраться. Пусть разбираться, ведь получается меня опять прокатили. Честно говоря, уже нет веры в эти ласковых и милых адмиралов. Надо будет как-нибудь связаться с Алариком и найти работу по интереснее. Что-то я уже не уверен про успешную карьеру в Рейнланде.",
               en="So much for networking. Mission accomplished, Dietrich dead. I could be a hero. But because of that hauler, they're not even planning to pay me the full amount. Gave me peanuts, and Hassler promised to sort it out. Let him sort it, because it looks like I got stiffed again. Honestly, I'm losing faith in these 'kind and gentle' admirals. Should get back in touch with Alaric and find more interesting work. Not so sure about a successful career in Rheinland anymore."),

    HistRecord("h400",
               ru="Входящее сообщение от Джакобо. Срочно просит помощи, он находится на какой-то планете в системе Мюнхен. Выдвигаюсь. Он был взволнован. Это странно.",
               en="Incoming message from Jacobo. Urgently asking for help; he's on some planet in the Munich system. On my way. He sounded agitated. That's strange."),

    HistRecord("h401",
               ru="Теперь я понял причину волнения Джакобо, он оказывается под наблюдением властей. Когда я заходил в бар, то там были толпы рейнландских военных. Мне удалось найти Джакобо. Он меня умолял помочь ему улететь из Рейнданда и довезти какие-то важные документы. С трудом, но я согласился. Он обещал вознаграждение, да и бросать паренька не хотелось. Надеюсь, мы сможем прошмыгнуть через патрули.",
               en="Now I understand Jacobo's panic. He's under surveillance by the authorities. When I entered the bar, it was crawling with Rheinland military. I managed to find Jacobo. He begged me to help him get out of Rheinland and deliver some important documents. Reluctantly, I agreed. He promised payment, and I didn't want to leave the kid hanging. Hope we can slip past the patrols."),

    HistRecord("h402",
               ru="Джакобо натуральный самоубийца. Он купил Дромадер! Не, ну я согласен с его мотивацией. Старый его корабль был засвечен, а это тихий спокойный транспорт. Но мог же он купить хотя бы истребитель!",
               en="Jacobo's a natural-born suicide case. He bought a Dromedary! I mean, I get his logic. His old ship was compromised, and it's a quiet, unassuming transport. But he could've at least bought a fighter!"),

    HistRecord("h403",
               ru="Наша песенка спета. Джакобо по глупости решил лететь не в Кусари, а повёл нас прямо на территорию Рейнланда. И я бы смог с ним согласиться, что у гиперврат в Хонсю нас могла ждать облава, но надо было его уговорить попробовать найти гипердыру. В итоге нас поймали в Бисмарке почти сразу. Теперь некий Крейтмайер ведёт нас прямо на станцию Кёльн. Надеюсь, не на эшафот. Хотя я уже ни чему не удивлюсь.",
               en="Our song is sung. Jacobo, in his foolishness, decided not to head to Kusari but led us straight into Rheinland space. I could agree that the jump gates in Honshu might be watched, but I should've convinced him to look for a jump hole. Instead, we got caught near Bismarck almost immediately. Now some guy named Kreitmeier is escorting us straight to Cologne Station. Hopefully not to the gallows. Though, nothing surprises me anymore."),

    HistRecord("h404",
               ru="Да, оказалось на эшафот! К счастью, прилетели Хасслер и Аларик и вырубили конвоиров. Жаль только нам пришлось разделать старый линкор Вотан. Только я еле-еле разобрался, куда бить. Если бы не маркер интерфейса, то возился бы с ним целую вечность.",
               en="Yep, it was the gallows! Thankfully, Hassler and Alaric showed up and took out our escorts. Pity we had to scrap the old battleship Wotan. Took me forever to figure out where to shoot. Without the HUD markers, I'd have been at it all day."),

    HistRecord("h405",
               ru="Мы почти покинули Бисмарк. Пока летели, Хасслер рассказал про какой-то заговор, из-за которого всех участников спецоперации в Кёнигсберге приказали арестовать или перехватить. Хасслер это разнюхал, отыскал Аларика. А они уже прилетели к Кёльну узнав, что смогут там меня найти. Это они вовремя, а то пришлось бы находить мой чёрный ящик с этим дневником!",
               en="We're almost clear of Bismarck. During the flight, Hassler told me about some conspiracy that led to orders to arrest or intercept everyone involved in the Königsberg op. Hassler caught wind of it, tracked down Alaric. They came to Cologne knowing they'd find me. Good timing, or they'd be searching for my black box with this log in it!"),

    HistRecord("h406",
               ru="Засада! В сигме-8 нас уже ждал отряд во главе с целым рейландским крейсером! Теперь надо его уничтожить. Да, нас учили такому даже в лётной школе. Нужно прицельно атаковать его уязвимые точки. Нос, башни и двигатель. Тогда он быстро выйдет из строя! Эти цели помечены в интерфейсе, но часто проще их сразу выделять. Тогда даже ракеты будут лететь куда надо!",
               en="Ambush! In Sigma-8, a Rheinland cruiser and its escort were waiting! Now we have to take it out. Yeah, they taught us this in flight school. Target its weak points—bow, turrets, and engine. It'll go down fast! The HUD marks them, but it's often easier to manually target. Then even missiles go where they should!"),

    HistRecord("h407",
               ru="Крейсер всё, мы вроде бы почти отбились. Но в этот момент рейндандцы перехватили Джакобо. Я же знал, что Дромадер — это дырявое корыто! Грустно говорить, но Джакобо правильно сделал, когда продублировал перевозимые документы в моём бортовом компьютере. При этом Хасслер на эту новость как-то слишком едино отреагировал. Не уж то он думает, что это как раз документы с того грузовика Дитриха? Всё может быть. Но отступать уже нельзя. Если остановлюсь, то быстро схватят военные. Поэтому нужно срочно лететь отсюда в Либерти. И чем быстрее, тем лучше.",
               en="Cruiser's gone, we've almost fought them off. But then the Rheinlanders intercepted Jacobo. I knew that Dromedary was a leaky bucket! Sadly, Jacobo did the right thing by copying the documents to my ship's computer. Hassler's reaction to the news was... too calm. Does he think these are the same docs from Dietrich's hauler? Could be. But there's no turning back now. If I stop, the military will grab me fast. So we need to get to Liberty, and fast."),

    HistRecord("h408",
               ru="Мы уже в Форбсе, по дороге нам помешали корсары, после чего Хасслер, используя свой весёлый девайс, отправил нас в Либерти через активированную гипердыру. Сам Хасслер с нами лететь отказалась, что странно, но я надеюсь, что с ним будет всё хорошо. Но теперь это уже его личное дело. В Форбсе с нами связался получатель информации от Джакобо. Это некая Хетчер. Пригласила нас на рандеву в баре планеты Форбс. Грех отказываться!",
               en="We're in Forbes now; Corsairs harassed us along the way, then Hassler used his funky device to send us to Liberty through an activated jump hole. Hassler himself refused to come, which is odd, but I hope he'll be okay. His business now. In Forbes, we were contacted by the recipient of Jacobo's data—someone named Hatcher. Invited us to meet at the bar on Planet Forbes. Can't say no!"),

    HistRecord("h409",
               ru="Не смотря на грусть от смерти Джакобо, сам перелёт стоил свеч. Я теперь далеко от Рейнланда и относительной безопасности, а за сам перелёт нам с Алариком заплатили хорошее вознаграждение. По началу мне всё даже нравилось, но потом я решил расспросить Аларика, почему на его лице такая довольная улыбка. Оказалось, что эта Хетчер работает на местную спецслужбу! Еще одна интригантка по типу Вильгельма. Мне опять не повезло, ведь казалось бы – вылетел из ада, живи себе спокойно. И опять ко мне липнет очередной гениальный комбинатор. Но Аларик зарекнулся, что Хетчер работает на очень секретную спецслужбу. Может это связано с Орденом, о котором говорились в приключениях Эдисона Трента? Хотя вроде везде писали, что золотые времена Ордена прошли и теперь это лишь именование в этих старых сказках. А может это не так? Время покажет.",
               en="Despite the sadness over Jacobo's death, the trip was worth it. I'm far from Rheinland and its 'relative safety,' and Alaric and I got paid well for the run itself. At first, I was even liking it, but then I asked Alaric why he had that smug grin. Turns out this Hatcher works for a local intelligence agency! Another schemer like Wilhelm. My luck—I escape one hell, think I can live peacefully, and another master manipulator latches onto me. But Alaric swears Hatcher works for a very secretive agency. Maybe it's connected to the Order from those Edison Trent stories? Though everyone says the Order's golden age is over, now just a name in old tales. Or maybe not. Time will tell."),

    HistRecord("h500",
               ru="Хетчер снова на связи. Говорит, что изучила документы, они очень хорошие, но народ у Хетчер слишком тупой, чтобы понять всё до конца. Поэтому Хетчер просит меня отыскать какого-то башкавитого учёного, способного понять, что к чему в этих документах. Зато теперь я понимаю на кого она работает и это не Орден, а какая-то служба безопасности Альянса. Да, это даже не служба безопасности Либерти. Но может это всё еще связано с Орденом? Посмотрим. Сама Хетчер уверяет, что её пропуск с меткой СБА поможет мне получить ключи от всех дверей в случае каких-то проблем. Ну вроде пока мне не надо уничтожать террористов, так что миссия звучит просто и привлекательно. Надо попробовать.",
               en="Hatcher's back in touch. Says she studied the documents; they're very good, but her people are too dense to grasp the full picture. So she wants me to find some brainiac scientist who can make sense of it all. At least now I know who she works for—it's not the Order, but some Alliance Security Bureau. Yeah, not even Liberty Security. But maybe it's still connected to the Order? We'll see. Hatcher assures me her ASF badge will get me through any door if there's trouble. Well, at least I don't have to kill terrorists this time; the mission sounds simple and appealing. Worth a shot."),

    HistRecord("h501",
               ru="Первая засада. Станция Детроит, на которую мне надо сесть, всё закрыто. Сесть нельзя. Я позвонил Аларику за помощью. Тот предложил направиться к пиратам и разузнать про ключ там. Я отправился на склад Монтгомери. Злачное местечко. Там точно что-то должно про это быть.",
               en="First roadblock. Detroit Station, where I need to dock, is locked down. Can't get permission. Called Alaric for help. He suggested heading to the pirates to find out about a key. I went to the Montgomery Depot. Sleazy place. Something's gotta be there."),

    HistRecord("h502",
               ru="На Монтгомери я нашел какого-то нарика, который сечёт во всех этих ключах. Я прикинулся, что забыл на Детроите мешок дури и теперь проникнуть через их режим досмотра, чтобы этим мешочком воспользоваться. Нарик любезно передал мне координаты склада своих подельников. Задача упрощается. Вопрос только теперь, насколько эти подельники злые.",
               en="On Montgomery, I found some junkie who knows all about these keys. I pretended I'd left a bag of 'spice' on Detroit and needed to get through their security scan to retrieve it. The junkie kindly gave me coordinates to his buddies' stash. Makes things easier. Question is, how mean are these buddies?"),

    HistRecord("h503",
               ru="А подельники были очень злые! Оказывается их друг наркоман уже не первый раз так проштрафился. Они не были довольным моим прилётом, но в этот момент прилетела сама Хетчер и предложила мне помочь разобраться с пиратами. Но мне всё еще надо добраться до ключа. Я вижу тут склад контрабанды. Чтобы вытряхнуть его содержимое, мне надо открыть его двери. Для этого надо сначала сбить три склада в нижней его части, а потом залететь в ядро и взорвать его. Делать нечего, приступаем.",
               en="And the buddies were very mean! Turns out their junkie friend has messed up like this before. They weren't happy to see me, but then Hatcher herself showed up and offered to help deal with the pirates. But I still need to get that key. I see a contraband stash here. To crack it open, I need to blow its doors. First, take out three depots at its base, then fly into the core and detonate it. No choice, let's do it."),

    HistRecord("h504",
               ru="Ядро взорвано! Ключ у меня. Вместе с Хетчер мы полетели к Детроиту. Мне кажется, что эту проверку на профпригодность я прошел успешно. Хотя мой намёк она не поняла, но будем считать, что дамочка заработалась. Теперь осталось только найти учёного и доставить его к тем самым документам, чтобы изучал их под микроскопом с особым пристрастием.",
               en="Core's blown! Got the key. Flew with Hatcher to Detroit. I think I passed this little competency test. She didn't get my hint, but let's chalk that up to her being overworked. Now just need to find the scientist and deliver him to those documents for some serious scrutiny."),

    HistRecord("h505",
               ru="А ведь действительно значок СБА работает! Местный бармен сначала щемился, а увидев значок, сразу выдал про профессора Мандрейка всё как есть. Обитает профессор на станции Кларк, которая находится в сигме-17. Это соседняя система. Берём Хетчер в охапку и вперёд!",
               en="The ASF badge actually works! The local barkeep was being difficult, but one look at the badge, and he spilled everything about Professor Mandrake. The prof resides on Clarke Station in Sigma-17. Neighboring system. Grab Hatcher and off we go!"),

    HistRecord("h506",
               ru="Я чувствую дежавю и как чёрные кошки стремительно пробегают рядом со мной. Станция Кларк закрыта! Придется искать доступ и на неё. В этот момент пришло сообщение от транспорта, который попал засаду недалеко от нас. Вылетаем к нему на помощь. Не знаю, поможет ли транспорт нам сесть на Кларк, но спасать человека точно надо!",
               en="Feeling déjà vu, and black cats are running past me. Clarke Station is locked down! Gotta find a way in. Right then, a distress call from a transport caught in an ambush nearby. Off to help. Don't know if it'll get us onto Clarke, but saving a guy is the right thing to do!"),

    HistRecord("h507",
               ru="Бинго! Транспорт не против нам помочь с посадкой. Теперь надо его довезть до Кларка. Социальные связи, доброта и джентльменство всегда работают на ура. Не всегда нужно только махать шашкой.",
               en="Bingo! The transport's willing to help us get docking clearance. Now we just need to escort it to Clarke. Networking, kindness, and chivalry always pay off. Don't always have to wave a gun around."),

    HistRecord("h508",
               ru="Я вообще не понимаю, что происходит, но транспорт привёз на станцию что-то не то и она взорвалась нафиг! Обломки разлетелись в разные стороны, а в обломках замурованы спасательные капсулы. Надеюсь, что Мандрейк успел сесть в такую капсулу! Задача простая: атаковать обломки, выбить капсулы и забрать их в трюм. Я думаю, было бы правильно постараться спасти всех учёных, а не только Мандрейка.",
               en="I have no idea what's happening, but the transport brought something wrong to the station, and it blew to hell! Debris everywhere, and life pods are trapped in the wreckage. Hope Mandrake made it to a pod! Simple task: blast the debris, free the pods, and scoop them into my cargo hold. I think we should try to save all the scientists, not just Mandrake."),

    HistRecord("h509",
               ru="Теперь я понял, почему Хетчер переживала о конфликте интересов в Либерти. Нас попытались перехватить, а меня арестовать! Теперь я понимаю, почему это служба безопасности Альянса. Потому что Либерти нет до неё никакого дела! Мне кажется, никакого отношения к Ордену служба не имеет, если к ней относится как половым тряпкам. И слава всем номадским богам, но меня спасли рейнландцы. Как раз в тот момент, когда на меня хотели напялить наручники, из невидимости повылезали рейнландские корабли и решительно стали пытаться меня прикончить. А так как для пилотов Либерти я был тоже лакомым кусочком, они так просто со мной расставаться не захотели. И вот пока мы воевали с рейнландцами, на трубку местного коммандера Тилтона пришел звонок от больших шишек. Значит СБА чего-то стоит, поэтому Хетчер срочно потребовала от меня покинуть место сражения, пока Тилтон не передумал. И я был с ней полностью согласен.",
               en="Now I understand why Hatcher was worried about conflicting interests in Liberty. They tried to intercept us, and arrest me! Now I get why it's the Alliance Security Bureau. Because Liberty doesn't give a damn about it! I don't think it has anything to do with the Order if they treat it like a rag. Thank all Nomad gods, the Rheinlanders saved me. Just as they were about to slap cuffs on me, Rheinland ships decloaked and tried to finish me off. And since I was a juicy target for Liberty pilots too, they weren't about to let me go. So while we fought the Rheinlanders, Commander Tilton got a call from higher-ups. Means the ASF has some pull, so Hatcher urgently ordered me to bug out before Tilton changed his mind. I agreed completely."),

    HistRecord("h510",
               ru="И всё-таки СБА связана с Орденом. Лучше было бы её назвать огрызком, хотя после сегодняшнего дня я бы скорее назвал огрызком жалким. Такое ощущение, что даже в Рейнланде спецслужбы имеют больше власти, чем СБА в Либерти. Но они там всё равно что-то мутят с номадами, артефатками и прочими инопланетными вещами. Я на самом деле пока ничего не понял, но за работу мне заплатили. Зато в очередной раз доказали, что сказки про моего тёзку совсем не шутка. Это конечно радует, но я даже и не думал, как все эти приключения опасны для жизни.",
               en="So the ASF is connected to the Order after all. Better to call it a remnant, though after today I'd call it a pathetic remnant. Feels like even in Rheinland, the intelligence agencies have more clout than the ASF does in Liberty. But they're still mixed up with Nomads, artifacts, and alien stuff. I honestly don't understand much yet, but I got paid. Proved once again that the tales about my namesake are no joke. That's encouraging, but I never realized how life-threatening these adventures would be."),

    HistRecord("h600",
               ru="Хетчер снова на связи. Видимо они разобрались со своими учёными. Она позвала меня на планету Питсбург в системе Манхеттен.",
               en="Hatcher's back on the comm. Guess they sorted things with their scientists. She summoned me to Planet Pittsburgh in the Manhattan system."),

    HistRecord("h601",
               ru="В баре Питсбурга я нашел не только Хетчер, но и Аларика. Она предложила нам операцию по закрытию некой Сферы, чтобы рейнландцы не смогли там ничего сделать особо опасного с инопланетянами. Я склонен с ней согласиться, ведь именно рейнландская экспедиция в свое время стала причиной проблем с кочевниками. Пока всё смотрится неплохо.",
               en="At the Pittsburgh bar, I found not just Hatcher but Alaric too. She proposed an operation to seal some 'Sphere' so the Rheinlanders can't do anything too dangerous with aliens there. I'm inclined to agree; it was a Rheinland expedition that caused the Nomad problem in the first place. So far, so good."),

    HistRecord("h602",
               ru="Да, Хетчер, конечно, врёт как дышит. Сначала обещала просто поиграть в закрывашки, а теперь сменила пластинку, и мы опять начинаем играть в шиноби и ассасинов. На этот раз нужно не просто быть ассасином, а навесить на себя очень опасное устройство невидимости, проскользнуть через толпы рейнландцев, а потом еще и пролезть чёрт знает где, чтобы убить чёрт знает кого. Аларик считает, что это очень выгодная операция, а считаю, что мы уже зашли слишком далеко. Я честно уже думал собирать монатки, но ради Аларика решил пока с этим не торопиться. Да и Хетчер уже выдала нам слишком много секретной информации, поэтому теперь путь только вперед. А денег она предложила за эту операцию просто огромное количество. Но я уже не сильно уверен, что смогу эти деньги заполучить.",
               en="Yeah, Hatcher lies like she breathes. First, it was just a simple 'seal the door' gig. Now she changed the tune, and we're back playing ninja and assassin. This time, it's not just about being an assassin; I need to strap on a very dangerous cloaking device, slip through hordes of Rheinlanders, then navigate hell-knows-where to kill hell-knows-who. Alaric thinks it's a highly profitable op; I think we're in way over our heads. I was honestly considering packing up, but for Alaric's sake, I'll hold off. And Hatcher's already fed us too much classified intel, so the only way is forward. The money she's offering is astronomical. But I'm not so sure I'll live to collect it."),

    HistRecord("h603",
               ru="Мы попали в очень стрёмную систему. По информации, которую Хетчер передала Аларику, мы должны попасть в какую-то странную Сферу, сложенную из инопланетянских кубов. По виду похожа на гробницу земного фараона. Есть пирамида, есть проход к усыпальнице. Только на этот раз вход в пирамиду охраняет толпа рейнландцев. Хетчер предложила нам воспользоваться специальными стратегиями. В этих стратегиях придумано, как выйти из сложной ситуации. Но я всегда могу попробовать пролететь напролом. Например, в этой локации летают патрули. Если просто не попадаться патрулю, то можно спокойно пролететь без каких-либо проблем. Всего тут пять патрулей. Один внутри Сферы, два патруля вокруг верфи Гамбург, два патруля летают в туннеле внутрь Сферы.",
               en="We're in a very creepy system. According to intel Hatcher gave Alaric, we need to enter some strange Sphere made of alien cubes. Looks like an ancient pharaoh's tomb. There's a pyramid, a passage to the inner chamber. Only this time, the pyramid entrance is guarded by a crowd of Rheinlanders. Hatcher suggested using special 'strategies'—pre-planned ways to handle tough spots. But I can always try the brute force approach. For instance, there are patrols here. If you just avoid the patrols, you can slip through without issues. Five patrols total. One inside the Sphere, two around Hamburg Shipyard, two patrolling the tunnel into the Sphere."),

    HistRecord("h604",
               ru="Мы прошли через туннель. Место весьма жуткое. Местами совсем холодок по душе от этих монументальных изваяний. Мы нашли рейнландскую лабораторию, но для начала надо убить профессора Роттермана. До него еще лететь и лететь. Это будет моя работа, а Аларик будет думать, как проникнуть в лабораторию через местные щиты.",
               en="We made it through the tunnel. The place is downright eerie. Gives you chills with those massive alien structures. We found the Rheinland lab, but first, we need to kill Professor Rotterman. He's a long way in. That's my job, while Alaric figures out how to breach the lab's shields."),

    HistRecord("h605",
               ru="Вот теперь можно начинать геройствовать. Номады! Много номадов. Они летают вокруг какого-то зерна. И из-за этого зерна местная система защиты не даёт мне пролететь дальше. Ну что за напасть. Можно идти и напролом и разнести корабли кочевников. Или воспользоваться стратегией. Тут снизу есть какой-то генератор, сбив который можно повредить кочевников. Только главное самому не попасть под этот заряд энергии. Когда буду бить зерно надо помнить, что оно умеет производить номадские корабли. Так что чем быстрее я уничтожу зерно, тем с меньшим числом кочевником мне придется сразиться.",
               en="Now for the heroics. Nomads! Lots of Nomads. They're swarming around some kind of 'seed.' And because of that seed, the local defense system won't let me pass further. What a nuisance. I could charge straight in and blast the Nomad ships, or use a strategy. There's some generator below; destroying it will weaken the Nomads. Just don't get caught in the energy discharge myself. When attacking the seed, remember it can spawn more Nomad ships. So the faster I destroy it, the fewer I'll have to fight."),

    HistRecord("h606",
               ru="Зерно уничтожено и нужно продвигаться дальше. Проход открыт, и он должен привести меня к цели. Интересно, что там находится в этом ядре Сферы... Судя по данным Хетчер, тут находятся два аванпоста.  В одном находится небольшая база Роттермана, а в другом база его ассистентов. Если я потревожу Роттермана, то они точно отправят ассистента за подмогой. Стены тут слишком толстые, чтобы отправить сигнал о помощи. Так что надо не только перехватить Роттермана, но и не дать ассистенту добраться до своих, иначе мы с Алариком не успеем зачистить лабораторию. Так что нужно действовать. В крайнем случае я могу воспользоваться стратегией.",
               en="Seed destroyed, time to move forward. The passage is open and should lead to the target. Wonder what's in the Sphere's core... According to Hatcher's data, there are two outposts. One houses Rotterman's small base, the other his assistants'. If I spook Rotterman, they'll definitely send an assistant for help. The walls here are too thick for a distress signal. So I need to intercept Rotterman *and* stop the assistant from reaching his buddies, or Alaric and I won't have time to clear the lab. Gotta act. Can always fall back on a strategy if needed."),

    HistRecord("h607",
               ru="Миссия ассасина выполнена и пора возвращаться к Аларику. А в ядре теперь типо и спокойно. Ни души... только какая странная шарообразная штука посреди лазеров.",
               en="Assassin mission accomplished. Time to regroup with Alaric. The core is quiet now. Not a soul... just some strange spherical thing surrounded by lasers."),

    HistRecord("h608",
               ru="Мы покинули лабораторию. Аларик быстро заложил взрывчатку, а я забрал артефакты. Странный ключ и знаменитый том Протея. С ключом то всё понятно, он открыл вход в Сферу. А зачем им том? Но так как это всё равно ценный артефакт, а лабораторию мы взорвали, то я решил не рисковать. Пусть всё будет со мной. Зато Хетчер порадуется.",
               en="We left the lab. Alaric planted charges quickly, and I grabbed the artifacts. A strange key and the famous Proteus Tome. The key's obvious—it opened the Sphere. But why the tome? Still, it's a valuable artifact, and we blew the lab, so I'm not taking chances. I'll keep it. Hatcher will be pleased."),

    HistRecord("h609",
               ru="Я думал, что миссия закончена, а не тут-то было. Прозвучали сирены о приближении вражеских торпедных канонерок. Нужно снарядиться блокираторами круиза или любыми ракетами. Ими легко детонировать торпеды.",
               en="Thought the mission was over, but no. Alarms blare about incoming enemy torpedo bombers. Need to equip cruise disruptors or any missiles. They can detonate torpedoes easily."),

    HistRecord("h610",
               ru="Странная штука творится. Вроде бы от торпеды мы отбили, но Миссури пока не может покинуть Сферу. Так что мне приказали отправиться вместе с группой Альфа своим ходом, чтобы мы не потеряли артефакты.",
               en="Strange things afoot. We fended off the torpedoes, but the Missouri can't leave the Sphere yet. So I've been ordered to depart with Alpha Group under my own power, so we don't lose the artifacts."),

    HistRecord("h611",
               ru="Попались... Приехали.",
               en="Caught... We're done for."),

    HistRecord("h700",
               ru="Возвращаюсь к дневнику после длительного отсутствия. Тут произошла целая череда событий. Вот я и встретился с тем самым Орденом. Только арестант. Чудом выбрались. Но всё по порядку. Сначала нас поймали на вылете из системы Сферы. Это был некий линкор Навухудоносор. Нас посадили на линкор и отправили в камеру. Потом пришел какой-то капитан Сид и представился двойным агентом. Он выдал нам одежду и разрешил покинуть линкор на моём корабле, но артефакты нам не отдал. Иначе его бы выгнали со службы. Но это всё равно лучший вариант, я думал, что там и сгину. А вот ребята из группы Альфа меня совсем не порадовали. Вознаграждения не то, что не будет, я еще и теперь в полной опале, поэтому если вернусь в Либерти, то с меня шкуру сдерут. Так что надо обязательно что-то делать. Достать артефакты и притащить их Хетчер. Но как? Я не знаю где они. Поэтому я решил пока заняться местной работой и накопить деньжат. Мне выдали очередное киллерское задание против какого-то Билла Айронсайда. Если не ошибаюсь, он работают на полу легальную либертийскую ЧВК. Но они в том числе и враги Либерти, поэтому мне волноваться нечего. Убьем и заработаем.",
               en="Back to the log after a long absence. A whole chain of events happened. So, I met the Order. As a prisoner. Got out by a miracle. But in order: First, we were caught leaving the Sphere system. Some battleship called Nebuchadnezzar. They boarded us, threw us in a cell. Then some Captain Sid showed up, claimed to be a double agent. He gave us clothes and let us leave on my ship, but kept the artifacts. Otherwise, he'd be busted. Still, better than vanishing forever. The Alpha Group guys didn't impress me. Not only is there no reward, I'm now persona non grata. If I return to Liberty, they'll skin me alive. So I have to do something. Retrieve the artifacts and deliver them to Hatcher. But how? I don't know where they are. So I'll take local jobs for now, build up credits. They gave me another assassination contract—some Bill Ironside. If I recall, he works for a semi-legal Liberty PMC. But they're also enemies of Liberty, so no worries. Kill him and get paid."),

    HistRecord("h701",
               ru="Правильно мне говорили, что нельзя доверять этим барменам на фрипортах, а во внешних мирах тем более. Мне заплатили настолько мало за этого Билла Айронсайда, что тут даже говорить не о чем. Я было хотел накостылять этому бармену, но мне тут на связь вышел какой-то Рокфорд. Говорит, что он из СБА и поможет мне вызволить артефакты. Можно ли ему доверять? Понятия не имею, но у меня вообще нет никакого выбора. Так или никак.",
               en="They were right not to trust freeport barkeeps, especially out in the Edge Worlds. They paid peanuts for that Bill Ironside hit. Almost not worth mentioning. I was about to give that barkeep a piece of my mind when a guy named Rockford contacted me. Says he's from the ASF and can help retrieve the artifacts. Can I trust him? No idea, but I have zero options. It's this or nothing."),

    HistRecord("h702",
               ru="Этот Рокфорд оказывается местная суперзвезда. Стоило мне завалиться в бар Мальты, как тут сразу прибежали киллеры, но уже не по мою душу, а по душу этого Рокфорда! Еще бы чуть-чуть, и меня начали бы пытать. Но пришел этот Рокфорд, расстрелял всех нафиг и говорит «полетели». Что мне и оставалось сделать.",
               en="This Rockford is a local superstar. The moment I walked into the Malta bar, hitmen showed up—not for me, but for Rockford! A little more, and they'd have started torturing me for info. Then Rockford walks in, blasts everyone to hell, and says, 'Let's fly.' What else could I do?"),

    HistRecord("h703",
               ru="Происходит какой-то безостановочный экшен. Мы раскидали отряд Ордена на орбите Мальты и направились в сторону Малого Омикрона. Рокфорд сказал, что артефакты держат там. В Малом Омикроне он выдал мне бомбы, которыми я смогу совершить диверсию на базе Тортуга, на которой артефакты сейчас и хранятся. Это вообще странные бомбы. Радиус взрыва у них огромный, поэтому мне нужно положить их и сдетонировать, находясь на как можно дальнем расстоянии. Лучше вообще вылететь из этой базы, иначе меня этими бомбами тоже снесёт.",
               en="It's non-stop action. We scattered an Order patrol in Malta's orbit and headed towards Omicron Minor. Rockford says the artifacts are held there. In Omicron Minor, he gave me bombs to sabotage the Tortuga Base where the artifacts are stored. Weird bombs. Huge blast radius, so I need to place them and detonate from as far away as possible. Better leave the base entirely, or the blast will take me out too."),

    HistRecord("h704",
               ru="Рокфорд был прав. Тортуга отправила конвой, чтобы отправить артефакты на соседнюю базу. Я пришел вовремя. Но это какой-то супер-прокаченный транспорт. Он стреляет из электромагнитной пушки и снаряжен крутым щитом. Мне нужно находиться с транспортом, что перегрузить генератор. Это опасно, но другого выхода нет. Если я отлечу, то генератор восстановится.",
               en="Rockford was right. Tortuga dispatched a convoy to move the artifacts to a neighboring base. I arrived just in time. But it's some super-upgraded transport. Fires an EMP cannon and has a heavy shield. I need to stay close to overload its generator. Dangerous, but no other choice. If I fly away, the generator resets."),

    HistRecord("h705",
               ru="Дело сделано, том Протея у меня, а Рокфорд забрал номадский ключ. Рокфорд сказал, что у него тут есть рядом база в системе Омега-13. Там мы сможем отдышаться и придумать, как отправить артефакты в СБА.",
               en="Job's done. The Proteus Tome is mine, and Rockford took the Nomad key. Rockford says he has a nearby base in Omega-13. We can catch our breath there and figure out how to get the artifacts to the ASF."),

    HistRecord("h706",
               ru="Я кажется живой? Опять я подхожу к дневнику с мыслью, что моя история чудом продолжается. Рокфорд оказался совсем не агентом СБА. В какой-то момент он решил просто убить меня, но непонятным образом один из полученных мной артефактов активировался и в самый последний момент перенёс меня в другую сторону сектора Сириуса. Не знаю как это вообще происходит. Но теперь, кажется, я в Бретонии. Рядом находится линкор, возможно там есть люди, которые мне помогут.",
               en="Am I... alive? Again, I approach this log thinking my story continues by some miracle. Rockford was no ASF agent. At one point, he decided to just kill me, but inexplicably, one of the artifacts I had activated and teleported me across the Sirius sector at the last second. No idea how that works. But now, it seems, I'm in Bretonia. There's a battleship nearby; maybe people there can help."),

    HistRecord("h707",
               ru="На линкоре Принц Уэльский я познакомился с Дерси. Она обещала помочь мне с поиском СБА при условии, если том Протея не фальшивка. А для проверки у неё есть знакомый старьёвщик на планете Авалон. Можно отправляться, хотя на местном линкоре я могу купить себе другой корабль. Дешевый, но зато получше моего текущего. И без последствий этого странного телепорта.",
               en="On the battleship Prince of Wales, I met Dersey. She promised to help me find the ASF, provided the Proteus Tome is genuine. For verification, she has a contact—a junk dealer on Planet Avalon. Can head there, though I could also buy another ship from this battleship's dealer. Cheap, but better than my current one. And without the side effects of that weird teleport."),

    HistRecord("h708",
               ru="Да, старьёвщик знает своё дело. Коллекция его восхитительна. Особенно меня позабавил крот в банке и мужик с надписью «Илон». А так Джабба подтвердил подлинность тома, но Дерси его реакция не понравилась. С чего бы. Теперь она же она точно знает, что я не врал.",
               en="Yeah, the junk dealer knows his stuff. His collection is amazing. Especially amused by the mole in a jar and the guy labeled 'Elon.' Anyway, Jabba confirmed the tome's authenticity, but Dersey didn't like his reaction. Wonder why. Now she knows for sure I wasn't lying."),

    HistRecord("h709",
               ru="Вот и причина расстройства Дерси, в космосе нас уже ждали люди Джаббы. Хотя в этот раз будто бы наоборот, Дерси прямо с удовольствием повязала Джаббу и вывела под конвоем. Видимо Джабба давно был местным властям поперёк горла, а я дал им для этого повод. Надеюсь, что его коллекцию не распродадут. Сделаю, может быть, музей. Или что-то вроде такого.",
               en="And there's the reason for Dersey's distress. Jabba's men were waiting for us in space. Though this time, it seemed Dersey was happy to arrest Jabba and take him away under escort. Guess Jabba's been a thorn in the authorities' side, and I gave them the excuse. Hope they don't auction off his collection. Maybe make a museum. Something like that."),

    HistRecord("h800",
               ru="Получил звенок от Дерси. Встреча на планете Авалон. Надеюсь, она нашла способ помочь мне связаться с СБА.",
               en="Got a call from Dersey. Meetup on Planet Avalon. Hope she's found a way to help me contact the ASF."),

    HistRecord("h801",
               ru="Нашел Дерси в баре Авалона. Она меня познакомила с двумя интересными личностями. Принцессой Кейтлин и адмиралом Брайтоном. Принцесса какая-то странная, как будто ей вообще всё равно, что мы делаем. А вот Брайтон поведал о приключениях местных террористов в запрещенной для посещения системе. И эта система связана с Орденом и инопланетянами. По этой причине меня и вызывали, так как я теперь считаюсь экспертом по Ордену. С чего бы? Но грех отказываться, ведь мне предложили отличную оплату по олимпийскому принципу. Чтобы мы там не нашли, я получу кучу денег.",
               en="Found Dersey at the Avalon bar. She introduced me to two interesting figures: Princess Caitlin and Admiral Bration. The princess seems odd, like she doesn't care what we do. But Bration told us about local terrorists operating in a forbidden system. And that system is linked to the Order and aliens. That's why they called me—I'm now considered an Order 'expert.' Since when? But no sin in refusing? They offered excellent pay on a 'finders keepers' basis. Whatever we find, I get a hefty sum."),

    HistRecord("h802",
               ru="Система Тау-44 по-своему зловеща и не просто так. Мы нашли лишь остатки базы террористов и заброшенную лабораторию. Она изучала... тарелку? Огромную тарелку, которая, как я понял, была Логовом Номадов. У входа в Логов мы с Дерси обнаружили патруль Либерти. Он сразу без предупреждения вступил с нами в бой. После чего мы получили приказ проникнуть в логово. Я хоть и побывал в Сфере и весьма пуганый, но это уже штука совершенно другого порядка. Если тут и должны быть кочевники, то их может быть вполне себе много.",
               en="Tau-44 is eerie for a reason. We found only remnants of a terrorist base and an abandoned lab. It was studying... a disc? A huge disc, which I gather is a Nomad Hive. At the Hive entrance, Dersey and I stumbled upon a Liberty patrol. They engaged immediately, no warning. After that, we were ordered to penetrate the Hive. I've been in the Sphere and I'm spooked enough, but this is a whole other level. If Nomads are supposed to be here, there could be a lot of them."),

    HistRecord("h803",
               ru="Вся эта миссия — это сплошной дурдом. Я добрался до дневника только сейчас, вылетая с Осириса. Мы залетели в логово, нашли там Тилтона, который нас повязал и возомнил себя богом. Он стрельнул по ядру Логова Номадов из крейсера, что привело к цепной реакции, которая привела к разрушению логова, Тилтона и его банды. Мы с Дерси еле-еле убежали, сверкая пятками. Снаружи проблема стала хуже, т.к. тут был целый флот Либерти, тогда как нам на помощь прибыл Брайтон. Мы пытались остановить разрушение логова, но цепная реакция усилилась и повредила корабль Брайтона. Все получили приказа покинуть систему, но Брайтон решил остаться на корабле и погиб геройской смертью. Дерси была очень расстроена, но и это тоже не конец. На «звук» взрыва логова прибежала мисс Хетчер. С одной стороны, я добился своей цели и нашел СБА. С другой стороны, на меня опять напялили «кандалы» и отправили с конвоем уже на разговор с СБА. Хетчер была явно рада тому, что нашла меня. Она стала бы еще счастливей, если бы меня придушила. Она привела нас к руководству СБА – тому самому легендарному генералу Кингу. Да, он действительно существует и руководит СБА на данный момент. Сколько же ему лет? Я думаю, уже под сотню. Я ему рассказал про встречу с Рокфордом и как я потерял артефакты. Казалось бы, вот-вот меня отпустят по своим делам, но эти ребята тоже начали плести интриги. Мне, честно, уже стало совсем всё равно на то, кто куда и зачем крутит вертит свои политические интриги. Но тут мне говорят, что Аларик попал в плен к Ордену и, как обычно, только я могу его вызволить. Выбора они мне не оставили. Так что следующая остановка – попытаемся проникнуть в Орден. Каким образом – неизвестно. Хетчер скоро скажет как.",
               en="This whole mission is pure insanity. I'm only getting to the log now, leaving Osiris. We entered the Hive, found Tilton there, who captured us and fancied himself a god. He fired on the Hive's core from his cruiser, triggering a chain reaction that destroyed the Hive, Tilton, and his gang. Dersey and I barely escaped with our skins. Outside, it got worse—a full Liberty fleet was there, while Bration arrived to help us. We tried to stop the Hive's destruction, but the chain reaction intensified and crippled Bration's ship. Everyone was ordered to evacuate, but Bration chose to stay with his ship and died a hero's death. Dersey was devastated, but that's not the end. The 'sound' of the Hive's explosion attracted Ms. Hatcher. On one hand, I achieved my goal and found the ASF. On the other, they slapped 'cuffs' on me again and sent me under escort to talk with the ASF. Hatcher was clearly thrilled to find me. She'd have been even happier to strangle me. She brought us to ASF leadership—the legendary General King himself. Yes, he really exists and leads the ASF currently. How old is he? Must be near a hundred. I told him about meeting Rockford and losing the artifacts. You'd think they'd let me go on my way, but these guys started scheming too. Honestly, I'm past caring who twists which political intrigue for what purpose. But then they tell me Alaric has been captured by the Order and, as usual, only I can rescue him. They left me no choice. So next stop—infiltrate the Order. How? Unknown. Hatcher will say soon."),

    HistRecord("h900",
               ru="Звонок от Хетчер. Они нашли способ связаться с Орденом, место встречи – станция Йокогама в системе Омега-3 и Дерси там уже меня ждёт. Выдвигаюсь",
               en="Call from Hatcher. They've found a way to contact the Order. Meeting place is Yokohama Station in Omega-3, and Dersey is already waiting there. On my way."),

    HistRecord("h901",
               ru="С виду станция Йокогама это обычная, хоть и большая, торговая станция. А на деле это целая штаб-квартира Ордена. По середине сектора Сириуса! Я часто бывал на этой станции и даже не замечал этого. А теперь наоборот. Меня на ней заметили все! Пялились глазами и прямо прожигали меня насквозь. В этот момент к нам с Дерси подошел Хасслер. Получается он теперь агент Ордена. В принципе, логично, ведь на Рейнланд он работать теперь не может. Он пригласил меня сходить на встречу к лидеру Ордена, какому-то Ямамото. Хасслер обещал неприкосновенность, а причин не доверять ему у меня нет. Так что мы отправились в настоящий бар Йокогамы. И... уууу, дааааа, бар там классный. Танцы, веселье. Жалко, что только мне было не до шуток. Меня посадили за столик с Ямамото и всё как обычно: он начал плести интриги. Он согласен был помочь мне с Рокфордом, но за это я должен был сотворить что-то эдакое против СБА. Вроде бы ничего такого криминального, но Дерси прямо сильно этим встревожилась. Но есть ли у меня выбор?",
               en="On the surface, Yokohama is just a regular, albeit large, trade station. In reality, it's the Order's headquarters. Right in the middle of Sirius! I've been here often and never noticed. Now it's the opposite. Everyone noticed me! Staring, eyes burning through me. That's when Hassler approached Dersey and me. So he's an Order agent now. Makes sense; he can't work for Rheinland anymore. He invited me to meet the Order's leader, some Yamamoto. Hassler promised safe passage, and I have no reason to distrust him. So we went to the real Yokohama bar. And... wow, yeah, the bar is classy. Dancing, fun. Pity I'm not in a joking mood. They sat me at a table with Yamamoto, and it's the usual: he started weaving plots. He agreed to help me with Rockford, but in return, I had to do something against the ASF. Seems not too criminal, but Dersey was seriously alarmed. But do I have a choice?"),

    HistRecord("h902",
               ru="С виду эти ребята из Ордена и не такие плохие. Мотивированные, все со своими целями и убеждениями. Когда я работал на СБА было ощущение, что там народ сам не знает, что делает. Просто не дают делам развалиться. Не положи, не тронь. Да и орденцы про это тоже так говорят. Видимо им тоже стоит поперёк горла эта «положь-не-трожь» политика со стороны СБА. Но что-то мне подсказывает, что мотивирован Орден далеко не только этим.",
               en="On the surface, these Order guys aren't so bad. Motivated, all with their own goals and convictions. Working for the ASF felt like the people there didn't know what they were doing. Just keeping things from falling apart. 'Don't put it down, don't pick it up.' And the Order says the same. Guess the ASF's 'hands-off' policy gets on their nerves too. But something tells me the Order is motivated by more than just that."),

    HistRecord("h903",
               ru="Да эти ребята реально безбашенные! У нас были шансы уйти по-простому, а местный инженер взял и с разбегу разнёс местный линкор к чёртовой матери! Даже не знаю, какими патриотичными фильмами их там накручивают. Натуральные камикадзе. Теперь я понимаю, почему Хасслер работает именно на них. Только у него какие-то мутки с новым персонажем по имени Ким. Этот Ким тот ещё грозный вояка, палец в рот не клади, оторвёт всю руку. Судя по его реакиции, нашу операцию спланировал именно Хасслер и именно Хасслер убедил Орден пойти на этот риск. Зачем? Что они такого запланировали с этими данными про Энтерпрайз? Загадка.",
               en="These guys are truly reckless! We had a chance to leave quietly, and some local engineer just charged and blew the local battleship to smithereens! No idea what patriotic films they're feeding them. Natural-born kamikazes. Now I understand why Hassler works for them. Though he's got some shady business with a new character named Kim. This Kim is one fierce warrior—cross him and you lose a hand. Judging by his reaction, Hassler planned this op, and Hassler convinced the Order to take this risk. Why? What did they plan with that data about the Enterprise? A mystery."),

    HistRecord("h1000",
               ru="Сегодня «утро» было в крепких стенах орденского линкора производства Кусари. Мы встретились с Дерси и пошли в бар к Хасслеру. Он наконец-то начал разговор о том, что действительно нужно мне. О том, как спасти Аларика. Моего старого приятеля оказывается держат в странной тюрьме Ксеносов. Как он туда попал и почему? Неизвестно. Из этой тюрьмы мне надо спасти кого-то другого, а Аларик будет добавлен до кучи. Скажем, на сдачу. Конечно, мне интересно, что было бы с Алариком, если бы мне такую цель не ставили. Зато тут явно видно, что этот важный узник настолько ценен, что Орден готов выделить серьезные ресурсы для этой операции. Это интересно.",
               en="Today's 'morning' is within the sturdy walls of an Order battleship of Kusari make. Met up with Dersey and went to Hassler's bar. He finally started talking about what I actually need—how to rescue Alaric. Turns out my old buddy is held in a strange Xeno prison. How and why he got there is unknown. From this prison, I need to rescue someone else, and Alaric will be thrown in as a bonus. Let's say, as change. Of course, I wonder what would've happened to Alaric if they hadn't set this goal for me. But clearly, this other important prisoner is so valuable that the Order is willing to commit serious resources. Interesting."),

    HistRecord("h1001",
               ru="Мой корабль готовят к вылету. Его обработали специальным мимикрирующим материалом. Работать будет ближайшие несколько часов, поэтому работать надо быстро. В этой туманности есть несколько видов газа. Плотный и разреженный. В плотном я буду абсолютно невидим. Важно следить за интерфейсом и работой моего корабля. Пока интерфейс не скажет, что я вышел из облака, то я невидим. Так же это видно по работе двигателя. Пока я в плотном газе, скорость моего корабля медленная. Надо быть аккуратным и не суетиться. Если всё пойдёт хорошо, то пролечу быстро.",
               en="My ship is being prepped for launch. They coated it with a special mimetic material. It'll last a few hours, so I need to work fast. This nebula has different gas densities—thick and thin. In the thick gas, I'll be completely invisible. Important to watch the HUD and my ship's performance. As long as the HUD doesn't say I've left the cloud, I'm invisible. Also, engine output is lower in thick gas, so speed is slow. Need to be careful, not rush. If all goes well, I'll get through quickly."),

    HistRecord("h1002",
               ru="Я прошел зону разреженных газов. Теперь мы в основном облаке туманности. Ксеносы раскидали тут мины, теперь мне нужно пройти через них и не взорваться. Главное не торопиться. Можно отойти в сторону и подождать, пока щит не восстановится. Тогда всё пойдёт гладко.",
               en="Made it through the thin gas zone. Now we're in the main nebula cloud. The Xenos littered it with mines; need to navigate through without blowing up. Key is not to hurry. Can move to the side and wait for shields to recharge. Then proceed smoothly."),

    HistRecord("h1003",
               ru="Очередная задача на взлом панели. Всё как обычно, нужно просто найти нужный цвет. Он отбивается фразой «максимальный». Надо быть аккуратным и стараться прицельно бить именно в верные цвета, иначе это может спровоцировать местную систему защиты.",
               en="Another panel hacking task. Same as usual, just need to find the right color. It's indicated by the word 'maximum.' Need to be careful and aim precisely for the correct colors, or it might trigger the local defense system."),

    HistRecord("h1004",
               ru="Штурм базы Ксеносов прошел очень энергично. Мы влетели с разбегу в центральную зону, раскидали турели и держали базу под огнём. В этот момент к нам прилетел бронированный транспорт с десантом. Но эти ребята быстрые, разобрались с местными на раз два и уже выбегали с арестантами. Осталось только сопроводить транспорт до Мусаси и посмотреть, кого эдакого важного они оттуда достали.",
               en="The assault on the Xeno base was vigorous. We charged into the central zone, cleared turrets, and kept the base under fire. Then an armored transport with troops arrived. These guys are quick—dealt with the locals in no time and emerged with prisoners. Just need to escort the transport to Musashi and see who this important person they extracted is."),

    HistRecord("h1100",
               ru="Вот это представление. Оказывается я не только вызволил Аларика, но и вызволил сам себя. Того самого Эдисона Трента! Он, конечно, уже не такой красавчик как Кинг. Видимо в тюрьме у Ксеносов нет таких пластических хирургов, как на Энтерпрайзе. Внешность у него... ну назову его ренегатом. Просто почему-то подумалось. Но было очень интересно с ним познакомиться. Он весь такой из себя уверенный и независимый. Явно, ему эти правительства и спецслужбы уже давно были поперёк горла, как и мне сейчас. Жаль, поговорить с ним не получилось, так как Хасслер пришел с очередной новостью. Орден нашел Рокфорда. Тот тусит на одной из станций в системе Омега-7. Только непонятно, что он там делает. Сидит, отдыхает? Мне поставлена задача отвлечь его, пока Орден устроит засаду. Это на самом деле очень рискованно, и я думал реально отказаться. Вдруг Рокфорд в этот момент просто достанет револьвер и сделает пиф-паф? Как в том салуне на Мальте. Но Аларик убедил меня, что надо рискнуть. Он совсем ослаб после плена, но верно рассудил, что если не я помогу с Рокфордом, то потом кто-нибудь поможет Ордену со мной. Может это будет этот самый Ким. Или Хетчер? Подойдёт сзади, и скажет: «Мистер Ямамото передаёт свой привет» и шмальнёт из лупары. Проверять я это, конечно, не буду.",
               en="Now that's a show. Turns out I didn't just rescue Alaric; I rescued myself—the original Edison Trent! He's not as dashing as King, of course. Guess Xeno prisons don't have plastic surgeons like the Enterprise does. His appearance... well, I'd call him a renegade. Just a thought. But it was fascinating to meet him. He's all confidence and independence. Clearly, governments and agencies have been a thorn in his side for ages, just like for me now. Pity we couldn't talk more, as Hassler arrived with more news. The Order found Rockford. He's hanging out at a station in Omega-7. Not sure what he's doing there. Just relaxing? My task is to distract him while the Order sets an ambush. It's very risky, and I seriously considered refusing. What if Rockford just pulls a revolver and goes 'bang-bang'? Like in that saloon on Malta. But Alaric convinced me to risk it. He's weak after captivity but rightly reasoned that if I don't help with Rockford, someone will help the Order with me later. Maybe that Kim guy. Or Hatcher? She'll come from behind and say, 'Mr. Yamamoto sends his regards,' and blast me with a Lupara. I won't be testing that theory."),

    HistRecord("h1101",
               ru="Я накосячил. Не успел я остановить Рокфорда, он вышел из бара слишком рано. Но зато я живой, и он не сделал пиф-паф. Видимо, я не являюсь предметом его интересов. Но зачем он вообще был в этом баре и почему так стремительно ушел? Я думаю, он чего-то ждал и дождался. Если бы мы прилетели раньше, то тогда бы успели подготовиться. Значит произошло что-то еще. Сейчас мой корабль уже вылетает в космос, мы с Кимом попытаемся догнать Рокфорда в космосе. Если мы его и не убьем, то может хотя бы поймем, что он тут затеял и вызовем кавалерию.",
               en="I messed up. Didn't manage to stall Rockford; he left the bar too early. But I'm alive, and he didn't go 'bang-bang.' Apparently, I'm not his target. But why was he in that bar, and why leave so abruptly? I think he was waiting for something and got it. If we'd arrived earlier, we could've prepared. So something else happened. Now my ship is launching into space; Kim and I will try to catch Rockford out there. If we don't kill him, maybe we'll at least figure out his plan and call in the cavalry."),

    HistRecord("h1102",
               ru="Что за дела. Во-первых, я и не знал, что тут в системе есть целый штаб Ордена. А во-вторых, он еще и атакован. Целый флот Рейнланда прилетел и устроил тут огромную заварушку! Они умудрились угнать какой-то генератор и Ямамото это очень не понравилось. Скажем, для спокойного японца он был достаточно агрессивен. Для Кима эта реакция была бы обычной. Сама система со штабом Ордена весьма интересная. Тут находится огромная мегабаза Вавилон, а также размещены терраформирующие станции. Они обрабатывают местную планету и, видимо, планируют её заселение в будущем. Устроились ребята хорошо, осталось только пересилить сюда пару миллиардов человеков.",
               en="What the hell. First, I had no idea there was a whole Order headquarters in this system. Second, it's under attack. A full Rheinland fleet showed up and started a huge brawl! They managed to hijack some generator, and Yamamoto was not happy. For a calm Japanese guy, he was quite aggressive. For Kim, that reaction would be normal. The system with the Order HQ is quite interesting. There's a huge mega-base, Babylon, plus terraforming stations. They're processing the local planet, presumably for future colonization. They've set up nicely; just need to move a couple billion people here."),

    HistRecord("h1103",
               ru="Теперь я понял, что тут ждал Рокфорд. Или он сам натравил или просто знал, но как только мы смогли найти генератор у рейнландцев, тут же появился Рокфорд, убил курьера и перехватил генератор! Орден потерял важный артефакт, Рокфорд получил что хотел и смылся живой здоровый! Я, честно говоря, уже задолбался. Это не моя работа. В который раз что-то уходит мимо, и я прямо вот предвкушаю, как завтра за мной придёт толпа офицеров, повяжут и скажут «пройдёмте-с». И расстреляют за очередной косяк! Ямамото на этот раз был в натуральной ярости. В тот момент, когда Рокфорд угнал генератор, прилетел Райхман на своём зелёном космолёте, что-то там пробурчал, а Ямамото резко нам приказал разнести линкор Гнейзенау в щепки. Да что уж там, рейнландцы готовы были сдаться, а Ямамото решил разнести линкор до конца в назидание! Это какая-то натуральная жесть, я, честно говоря, в такой политической грызне участия принимать не желаю. С меня хватит.",
               en="Now I see what Rockford was waiting for. Either he tipped them off or just knew, but the moment we located the generator with the Rheinlanders, Rockford appeared, killed the courier, and snatched the generator! The Order lost a crucial artifact, Rockford got what he wanted, and got away scot-free! I'm honestly fed up. This isn't my job. Time after time, something slips away, and I can just picture a squad of officers showing up tomorrow, cuffing me, saying, 'Come with us,' and executing me for another failure! Yamamoto was in a genuine rage this time. Just as Rockford stole the generator, Reichmann showed up in his green spacecraft, muttered something, and Yamamoto abruptly ordered us to blast the battleship Gneisenau to pieces. Hell, the Rheinlanders were ready to surrender, but Yamamoto wanted it destroyed as a lesson! This is insane. I honestly don't want any part of this political squabbling. I've had enough."),

    HistRecord("h1104",
               ru="Мои планы снова поменялись. Когда я было хотел уже нахерачиться чем погорячее, появился мой тёзка и стал втирать про то, что дрейфить еще рано. И всё на самом деле куда серьёзней, чем мы все думали. Рокфорд не просто так украл генератор, у него какой-то план «спасения мира» и его нужно остановить. У меня на руках все ключи, чтобы это сделать. Вроде звучит как не сложная задача, главное просто убедить нужных людей принять правильные решения. Даже не надо никого убивать. Мне даже интересно это попробовать!",
               en="My plans changed again. Just when I was about to get thoroughly drunk, my namesake showed up and started talking about how it's too early to panic. That everything is far more serious than we thought. Rockford didn't steal the generator for nothing; he has some 'save the world' plan that needs stopping. I have all the keys to do it. Sounds like a simple enough task; just need to convince the right people to make the right decisions. Don't even have to kill anyone. I'm almost curious to try!"),

    HistRecord("h1200",
               ru="Я вызывал всех друзей на Спрагу. Во время полёта о мне вспомнил Ким. Перед общением с мистером Трентом, Ким просил меня остыть и подождать сигнала. А потом я улетел. А сигнал был о какой-то операции, которую сейчас планирует проводить Ямамото. Это уже точно к чёрту. Спецоперации пусть проводят сами. Есть дела и поважнее.",
               en="I called all friends to Spur. During the flight, Kim remembered me. Before meeting with Mr. Trent, Kim asked me to cool off and wait for a signal. Then I left. The signal was about some operation Yamamoto is now planning. To hell with that. Let them run their own special ops. There are more important things."),

    HistRecord("h1201",
               ru="И вот опять сюжетный поворот, я понял о какой спецоперации шла речь! Этот хорёк Хасслер оказывается собрал разведданные о штабе СБА, и они всей орденской толпой пошли штурмовать Энтерпрайз, чтобы снести его нахер! Я даже не успел убедить Хетчер согласиться помочь с Рокфордом! Все резко драпанули в Энтерпрайз, чтобы не дать Ордену реализовать задуманное. Теперь летим толпой на всех порах. Дерси попыталась связаться с Бретонией, но эти гниды даже не собираются нам помогать. Видимо, если Орден прорвётся и победит Кинга, то Бретония будет с ним мириться и договариваться о разделе сфер интересов. Весьма интересная ситуация. Значит мы теперь против Ордена один на один. И я более чем уверен, что этим орденским баранам плевать на Рокфорда. Есть, конечно, шальная мысль, а вдруг именно Орден помог бы мне против Рокфорда? Но я предположу, что не просто так именно Орден вызволил из тюрьмы моего тёзку – Эдисона Трента. Значит кто-то там знал, что будет именно так, и попытка убедить Ямамото уже была. Значит теперь мне нужно убедить Кинга. А для этого мне нужно сделать, чтобы Кинг выжил.",
               en="And another plot twist—I realized what operation they meant! That weasel Hassler gathered intel on the ASF headquarters, and the whole Order mob is going to storm the Enterprise to blow it to hell! I didn't even have time to convince Hatcher to help with Rockford! Everyone suddenly bolted to the Enterprise to stop the Order's plan. Now we're flying there at full throttle. Dersey tried contacting Bretonia, but those bastards aren't planning to help. Apparently, if the Order breaks through and defeats King, Bretonia will make peace and negotiate spheres of influence. Quite a situation. So it's just us against the Order now. And I'm more than sure those Order sheep don't care about Rockford. There's a wild thought—what if the Order would actually help me against Rockford? But I suspect there's a reason the Order sprung my namesake—Edison Trent—from prison. Someone there knew this would happen, and the attempt to convince Yamamoto already occurred. So now I need to convince King. And for that, I need to keep King alive."),

    HistRecord("h1300",
               ru="Это была весьма агрессивная операция, но мы справились. Ямамото у нас в плену, а также мы смогли убедить Кинга, что надо остановить планы Рокфорда. Мы уже направляемся в Сферу. Оказывается Сфера это не просто набор кубиков, а что-то большое и опасное, что может хорошенько бумкнуть, что мало никому не покажется. Эдакая маленькая локальная сверхновая.",
               en="That was a very aggressive operation, but we managed. Yamamoto is our prisoner, and we convinced King that Rockford's plans must be stopped. We're heading to the Sphere now. Turns out the Sphere isn't just a bunch of cubes; it's something big and dangerous that can go boom in a way no one will enjoy. A kind of local supernova."),

    HistRecord("h1301",
               ru="Линкор Осирис. Мы уже покинули Сферу. События развивались стремительно. Мы успели повредить излучатель, сделанный Рокфордом, но было слишком поздно. Он умудрился попасть по этому шару в центре Сферы. Мандрейк сказал, что это страшный и ужасный инопланетянин, которого он назвал Крыгом. Почти как круг. Только Крыг. Мы смогли не дать этому Крыгу зарядиться, но он решил подружиться с номадами и натравить их на нас. В этот момент нам помог мой тёзка. Он открыл запасной ход, и мы полетели к Осирису. Теперь нам нужно использовать вытащенный мной номадский генератор и запулить его чёрную дыру, чтобы отправить туда Крыга раз и навсегда. Не знаю, как это должно работать. Как я понял, генератор для Крыга очень вкусный и если правильно генератор подкрутить, то он будет излучать особые домкавашские феромоны. Мандрейк предполагает, что Крыг должен просто одуреть с этой прикормки, и безропотно отправить вслед за генератором в чёрную дыру. Считай в самую преисподнюю.",
               en="Battleship Osiris. We've left the Sphere. Events moved fast. We managed to damage the emitter Rockford built, but it was too late. He managed to hit that sphere at the Sphere's center. Mandrake called it a terrible, horrible alien named 'Krieg.' Almost like 'circle,' but 'Krieg.' We stopped Krieg from fully charging, but it decided to befriend the Nomads and sic them on us. That's when my namesake helped. He opened an alternate passage, and we flew to the Osiris. Now we need to use the Nomad generator I retrieved and launch it into the black hole to send Krieg there for good. Not sure how it's supposed to work. As I understand, the generator is very 'tasty' to Krieg, and if tuned right, it'll emit special 'Dom'Kavash pheromones. Mandrake thinks Krieg will go nuts for the bait and follow the generator into the black hole. Straight to hell, basically."),

    HistRecord("h1302",
               ru="Как обычно, всё пошло не по плану. Вроде бы банальная операция – пролететь через астероидный пояс и добраться до чёрной дыры. Но номады успели всё заминировать своими зёрнами, а Крыг эти зёрна еще и усилил. Мой корабль выдержал нагрузку, а корабль тёзки сломался. Сам тёзка в порядке, и я уже вызвал сигнал об эвакуации, но летать он уже не сможет. Генератор в чёрную дыру нести придётся мне. А так как катапульты для генератора у меня в корабле нет, то придётся лететь на корабле самому. Теоретически, у меня нет шансов как попасть в чёрную дыру живым, как и выбраться из неё живым. Поэтому этот журнал я не буду выбрасывать из корабля и оставлю с собой. Если где-то в чёрной дыре я и выживу, то это будет интересной находкой для второго такого идиота, как я. Прощай, мир!",
               en="As usual, nothing went according to plan. Seemed a simple op—fly through an asteroid belt and reach the black hole. But the Nomads mined everything with their seeds, and Krieg amplified them. My ship withstood the strain, but my namesake's ship broke down. He's okay, and I've called for evac, but he won't be flying. Carrying the generator into the black hole falls to me. And since my ship doesn't have a catapult for the generator, I'll have to fly it in myself. Theoretically, I have zero chance of entering a black hole alive, let alone coming out. So I won't eject this log; I'll keep it with me. If I somehow survive inside a black hole, it'll be an interesting find for the next idiot like me. Farewell, world!"),
]


def get_history_items_dict(ids):
    items = {}
    for record in history_records:
        if record.index in items:
            raise Exception(f'history item {record.index} already used')
        items[record.index] = HistoryItem(ids, record)
    return items
