from text.strings import MultiString as MS

LI_CRUISER = MS('Крейсер Либерти', 'Liberty Cruiser')
RH_CRUISER = MS('Крейсер Рейнланда', 'Rheinland Cruiser')
KU_DESTROYER = MS('Эсминец Кусари', 'Kusari Destroyer')
BR_DESTROYER = MS('Эсминец Бретонии', 'Bretonia Destroyer')
RH_GUNBOAT = MS('Канонерка Рейнланда', 'Rheinland Gunboat')
KU_GUNBOAT = MS('Канонерка Кусари', 'Kusari Gunboat')
BR_GUNBOAT = MS('Канонерка Бретонии', 'Bretonia Gunboat')
NO_BATTLESHIP = MS('Линкор Кочевников', 'Nomad Battleship')
NO_KERNEL = MS('Номадское зерно', 'Nomad Kernel')
MUSASHI = MS('Линкор Мусаси', 'Battleship Musashi')
MISSOURI = MS('Линкор Миссури', 'Battleship Missouri')
OSIRIS = MS('Линкор Осирис', 'Battleship Osiris')
ARMORED = MS('Бронированный транспорт', 'Armored Transport')
KRIEG = MS('Крыг', "Krieg")
WPLATFORM = MS('Орудийная платформа', 'Weapons platform')
GENERATOR = MS('Генератор', 'Generator')
ASTEROID = MS('Астероид', 'Asteroid')
TUNNEL_LOCK = MS('Перегородка туннеля', 'Tunnel lock')