
[Ship]
{{ bdr.root }}
msg_id_prefix = gcs_refer_shiparch_Bred
mission_property = can_use_med_moors
LODranges = 0, 5000, 10000, 25000
type = CRUISER
DA_archetype = ships\bretonia\br{{ prefix }}_destroyer\br{{ prefix }}_destroyer.cmp
material_library = ships\bretonia\br{{ prefix }}_capships.mat
material_library = fx\envmapbasic.mat
envmap_material = envmapship
linear_drag = 1.000000
mass = 500.000000
hold_size = 10
explosion_arch = explosion_br_destroyer
fuse = br_destroyer_fuse, 1.000000, 1
steering_torque = 20000000.000000, 20000000.000000, 20000000.000000
angular_drag = 132000000.000000, 132000000.000000, 132000000.000000
rotation_inertia = 40000000.000000, 40000000.000000, 40000000.000000
nudge_force = 360000.000000
HP_bay_surface = HpBayDoor01
HP_bay_external = HpBayDoor02
HP_tractor_source = HpTractor_Source
num_exhaust_nozzles = 2
max_bank_angle = 5 ;35
camera_offset = 30, 125
camera_angular_acceleration = 0.050000
camera_horizontal_turn_angle = 20
camera_vertical_turn_up_angle = 5
camera_vertical_turn_down_angle = 20
camera_turn_look_ahead_slerp_amount = 1.000000
cockpit = cockpits\bretonia\br_destroyer.ini
nanobot_limit = 0 ; = 0
shield_battery_limit = 0 ; = 0
hp_type = hp_thruster, HpThruster01
hp_type = hp_turret_special_2, HpTurret_B3_01, HpTurret_B3_02
hp_type = hp_turret_special_4, HpTurret_B1_01, HpTurret_B2_02, HpTurret_B2_01

[CollisionGroup]
obj = Br_frnt_bdy_lod1
separable = true
parent_impulse = 60.000000
child_impulse = 600.000000
debris_type = cap_ship_piece
mass = 201.000000
fuse = br_destroyer_fuse, 0.000000, 1
hit_pts = 5000000
root_health_proxy = true

[CollisionGroup]
obj = Br_frnt_bdy_top_lod1
separable = true
parent_impulse = 60.000000
child_impulse = 10.000000
debris_type = cap_ship_piece
mass = 201.000000
;;;;fuse = br_destroyer_fuse, 0.000000, 1
dmg_hp = DpFrnt_bdy_top
dmg_obj = b{{ prefix }}_destroyer_body_cap
hit_pts = 5000000
root_health_proxy = true

[CollisionGroup]
obj = Br_wpn_platform_lod1
separable = true
parent_impulse = 60.000000
child_impulse = 10.000000
debris_type = debris_vanish
mass = 201.000000
separation_explosion = explosion_br
dmg_obj = b{{ prefix }}_destroyer_wplat_cap
dmg_hp = DpWpn_platform
{{ bdr.platform('Br_wpn_platform_lod1', 'DpWpn_platform') }}

[CollisionGroup]
obj = br_cntrl_twr_lod1
separable = true
parent_impulse = 60.000000
child_impulse = 10.000000
debris_type = debris_vanish
mass = 201.000000
dmg_obj = b{{ prefix }}_destroyer_tower_cap
dmg_hp = DpCntrltwr
{{ bdr.control_tower('br_cntrl_twr_lod1', 'DpCntrltwr') }}

[CollisionGroup]
obj = br_port_eng_lod1
separable = true
parent_impulse = 60.000000
child_impulse = 10.000000
debris_type = debris_vanish
mass = 201.000000
separation_explosion = explosion_br
dmg_obj = b{{ prefix }}_destroyer_port_eng_cap
dmg_hp = DpPortengine
{{ bdr.eng1('br_port_eng_lod1', 'DpPortengine') }}

[CollisionGroup]
obj = br_star_eng_lod1
separable = true
parent_impulse = 60.000000
child_impulse = 10.000000
debris_type = debris_vanish
mass = 201.000000
separation_explosion = explosion_br
dmg_obj = b{{ prefix }}_destroyer_starboard_eng_cap
dmg_hp = DpStarboardengine
{{ bdr.eng2('br_star_eng_lod1', 'DpStarboardengine') }}
