
[Ship]
{{ bgb.root }}
LODranges = 0, 5000, 10000, 25000
msg_id_prefix = gcs_refer_shiparch_Breg
mission_property = can_use_med_moors
type = GUNBOAT
DA_archetype = ships\bretonia\br{{ prefix }}_gunship\br{{ prefix }}_gunship.cmp
material_library = ships\bretonia\br{{ prefix }}_capships.mat
material_library = fx\envmapbasic.mat
envmap_material = envmapship
linear_drag = 1.000000
mass = 1000.000000
hold_size = 10
;;explosion_arch = explosion_empty ;;;explosion_br_gship
explosion_arch = explosion_br_gship
fuse = br_gunship_fuse, 0.000000, 1
steering_torque = 60000000.000000, 60000000.000000, 60000000.000000
angular_drag = 120000000.000000, 120000000.000000, 120000000.000000
rotation_inertia = 16800000.000000, 16800000.000000, 16800000.000000
nudge_force = 150000.000000
HP_bay_surface = HpBayDoor01
HP_bay_external = HpBayDoor02
HP_tractor_source = HpTractor_Source
num_exhaust_nozzles = 2
max_bank_angle = 1 ;15
camera_offset = 40, 100
camera_angular_acceleration = 0.035000
camera_horizontal_turn_angle = 20
camera_vertical_turn_up_angle = 5
camera_vertical_turn_down_angle = 20
camera_turn_look_ahead_slerp_amount = 1.000000
cockpit = cockpits\bretonia\br_gunboat.ini
nanobot_limit = 0 ; = 0
shield_battery_limit = 0 ; = 0
;hp_type = hp_thruster, HpEngine01, HpEngine02
hp_type = hp_turret_special_1, HpTurret_B4_01
hp_type = hp_turret_special_2, HpTurret_B3_02, HpTurret_B3_03
hp_type = hp_turret_special_5, HpTurret_B3_01



[CollisionGroup]
obj = br_cntrl_twr_lod1
separable = true
debris_type = debris_vanish
parent_impulse = 500.000000
child_impulse = 10.000000
mass = 200.000000
dmg_obj = b{{ prefix }}_gunship_tower_cap
dmg_hp = DpCntrltwr
{{ bgb.control_tower('br_cntrl_twr_lod1', 'DpCntrltwr') }}


[CollisionGroup]
obj = br_tail_lod1
separable = true
parent_impulse = 500.000000
child_impulse = 10.000000
debris_type = cap_ship_piece2
mass = 200.000000
dmg_obj = b{{ prefix }}_gunship_tail_cap
dmg_hp = DpTail
{{ bgb.tail('br_tail_lod1', 'DpTail') }}
type = Tail

[CollisionGroup]
obj = br_port_eng_lod1
separable = true
parent_impulse = 500.000000
child_impulse = 10.000000
debris_type = debris_vanish
mass = 200.000000
dmg_obj = b{{ prefix }}_gunship_port_eng_cap
dmg_hp = DpPortengine
{{ bgb.eng1('br_port_eng_lod1', 'DpPortengine') }}
type = Port_Engine

[CollisionGroup]
obj = br_star_eng_lod1
separable = true
parent_impulse = 500.000000
child_impulse = 10.000000
debris_type = debris_vanish
mass = 200.000000
dmg_obj = b{{ prefix }}_gunship_starboard_eng_cap
dmg_hp = DpStarboardengine
{{ bgb.eng2('br_star_eng_lod1', 'DpStarboardengine') }}
type = Starboard_Engine

[CollisionGroup]
obj = br_port_wing_lod1
separable = true
parent_impulse = 0
child_impulse = 2500.000000
debris_type = cap_ship_piece2
mass = 200.000000

dmg_hp = DpPortwing
dmg_obj = b{{ prefix }}_gunship_port_wing1_cap
group_dmg_hp = DpPortwing1
group_dmg_obj = b{{ prefix }}_gunship_port_wing_cap
{{ bgb.wing1('br_port_wing_lod1', 'DpPortwing') }}
type = Port_Wing

[CollisionGroup]
obj = br_star_wing_lod1
separable = true
parent_impulse = 0
child_impulse = 2500.000000
debris_type = cap_ship_piece2
mass = 200.000000

dmg_hp = DpStarboardwing
dmg_obj = b{{ prefix }}_gunship_starboard_wing1_cap
group_dmg_hp = DpStarboardwing1
group_dmg_obj = b{{ prefix }}_gunship_starboard_wing_cap
{{ bgb.wing2('br_star_wing_lod1', 'DpStarboardwing') }}
type = Starboard_Wing