
[Ship]
{{ kdr.root }}
LODranges = 0, 1000, 5000, 10000, 25000
msg_id_prefix = gcs_refer_shiparch_Kusd
mission_property = can_use_med_moors
type = CRUISER
DA_archetype = ships\kusari\ku{{ prefix }}_destroyer\ku{{ prefix }}_destroyer.cmp
material_library = ships\kusari\ku{{ prefix }}_capships.mat
material_library = fx\envmapbasic.mat
envmap_material = envmapship
linear_drag = 1.000000
mass = 5000.000000
hold_size = 5
explosion_arch = explosion_ku_destroyer
fuse = ku_destroyer_body_fuse, 0.000000, 1
steering_torque = 20000000.000000, 20000000.000000, 20000000.000000
angular_drag = 132000000.000000, 132000000.000000, 132000000.000000
rotation_inertia = 6600000.000000, 40000000.000000, 40000000.000000
nudge_force = 300000.000000
HP_bay_surface = HpBayDoor01
HP_bay_external = HpBayDoor02
HP_tractor_source = HpTractor_Source
num_exhaust_nozzles = 3
max_bank_angle = 20
camera_offset = 23, 80
camera_angular_acceleration = 0.050000
camera_horizontal_turn_angle = 10
camera_vertical_turn_up_angle = 5
camera_vertical_turn_down_angle = 5
camera_turn_look_ahead_slerp_amount = 1.000000
cockpit = cockpits\kusari\ku_destroyer.ini
nanobot_limit = 0 ; = 0
shield_battery_limit = 0 ; = 0

hp_type = hp_turret_special_2, HpTurret_K2_02, HpTurret_K2_03, HpTurret_K2_01, HpTurret_K2_04, HpTurret_K2_05
hp_type = hp_turret_special_4, HpTurret_K1_01, HpTurret_K1_02

[CollisionGroup]
obj = ku_front_lod1
mass = 200.000000
separable = true
parent_impulse = 0
child_impulse = 500.000000
;group_dmg_hp = DpMain
;group_dmg_obj = ku{{ prefix }}_destroyer_dmg_body_cap
dmg_hp = DpRoot
dmg_obj = ku{{ prefix }}_destroyer_dmg_body_cap
debris_type = cap_ship_piece2
{{ kdr.front('ku_front_lod1', 'DpFront2') }}

[CollisionGroup]
obj = ku_cntrltwr_lod1
separable = true
parent_impulse = 60.000000
child_impulse = 30.000000
dmg_hp = DpCntrltwr
dmg_obj = ku{{ prefix }}_destroyer_dmg_tower_cap
debris_type = debris_vanish
mass = 20.000000
{{ kdr.control_tower('ku_cntrltwr_lod1', 'DpCntrltwr') }}

[CollisionGroup]
obj = ku_eng01_lod1
separable = true
parent_impulse = 60.000000
child_impulse = 30.000000
dmg_hp = DpEng01
dmg_obj = ku{{ prefix }}_destroyer_dmg_top_engine_cap
debris_type = debris_vanish
mass = 20.000000
{{ kdr.eng1('ku_eng01_lod1', 'DpEng01') }}

[CollisionGroup]
obj = ku_eng02_lod1
separable = true
parent_impulse = 60.000000
child_impulse = 30.000000
dmg_hp = DpEng02
dmg_obj = ku{{ prefix }}_destroyer_dmg_mid_engine_cap
debris_type = debris_vanish
mass = 20.000000
{{ kdr.eng2('ku_eng02_lod1', 'DpEng02') }}

[CollisionGroup]
obj = ku_eng03_lod1
separable = true
parent_impulse = 60.000000
child_impulse = 30.000000
dmg_hp = DpEng03
dmg_obj = ku{{ prefix }}_destroyer_dmg_low_engine_cap
debris_type = debris_vanish
mass = 20.000000
{{ kdr.eng3('ku_eng03_lod1', 'DpEng03') }}
