
[Ship]
{{ lcr.root }}
LODranges = 0, 1000, 5000, 15000, 25000
msg_id_prefix = gcs_refer_shiparch_Libc
mission_property = can_use_med_moors
type = CRUISER
DA_archetype = ships\liberty\li{{ prefix }}_cruiser\li{{ prefix }}_cruiser.cmp
material_library = ships\liberty\li{{ prefix }}_capships.mat
material_library = fx\envmapbasic.mat
envmap_material = envmapship
linear_drag = 1.000000
mass = 5000.000000
hold_size = 5
explosion_arch = explosion_li_cruiser
fuse = li_cruiser_body_fuse, 0.000000, 1
steering_torque = 20000000.000000, 20000000.000000, 20000000.000000
angular_drag = 132000000.000000, 132000000.000000, 132000000.000000
rotation_inertia = 40000000.000000, 40000000.000000, 40000000.000000
;surface_hit_effects = 1, gf_big_hit01
nudge_force = 300000.000000
HP_bay_surface = HpBayDoor01
HP_bay_external = HpBayDoor02
HP_tractor_source = HpTractor_Source
num_exhaust_nozzles = 4
camera_offset = 30, 125
camera_angular_acceleration = 0.050000
camera_horizontal_turn_angle = 10
camera_vertical_turn_up_angle = 5
camera_vertical_turn_down_angle = 5
camera_turn_look_ahead_slerp_amount = 1.000000
cockpit = cockpits\liberty\li_cruiser.ini
nanobot_limit = 0 ; = 0
shield_battery_limit = 0 ; = 0
hp_type = hp_turret_special_1, HpTurret_L5_01, HpTurret_L5_02, HpTurret_L5_03, HpTurret_L5_04, HpTurret_L5_05, HpTurret_L5_06, HpTurret_L5_07
hp_type = hp_turret_special_10, HpWeapon02

[CollisionGroup]
obj = Li_cruiser_cntrltwr_lod1
separable = true
debris_type = debris_vanish
separation_explosion = explosion_li
fuse = lcr_tower_fuse, 0.500000, 1
dmg_obj = l{{ prefix }}_cruiser_tower_cap
dmg_hp = DpCntrltwr
mass = 100.000000
parent_impulse = 10.000000
child_impulse = 10.000000
{{ lcr.control_tower('Li_cruiser_cntrltwr_lod1', 'DpCntrltwr') }}

[CollisionGroup]
obj = Li_cruiser_nose_lod1
separable = true
debris_type = cap_ship_piece
;;fuse = li_cruiser_body_fuse, 0.000000, 1
parent_impulse = 10.000000
child_impulse = 250.000000
dmg_hp = DpRoot
dmg_obj = l{{ prefix }}_cruiser_front2_cap
group_dmg_hp = DpFront
group_dmg_obj = l{{ prefix }}_cruiser_front_cap
mass = 10.000000
{{ lcr.nose('Li_cruiser_nose_lod1', 'DpFront2', hit_pts_multipler=2) }}

[CollisionGroup]
obj = Li_cruiser_engine01_lod1
separable = true
debris_type = cap_ship_piece
;fuse = li_cruiser_engine1_fuse, 0.000000, 1
;fuse = lcr_eng01_fuse, 0.500000, 1
separation_explosion = explosion_li
dmg_obj = l{{ prefix }}_cruiser_engine01_cap
dmg_hp = DpEngine01
group_dmg_hp = DpEng01
group_dmg_obj = l{{ prefix }}_cruiser_engine01_cap
mass = 100.000000
parent_impulse = 10.000000
child_impulse = 1000.000000
{{ lcr.eng1('Li_cruiser_engine01_lod1', 'DpEngine01') }}

[CollisionGroup]
obj = Li_cruiser_engine02_lod1
separable = true
debris_type = cap_ship_piece
;fuse = li_cruiser_engine2_fuse, 0.000000, 1
;fuse = lcr_eng02_fuse, 0.500000, 1
dmg_obj = l{{ prefix }}_cruiser_engine02_cap
dmg_hp = DpEngine02
mass = 100.000000
parent_impulse = 10.000000
child_impulse = 3000.000000
{{ lcr.eng2('Li_cruiser_engine02_lod1', 'DpEngine02') }}

[CollisionGroup]
obj = Li_cruiser_engine03_lod1
separable = true
debris_type = cap_ship_piece
;fuse = li_cruiser_engine3_fuse, 0.000000, 1
;fuse = lcr_eng03_fuse, 0.500000, 1
dmg_obj = l{{ prefix }}_cruiser_engine03_cap
dmg_hp = DpEngine03
mass = 100.000000
parent_impulse = 10.000000
child_impulse = 9000.000000
{{ lcr.eng3('Li_cruiser_engine03_lod1', 'DpEngine03') }}

[CollisionGroup]
obj = Li_cruiser_engine04_lod1
separable = true
debris_type = cap_ship_piece
;fuse = li_cruiser_engine4_fuse, 0.000000, 1
;fuse = lcr_eng04_fuse, 0.500000, 1
dmg_obj = l{{ prefix }}_cruiser_engine04_cap
dmg_hp = DpEngine04
mass = 100.000000
parent_impulse = 10.000000
child_impulse = 5000.000000
{{ lcr.eng4('Li_cruiser_engine04_lod1', 'DpEngine04') }}