
[Ship]
ids_name = 237043
ids_info = 66584
nickname = or{{ prefix }}_osiris
LODranges = 0, 3000, 6000, 50000
msg_id_prefix = gcs_refer_shiparch_Ordb
mission_property = can_use_med_moors
type = FIGHTER
DA_archetype = ships\order\or{{ prefix }}_osiris\or{{ prefix }}_osiris.cmp
material_library = Ships\order\or{{ prefix }}_ships.mat
material_library = fx\envmapbasic.mat
envmap_material = envmapship
explosion_arch = explosion_li_dread
fuse = o_osiris_fuse, 0.500000, 1
fuse = or_osiris_burning_fuse01, 0.000000, 5000000
fuse = or_osiris_burning_fuse02, 0.000000, 2000000
fuse = or_osiris_burning_fuse03, 0.000000, 1000000
steering_torque = 250000000.000000, 250000000.000000, 250000000.000000
rotation_inertia = 200000000.000000, 4000000000, 4000000000 ; 25806999552.000000, 638700032.000000
angular_drag = 4000000000.000000, 4000000000.000000, 4000000000.000000
linear_drag = 2.000000
nudge_force = 360000.000000
mass = 100000.000000
hold_size = 5
bay_door_anim = Sc_open baydoor
bay_doors_open_snd = hanger_doors_opening
bay_doors_close_snd = hanger_doors_closing
HP_bay_surface = HpBayDoor01
HP_bay_external = HpBayDoor02
HP_tractor_source = HpTractor_Source
num_exhaust_nozzles = 1
hit_pts = 10000000
camera_offset = 50, 300
camera_angular_acceleration = 0.050000
camera_horizontal_turn_angle = 10
camera_vertical_turn_up_angle = 5
camera_vertical_turn_down_angle = 5
camera_turn_look_ahead_slerp_amount = 1.000000
cockpit = cockpits\liberty\li_dread.ini
nanobot_limit = 0 ; = 0
shield_battery_limit = 0 ; = 0
shield_link = l_fighter_shield01, HpMount, HpShield01
hp_type = hp_freighter_shield_special_1, HpShield01
hp_type = hp_turret_special_2, HpTurret_O3_01, HpTurret_O3_02, HpTurret_O4_02, HpTurret_O4_03
hp_type = hp_turret_special_3, HpTurret_O4_01, HpTurret_O4_04
hp_type = hp_turret_special_4, HpTurret_O1_01, HpTurret_O2_01

[CollisionGroup]
obj = Leaf01_d1_lod1
parent_impulse = 10.000000
child_impulse = 30.000000
separable = true
debris_type = cap_ship_piece
mass = 5.000000
;fuse = o_osiris_fuse, 1.000000, 1
separation_explosion = explosion_li
hit_pts = 200000
root_health_proxy = true

[CollisionGroup]
obj = Leaf02_d1_lod1
separable = true
debris_type = cap_ship_piece
mass = 5.000000
parent_impulse = 10.000000
child_impulse = 30.000000
;fuse = o_osiris_fuse, 1.000000, 1
separation_explosion = explosion_li
hit_pts = 200000
root_health_proxy = true

[CollisionGroup]
obj = Leaf03_d1_lod1
separable = true
debris_type = cap_ship_piece
mass = 5.000000
parent_impulse = 10.000000
child_impulse = 30.000000
;fuse = o_osiris_fuse, 1.000000, 1
separation_explosion = explosion_li
hit_pts = 200000
root_health_proxy = true

[CollisionGroup]
obj = Leaf04_d1_lod1
separable = true
debris_type = cap_ship_piece
mass = 5.000000
parent_impulse = 10.000000
child_impulse = 30.000000
;fuse = o_osiris_fuse, 1.000000, 1
separation_explosion = explosion_li
hit_pts = 200000
root_health_proxy = true

[CollisionGroup]
obj = Leaf05_d1_lod1
separable = true
debris_type = cap_ship_piece
mass = 5.000000
parent_impulse = 10.000000
child_impulse = 30.000000
;fuse = o_osiris_fuse, 1.000000, 1
separation_explosion = explosion_li
hit_pts = 200000
root_health_proxy = true

[CollisionGroup]
obj = Leaf06_d1_lod1
separable = true
debris_type = cap_ship_piece
mass = 5.000000
parent_impulse = 10.000000
child_impulse = 30.000000
;fuse = o_osiris_fuse, 1.000000, 1
separation_explosion = explosion_li
hit_pts = 200000
root_health_proxy = true

[CollisionGroup]
obj = Leaf07_d1_lod1
separable = true
debris_type = cap_ship_piece
mass = 5.000000
parent_impulse = 10.000000
child_impulse = 30.000000
;fuse = o_osiris_fuse, 1.000000, 1
separation_explosion = explosion_li
hit_pts = 200000
root_health_proxy = true

[CollisionGroup]
obj = Leaf08_d1_lod1
separable = true
debris_type = cap_ship_piece
mass = 5.000000
parent_impulse = 10.000000
child_impulse = 30.000000
;fuse = o_osiris_fuse, 1.000000, 1
separation_explosion = explosion_li
hit_pts = 200000
root_health_proxy = true

[CollisionGroup]
obj = osiris_nose_lod1
separable = true
debris_type = cap_ship_piece
mass = 10.000000
parent_impulse = 10.000000
child_impulse = 80.000000
fuse = o_osiris_fuse, 0.000000, 1
fuse = or_osiris_burning_fuse01, 0.000000, 17325
group_dmg_hp = DpNose
group_dmg_obj = or{{ prefix }}_osiris_head_dmg_cap
hit_pts = 25000000
root_health_proxy = true

[CollisionGroup]
obj = osiris_interior_lod1
separable = true
debris_type = debris_vanish
mass = 10.000000
parent_impulse = 10.000000
child_impulse = 50.000000
fuse = o_osiris_fuse, 0.000000, 1
fuse = or_osiris_burning_fuse01, 0.000000, 5000000
separation_explosion = explosion_li
group_dmg_hp = DpNose
group_dmg_obj = or{{ prefix }}_osiris_head_dmg_cap
hit_pts = 10000000
root_health_proxy = true

[CollisionGroup]
obj = osiris_front_lod1
separable = true
debris_type = debris_vanish
mass = 10.000000
parent_impulse = 10.000000
child_impulse = 10.000000
fuse = o_osiris_fuse, 0.250000, 1
fuse = or_osiris_burning_fuse02, 0.000000, 2000000
dmg_hp = DpFront
dmg_obj = or{{ prefix }}_osiris_neck_dmg_cap
hit_pts = 20000000
root_health_proxy = true

[CollisionGroup]
obj = osiris_rear_lod1
separable = true
debris_type = debris_vanish
mass = 10.000000
parent_impulse = 10.000000
child_impulse = 10.000000
fuse = o_osiris_fuse, 0.750000, 1
fuse = or_osiris_burning_fuse04, 0.000000, 2000000
dmg_hp = DpRear
dmg_obj = or{{ prefix }}_osiris_butt_dmg_cap
hit_pts = 20000000
root_health_proxy = true

[CollisionGroup]
obj = osiris_cntrltwr_lod1
separable = true
debris_type = debris_vanish
mass = 10.000000
parent_impulse = 10.000000
child_impulse = 10.000000
dmg_hp = DpCntrltwr
dmg_obj = or{{ prefix }}_osiris_tower_cap
;fuse = o_osiris_fuse, 0.500000, 1
;fuse = or_osiris_burning_fuse03, 0.000000, 17325
separation_explosion = explosion_li
hit_pts = 500000
root_health_proxy = true

[CollisionGroup]
obj = osiris_shield_generator_lod1
separable = true
debris_type = debris_vanish
mass = 10.000000
parent_impulse = 10.000000
child_impulse = 10.000000
;fuse = o_osiris_fuse, 0.500000, 1
;fuse = or_osiris_burning_fuse02, 0.000000, 17325
dmg_hp = DpShieldgen
dmg_obj = or{{ prefix }}_osiris_shield_gen_cap
separation_explosion = explosion_li
hit_pts = 500000
root_health_proxy = true

[CollisionGroup]
obj = osiris_reactor_lod1
separable = true
debris_type = debris_vanish
mass = 10.000000
parent_impulse = 10.000000
child_impulse = 10.000000
fuse = o_osiris_fuse, 1.000000, 1
fuse = or_osiris_burning_fuse04, 0.000000, 2000000
hit_pts = 20000000
root_health_proxy = true

[CollisionGroup]
obj = osiris_reactor_core_lod1
separable = true
debris_type = cap_ship_piece
mass = 10.000000
parent_impulse = 10.000000
child_impulse = 300.000000
;fuse = o_osiris_fuse, 1.000000, 1
;fuse = or_osiris_burning_fuse04, 0.000000, 17325
group_dmg_hp = DpEngine
group_dmg_obj = or{{ prefix }}_osiris_engine_cap
separation_explosion = explosion_li
hit_pts = 2000000
root_health_proxy = true

[CollisionGroup]
obj = osiris_engine_lod1
separable = true
debris_type = debris_vanish
mass = 10.000000
parent_impulse = 10.000000
child_impulse = 50.000000
;fuse = o_osiris_fuse, 1.000000, 1
;fuse = or_osiris_burning_fuse04, 0.000000, 17325
separation_explosion = explosion_li
hit_pts = 1000000
root_health_proxy = true
