import text.info_commodity_ru as RU
import text.info_commodity_en as EN
from text.strings import MultiString as MS


EXPL_MAPS = MS(RU.EXPL_MAPS, EN.EXPL_MAPS)

EXPL_NEUTRON = MS(RU.EXPL_NEUTRON, EN.EXPL_NEUTRON)

EXPL_BH = MS(RU.EXPL_BH, EN.EXPL_BH)

EXPL_RESEARCHS = MS(RU.EXPL_RESEARCHS, EN.EXPL_RESEARCHS)

ARTIFACTS = MS(RU.ARTIFACTS, EN.ARTIFACTS)

ALIEN_ORGANISMS = MS(RU.ALIEN_ORGANISMS, EN.ALIEN_ORGANISMS)

NOMAD_GENERATOR = MS(RU.NOMAD_GENERATOR, EN.NOMAD_GENERATOR)

TERRAFORM_MINERALS = MS(RU.TERRAFORM_MINERALS, EN.TERRAFORM_MINERALS)

TERRAFORM_GASES = MS(RU.TERRAFORM_GASES, EN.TERRAFORM_GASES)

LASERBEAM_COMPONENTS = MS(RU.LASERBEAM_COMPONENTS, EN.LASERBEAM_COMPONENTS)

WATER = MS(RU.WATER, EN.WATER)

OXYGEN = MS(RU.OXYGEN, EN.OXYGEN)

SYNTS_FOOD = MS(RU.SYNTS_FOOD, EN.SYNTS_FOOD)

CONSUMER_GOODS = MS(RU.CONSUMER_GOODS, EN.CONSUMER_GOODS)

MEDS = MS(RU.MEDS, EN.MEDS)

LIGHT_ARMS = MS(RU.LIGHT_ARMS, EN.LIGHT_ARMS)

TOXIC = MS(RU.TOXIC, EN.TOXIC)

METAL = MS(RU.METAL, EN.METAL)

SHIP_PANELS = MS(RU.SHIP_PANELS, EN.SHIP_PANELS)

POWER_SOLAR_EMPTY = MS(RU.POWER_SOLAR_EMPTY, EN.POWER_SOLAR_EMPTY)

POWER_SOLAR = MS(RU.POWER_SOLAR, EN.POWER_SOLAR)

ALLOY_BASIC = MS(RU.ALLOY_BASIC, EN.ALLOY_BASIC)

GAS_BALOONS = MS(RU.GAS_BALOONS, EN.GAS_BALOONS)

GAS_LIQUID = MS(RU.GAS_LIQUID, EN.GAS_LIQUID)

GAS_FUEL = MS(RU.GAS_FUEL, EN.GAS_FUEL)

WATER_EXTRA = MS(RU.WATER_EXTRA, EN.WATER_EXTRA)

DIAMONDS = MS(RU.DIAMONDS, EN.DIAMONDS)

LUXURY_DIAMONDS = MS(RU.LUXURY_DIAMONDS, EN.LUXURY_DIAMONDS)

NIOBIUM = MS(RU.NIOBIUM, EN.NIOBIUM)

PROD_MACHINES = MS(RU.PROD_MACHINES, EN.PROD_MACHINES)

STATION_PANELS = MS(RU.STATION_PANELS, EN.STATION_PANELS)

ALLOY_HEAVY = MS(RU.ALLOY_HEAVY, EN.ALLOY_HEAVY)

ROID_MINER_PARTS = MS(RU.ROID_MINER_PARTS, EN.ROID_MINER_PARTS)

BERILIUM = MS(RU.BERILIUM, EN.BERILIUM)

NICOLLUM = MS(RU.NICOLLUM, EN.NICOLLUM)

LUXURY_GOODS = MS(RU.LUXURY_GOODS, EN.LUXURY_GOODS)

TLR_PARTS = MS(RU.TLR_PARTS, EN.TLR_PARTS)

ENGINE_COMPONENTS = MS(RU.ENGINE_COMPONENTS, EN.ENGINE_COMPONENTS)

JG_COMPONENTS = MS(RU.JG_COMPONENTS, EN.JG_COMPONENTS)

ALLOY_TEMPERATURE = MS(RU.ALLOY_TEMPERATURE, EN.ALLOY_TEMPERATURE)

MINING_EQUIP = MS(RU.MINING_EQUIP, EN.MINING_EQUIP)

URANIUM = MS(RU.URANIUM, EN.URANIUM)

PLUMBUM = MS(RU.PLUMBUM, EN.PLUMBUM)

REACTORS = MS(RU.REACTORS, EN.REACTORS)

MOX_FUEL = MS(RU.MOX_FUEL, EN.MOX_FUEL)

MUNITIONS = MS(RU.MUNITIONS, EN.MUNITIONS)


LUXURY_FOOD = MS(RU.LUXURY_FOOD, EN.LUXURY_FOOD)


ALLOY_RADIATION = MS(RU.ALLOY_RADIATION, EN.ALLOY_RADIATION)

GREENHOUSE_PARTS = MS(RU.GREENHOUSE_PARTS, EN.GREENHOUSE_PARTS)

GOLD = MS(RU.GOLD, EN.GOLD)

SILVER = MS(RU.SILVER, EN.SILVER)

ELECTRONICS = MS(RU.ELECTRONICS, EN.ELECTRONICS)

LUXURY_GOLD = MS(RU.LUXURY_GOLD, EN.LUXURY_GOLD)

ALLOY_CONDUCTOR = MS(RU.ALLOY_CONDUCTOR, EN.ALLOY_CONDUCTOR)

GASMINER_PARTS = MS(RU.GASMINER_PARTS, EN.GASMINER_PARTS)

RED_ROID = MS(RU.RED_ROID, EN.RED_ROID)

ALLOY_RED = MS(RU.ALLOY_RED, EN.ALLOY_RED)

SPECTRUM_ROID = MS(RU.SPECTRUM_ROID, EN.SPECTRUM_ROID)

PIRATE_GOODS = MS(RU.PIRATE_GOODS, EN.PIRATE_GOODS)

LIGHT_DRUGS = MS(RU.LIGHT_DRUGS, EN.LIGHT_DRUGS)

CARDAMINE = MS(RU.CARDAMINE, EN.CARDAMINE)

PIRATE_MEDS = MS(RU.PIRATE_MEDS, EN.PIRATE_MEDS)

PRISONERS = MS(RU.PRISONERS, EN.PRISONERS)

SOLAR_PLANT_PARTS = MS(RU.SOLAR_PLANT_PARTS, EN.SOLAR_PLANT_PARTS)

RESEARCH_EQUIP = MS(RU.RESEARCH_EQUIP, EN.RESEARCH_EQUIP)

SMELTER_PARTS = MS(RU.SMELTER_PARTS, EN.SMELTER_PARTS)

POLYMERS = MS(RU.POLYMERS, EN.POLYMERS)

DEFENCE_SYSTEMS = MS(RU.DEFENCE_SYSTEMS, EN.DEFENCE_SYSTEMS)

OPTICAL_CHIPS = MS(RU.OPTICAL_CHIPS, EN.OPTICAL_CHIPS)
