import text.info_commodity_ru as RU
from text.strings import MultiString as MS


EXPL_MAPS = MS(RU.EXPL_MAPS, '')

EXPL_NEUTRON = MS(RU.EXPL_NEUTRON, '')

EXPL_BH = MS(RU.EXPL_BH, '')

EXPL_RESEARCHS = MS(RU.EXPL_RESEARCHS, '')

ARTIFACTS = MS(RU.ARTIFACTS, '')

ALIEN_ORGANISMS = MS(RU.ALIEN_ORGANISMS, '')

NOMAD_GENERATOR = MS(RU.NOMAD_GENERATOR, '')

TERRAFORM_MINERALS = MS(RU.TERRAFORM_MINERALS, '')

TERRAFORM_GASES = MS(RU.TERRAFORM_GASES, '')

LASERBEAM_COMPONENTS = MS(RU.LASERBEAM_COMPONENTS, '')

WATER = MS(RU.WATER, '')

OXYGEN = MS(RU.OXYGEN, '')

SYNTS_FOOD = MS(RU.SYNTS_FOOD, '')

CONSUMER_GOODS = MS(RU.CONSUMER_GOODS, '')

MEDS = MS(RU.MEDS, '')

LIGHT_ARMS = MS(RU.LIGHT_ARMS, '')

TOXIC = MS(RU.TOXIC, '')

METAL = MS(RU.METAL, '')

POWER_SOLAR = MS(RU.POWER_SOLAR, '')

ALLOY_BASIC = MS(RU.ALLOY_BASIC, '')

GAS_BALOONS = MS(RU.GAS_BALOONS, '')

GAS_FUEL = MS(RU.GAS_FUEL, '')

WATER_EXTRA = MS(RU.WATER_EXTRA, '')

DIAMONDS = MS(RU.DIAMONDS, '')

LUXURY_DIAMONDS = MS(RU.LUXURY_DIAMONDS, '')

NIOBIUM = MS(RU.NIOBIUM, '')

PROD_MACHINES = MS(RU.PROD_MACHINES, '')

STATION_PANELS = MS(RU.STATION_PANELS, '')

ALLOY_HEAVY = MS(RU.ALLOY_HEAVY, '')

ROID_MINER_PARTS = MS(RU.ROID_MINER_PARTS, '')

BERILIUM = MS(RU.BERILIUM, '')

NICOLLUM = MS(RU.NICOLLUM, '')

LUXURY_GOODS = MS(RU.LUXURY_GOODS, '')

TLR_PARTS = MS(RU.TLR_PARTS, '')

ENGINE_COMPONENTS = MS(RU.ENGINE_COMPONENTS, '')

JG_COMPONENTS = MS(RU.JG_COMPONENTS, '')

ALLOY_TEMPERATURE = MS(RU.ALLOY_TEMPERATURE, '')

MINING_EQUIP = MS(RU.MINING_EQUIP, '')

URANIUM = MS(RU.URANIUM, '')

PLUMBUM = MS(RU.PLUMBUM, '')

REACTORS = MS(RU.REACTORS, '')

MOX_FUEL = MS(RU.MOX_FUEL, '')

MUNITIONS = MS(RU.MUNITIONS, '')


LUXURY_FOOD = MS(RU.LUXURY_FOOD, '')


ALLOY_RADIATION = MS(RU.ALLOY_RADIATION, '')

GREENHOUSE_PARTS = MS(RU.GREENHOUSE_PARTS, '')

GOLD = MS(RU.GOLD, '')

SILVER = MS(RU.SILVER, '')

ELECTRONICS = MS(RU.ELECTRONICS, '')

LUXURY_GOLD = MS(RU.LUXURY_GOLD, '')

ALLOY_CONDUCTOR = MS(RU.ALLOY_CONDUCTOR, '')

GASMINER_PARTS = MS(RU.GASMINER_PARTS, '')

RED_ROID = MS(RU.RED_ROID, '')

ALLOY_RED = MS(RU.ALLOY_RED, '')

SPECTRUM_ROID = MS(RU.SPECTRUM_ROID, '')

PIRATE_GOODS = MS(RU.PIRATE_GOODS, '')

LIGHT_DRUGS = MS(RU.LIGHT_DRUGS, '')

CARDAMINE = MS(RU.CARDAMINE, '')

PIRATE_MEDS = MS(RU.PIRATE_MEDS, '')

PRISONERS = MS(RU.PRISONERS, '')
