from story import script
from audio.sound import VoiceLine
from story.actors import Trent, Hatcher, Darcy, Tilton, Brighton, CruiserCaptain, RedLeader, Kaitlyn, King, MajorScrew, Mandrake
from story.cutscenes.story_scenes import m08


class Msn8(object):
    MISSION_INDEX = 8


class Msn8Offer(Msn8, script.CutsceneProps):
    ALIAS = 'offer'
    TITLE = 'Предложение'
    DESCRIPTION = ''
    VOICE_LINES = [
        VoiceLine(40, Brighton, ru="А это мисс Дерси, наша краса и надежда на светлое будущее.", en="Ah, Ms.Darcy - our beauty with brains, and hope for a brighter age."),
        VoiceLine(50, Kaitlyn, ru="А это, если я все правильно поняла, эксперт по Ордену, о котором мне столько рассказывали.", en="And this must the Freelancer. I've heard so much about you."),
        VoiceLine(60, Darcy, ru="Да, это мистер Трент. Трент, это адмирал Брайтон и принцесса Кейтлин.", en="Yes, this is Mister Trent. Trent, this are Admiral Brighton, and the honorable Princess Caitlin."),
        VoiceLine(70, Brighton, ru="И у нас к вам, мистер Трент, чрезвычайно важное дело.", en="We have a matter of the utmost importance to discuss with you, mister Trent."),
        VoiceLine(80, Trent, ru="Шо, опять?", en="Really? Not again."),
        VoiceLine(90, Brighton, ru="Мистер Трент, давайте чуточку серьёзнее. Речь идет о государственной безопасности Бретонии.", en="Mr.Trent, please try not to be flippant. This matter is of fundamental importance to Bretonia."),
        VoiceLine(100, Trent, ru="Я постараюсь.", en="Trying my best."),
        VoiceLine(110, Brighton, ru="У нас для вас, мистер Трент, будет небольшое задание по вашему профилю.", en="We have a mission that requires to your very specific skillset."),
        VoiceLine(120, Trent, ru="Моему профилю?", en="My specific skillset?"),
        VoiceLine(130, Brighton, ru="Орден, мистер Трент, Орден.", en="Order,, Mr.Trent, Order."),
        VoiceLine(140, Trent, ru="А... Аааа...", en="A burger and..."),
        VoiceLine(150, Brighton, ru="Мистер Трент, смею вас заверить, что данная миссия находится на контроле у самых высокопоставленных лиц Бретонии. ", en="Mr.Trent, I must inform you that this mission is being overseen by the very highest ranking officials of Bretonia."),
        VoiceLine(160, Brighton, ru="Одно то, что на встрече с вами присутствует принцесса Кейтлин, должно о многом вам говорить.", en="That her royal highness is in attendance should inform even someone like you of the gravity of this matter, and perhaps hint at the bare modicum of decorum necessitated. We would most appreciate it if you could take this just a little seriously."),
        VoiceLine(170, Trent, ru="Минуй нас пуще всех печалей и барский гнев, и барская любовь...", en="Beware of masters, they / Will cause you trouble any day. / Of all the woes may God deliver us from both. / From their love and their wrath."),
        VoiceLine(180, Brighton, ru="Я не понимаю вашего скептицизма, мистер Трент, будьте чуточку прозорливее", en="We also fail to appreciate your skepticism, and what you appear to believe is humour, Mr.Trent. "),
        VoiceLine(190, Brighton, ru="Вы окажете услугу нам, а мы, при случае, окажем услугу вам.", en="We would ask a favour of you, and in return we offer an opportunity."),
        VoiceLine(200, Trent, ru="Допустим. А в чём задание-то?", en="Okay. Fine. What is the nature of this favour?"),
        VoiceLine(210, Brighton, ru="Вот это уже серьёзный разговор, мистер Трент. Принцесса?", en="Much better, Mr.Trent. Milady, may I?"),
        VoiceLine(215, Kaitlyn, ru="Угу...", en="Please..."),
        VoiceLine(220, Brighton, ru="Мистер Трент, в свое время правительство Бретонии заключило некое соглашение с Орденом.", en="Mr.Trent, quite a while ago the government of Bretonnia entered into an agreement with the Order."),
        VoiceLine(230, Brighton, ru="Оно сводилось к тому, что Бретония, хм…", en="It boiled down to the fact that Bretonia... well..."),
        VoiceLine(235, Brighton, ru="Мистер Трент, а вы слышали о проблеме кочевников? ", en="Mr.Trent, have you heard of the Nomad problem?"),
        VoiceLine(240, Trent, ru="В общем и целом.", en="Yep."),
        VoiceLine(250, Brighton, ru="Отлично. Чуточку осторожности не помешает, вы же меня понимаете?", en="Excellent. A little caution can't hurt, if you know what I mean."),
        VoiceLine(260, Brighton, ru='Так вот, по этому соглашению Бретония отказывалась от своих интересов в секторах так называемого "Наследия Номадов", кочевников то есть. Вы понимаете, о чем я, мистер Трент?', en="Under this agreement, Bretonnia renounced its interests in the sectors of the so-called \"The Nomad Legacy\". that is, the nomads. Are you following, Mr. Trent?"),
        VoiceLine(270, Trent, ru="Чуточку", en="Yep."),
        VoiceLine(280, Brighton, ru="Гхм, хорошо. Взамен Орден обязался ограничить доступ к этим системам для всех. То есть совсем ограничить. Вы меня понимаете, мистер Трент?", en="Hmm, fine. In exchange, the Order agreed to prohibit access to these systems to all parties. Completely."),
        VoiceLine(290, Brighton, ru="И мы наивно полагали, что СБА, как прямой наследник Ордена, будет придерживаться достигнутых договоренностей. И что же мы видим сейчас?", en="In our naivete, we assumed that ASF would adhere to the agreement, as the progeny of the Order. But now..."),
        VoiceLine(300, Trent, ru="Что?...", en="Now... What?..."),
        VoiceLine(310, Brighton, ru="А то, что эти ублюдки из ИРА во всю осваивают Тау-44.", en="They are permitting the bastards from the IRA to colonise Tau-44, and at a prodigious speed."),
        VoiceLine(320, Trent, ru='Вот сволочи. А Ира - это кто?', en="How horrific. What's the IRA by the way?"),
        VoiceLine(330, Brighton, ru='Не "кто" а "что". Группа фанатиков, в том числе религиозных, требующих независимости Ирландии от Британской короны.', en="Not \"what\" but \"who\". They're a group of political, idealogical and religious fanatics, demanding independence for Ireland from the Crown of Bretonia."),
        VoiceLine(340, Trent, ru="Достаточно забавно, учитывая что в секторе Сириуса нет ни Ирландии, ни Британской короны.", en="That's rich, given that there're neither Ireland nor a true monarchy in Sirius sector. Bretonia is a constitutional monarchy."),
        VoiceLine(350, Kaitlyn, ru="Мистер Трент...", en="Mr.Trent..."),
        VoiceLine(360, Trent, ru="А что? Дома Ирландии, насколько я знаю, нет.", en="What? As far as I know, there's no planet or station called Ireland."),
        VoiceLine(370, Kaitlyn, ru="А ирландцы, к сожалению, есть...", en="But there are still Irish people, unfortunately..."),
        VoiceLine(380, Brighton, ru="Теперь вы понимаете, мистер Трент, насколько все это дико?", en="Do you realize now how ridiculous this is, Mr.Trent?"),
        VoiceLine(390, Trent, ru="Допустим. Что требуется от меня?", en="So what do you want me to do?"),
        VoiceLine(400, Brighton, ru="Чуточку помочь нам. В составе оперативного отряда вылететь в Тау-44, и очистить систему от присутствия ИРА.", en="Fly to Tau-44 and purge it of all IRA presence."),
        VoiceLine(410, Brighton, ru="Кроме всего прочего, мы подозреваем что СБА напрямую во всем этом замешано. И здесь нам пригодитесь вы.", en="We also suspect that the ASF is tied up with all of this. And that's where you come in."),
        VoiceLine(420, Trent, ru="В качестве кого? Того, кто ткнет на кого-нибудь пальцем и скажет \"он из СБА\"? Звучит не очень убедительно.", en="Me? How? As someone who points his finger at someone else and says, \"He's from the ASF\"? That doesn't sound too convincing to me."),
        VoiceLine(430, Kaitlyn, ru="Ахх...", en="Uhhh..."),
        VoiceLine(435, Kaitlyn, ru="А пятьдесят тысяч звучат достаточно убедительно? Вы просто примите участие в заплыве, вам не обязательно становиться победителем.", en="Does fifty thousand credits sound convincing? Just to go for a little walk in the park."),
        VoiceLine(440, Trent, ru="Олимпийский принцип? За пятьдесят тысяч? Возможно, я сильно поторопился, сказав, что в секторе Сириуса нет британской короны.", en="A walk in the park? For fifty thousand? Maybe I was too quick to say that there is no Bretonian Crown in Sirius sector."),
        VoiceLine(450, Kaitlyn, ru="И были достаточно умны, чтобы это признать. Непосредственное руководство миссией возложено на адмирала Брайтона, все детали обсудите с ним...", en="Cleverer than he looks. Admiral Brighton will have direct oversight of this operation, please discuss all the details with him."),
        VoiceLine(460, Kaitlyn, ru="Джентльмены...", en="That will be all..."),
        VoiceLine(470, Brighton, ru="Мистер Трент, на орбите планеты находится Принц Уэльский, мой линкор. Стыкуйтесь к нему, все необходимые допуски и разрешения я вам выдам.", en="Trent, my battleship, the Prince of Wales, is orbiting the planet. Dock on it, and I'll transfer all the necessary passes and permits to you."),
        VoiceLine(480, Darcy, ru="Трент, увидимся на Принце Уэльском.", en="Well Trent, see you on the \"Prince of Wales\"."),
    ]


class Msn8Osiris(Msn8, script.CutsceneProps):
    ALIAS = 'osiris'
    TITLE = 'Осирис'
    DESCRIPTION = ''
    VOICE_LINES = [
        VoiceLine(10, Hatcher, ru="Майо... эээ... Простите, генерал Кинг, майор Скрю, Трент доставлен.", en="Majo... uhhm... Sorry, General King, Trent has been delivered."),
        VoiceLine(20, King, ru="Спасибо, мисс Хетчер.", en="Thank you, Miss Hatcher."),
        VoiceLine(30, King, ru="Мистер Трент, я понимаю, что у вас выдались тяжелые... гхм... несколько дней...", en="Mr.Trent, I know, it's been a wild ... ahem... couple of days for you..."),
        VoiceLine(40, Trent, ru="Недель...", en="Weeks..."),
        VoiceLine(50, King, ru="Пусть даже месяцев, но есть некоторые вещи, которые выше нашего морального и физического состояния. И в данный момент очень важно определить местонахождение известного вам тома Протеуса и ключа. ",
                  en="Even were it months, there are some things take precedence over our mental and physical states. Right now, it is absolutely crucial to determine the location of the Proteus Tome and the Key."),
        VoiceLine(60, King, ru="А поэтому, расскажите, пожалуйста, подробно всё, что происходило с вами с момента когда мисс Хетчер приказала вам вместе с отрядом Дельта отправиться в Сигму-17.",
                  en="So, please recount to me in detail everything that's happened to you from the moment Miss Hatcher ordered you to fly to Sigma-19 with Delta Squad till this moment. Spare no details."),
        VoiceLine(70, Trent, ru="Нас перехватили в Большом Омикроне, до сигмы-17 мы так и не добрались.", en="We were intercepted in Omicron Major, didn't make it to Sigma-19."),
        VoiceLine(80, King, ru="Кто перехватил?", en="Who intercepted you?"),
        VoiceLine(90, Trent, ru='Да хрен его знает, какие-то бравые ребята с линкора под названием "Навухудоноссор". А потом нам помог с него сбежать капитан Сид. ', en="Military types from a battleship named the \"Nebuchadnezzar\". Order I think. A certain Captain Ceed helped us escape..."),
        VoiceLine(100, King, ru="Капитан Сид...", en="Captain Ceed..."),
        VoiceLine(110, MajorScrew, ru="Капитан Сид...", en="Ceed..."),
        VoiceLine(120, Trent, ru="Потом со мной вышел на контакт агент Рокфорд. Или это я с ним на контакт вышел...", en="After that, agent Rockford contacted me. Or rather I contacted him..."),
        VoiceLine(130, King, ru="Рокфорд?", en="Rockford? Rockford who?"),
        VoiceLine(140, Trent, ru="Рокфорд. И он помог мне вернуть артефакты. Но позже оказалось, что вернуть он их хотел себе, а меня попытался уничтожить. (прикол жеж, удалось почти) И это ему почти удалось.",
                  en="Just Rockford. He helped me retrieve the artifacts. But it turned out he wanted them for himself. He turned on me and tried to murder me."),
        VoiceLine(145, Trent, ru="В итоге, в последний момент я ускользнул от него и спас вот это:", en="I managed to escape by the skin of my teeth, with the Proteus tome."),
        VoiceLine(150, King, ru="Значит Рокфорд в курсе", en="So this Rockford person knows..."),
        VoiceLine(160, MajorScrew, ru="И в игре...", en="And he's in the game"),
        VoiceLine(170, King, ru="И в игре... пока... (серьёзно) Нужно это исправить.", en="We have to fix this."),
        VoiceLine(180, MajorScrew, ru="В данный момент он скорее всего где-то в штате Нового Ордена. Нам нужен агент в Новом Ордене. Агент, который вычислит его местонахождение.",
                  en="At the moment he's lurking around in the New Order. We need someone on the inside to help us track him down."),
        VoiceLine(190, King, ru="И вы нам его обеспечите?", en="Will you provide us this elusive someone?"),
        VoiceLine(200, MajorScrew, ru="Нет, не обеспечу. Моих агентов в Ордене осталось считанные единицы, их там отстреливают как куропаток.",
                  en="No way Jose. I've only got a few assets left within the Order that haven't been compromised."),
        VoiceLine(210, King, ru="А может быть нам в этом поможет… (взгляд) мистер Трент?", en="Perhaps... Mr.Trent could be of assistance?"),
        VoiceLine(220, Hatcher, ru="Трент просрал два артефакта и звено прикрытия, и что же мы ему предложим? Стать нашим агентом в Ордене... Генерал Кинг, вы в своем уме???",
                  en="You're kidding me. Trent? The same Trent that's misplaced two crucial artifacts, squandered an entire cover squadron, earned himself wanted status in Liberty AND Rhineland... you want HIM to infiltrate the Order? He won't last a day! General King, are you out of your mind???"),
        VoiceLine(230, MajorScrew, ru="Не говоря уже о том, что скорее всего он и есть агент Ордена.", en="Yeah incompetence to this extent can't be natural. He's probably a double agent for the Order..."),
        VoiceLine(240, King, ru="А я верю в этого паренька. Трент, давай так, ты помогаешь нам, а мы чистим всю твою биографию перед СБА и платим тройной тариф.",
                  en="My gut tells me to trust him. Trent, help us do this and we'll wipe your record and pay you triple the going rate."),
        VoiceLine(250, Trent, ru="Знаете что, идите нахер, генерал Кинг. Последнее время я только и занимаюсь тем, что стараюсь улучшить репутацию и получить большие деньги. ",
                  en="You know what? No dice. Lately it feels like all I'm ever trying to do is patch up my steadily worsening reputation for some measely bucks."),
        VoiceLine(260, Trent, ru="А все заканчивается тем, что на меня начинают охоту и обвиняют во все более тяжких преступлениях. ",
                  en="But it keeps ending up with me being hunted down by entire governments and framed for treason. It's like Groundhog Day."),
        VoiceLine(270, MajorScrew, ru="Генерал Кинг, а вы не напомните, как звали того агента, которого мы внедрили в Орден до Трента?",
                  en="General King, could you remind us of the name of the previous agent we entrusted with infiltrating the Order?"),
        VoiceLine(280, King, ru="Какая разница? Связь с ним утеряна, он, скорее всего погиб.", en="What does it matter? He's offline, almost certainly dead."),
        VoiceLine(290, MajorScrew, ru="Тем не менее, генерал.", en="General, I suspect Trent will want to hear this."),
        VoiceLine(300, King, ru="Аларик. По-моему, Аларик.", en="Alaric. I think, Alaric."),
        VoiceLine(310, Trent, ru="Сволочи! Что с Алариком, гады?", en="You bastards! What happened to Alaric?"),
        VoiceLine(320, MajorScrew, ru="Мы не знаем. Связь с ним прервалась где-то на территории Кусари.", en="We lost contact with him somewhere in Kusari teritory. "),
        VoiceLine(330, Hatcher, ru="(виноватая): У него почти получилось. Он должен был передать нам базу данных, но не вышел на связь. Мы не знаем, кто наложил лапу на Аларика и его информацию.",
                  en="He was supposed to come in from the cold to us after going deep undercover but never made it. We don't know who got their hands on him and whatever information he was carrying."),
        VoiceLine(340, King, ru="(мотивирующе): Ты можешь помочь и нам и своему другу. Найди его, заверши передачу информации, которую должен был завершить твой друг - и ты свободен.",
                  en="Trent, how about this. Kill two birds with one stone. Help us, and find your friend at the same time. Retrieve the data your friend was supposed to transfer to us and you both free to go."),
        VoiceLine(345, King, ru="И не вздумай хитрить, дружище, не вздумай", en="And don't even think about doing anything heroic, just don't think. Period."),
        VoiceLine(350, Trent, ru="Ладно... ваша взяла...", en="Yeah, I can do that."),
        VoiceLine(360, King, ru="Мисс Хетчер, поднимите все данные по агенту Аларику и передайте их в распоряжение мистеру Тренту.", en="Miss Hatcher, retrieve all data on Agent Alaric and transfer it to mister Trent, please."),
        VoiceLine(370, King, ru="Далее, вашим заданием будет сопровождение тома Протея вместе с Трентом и мисс Дерси на исследовательскую базу.",
                  en="Next, your orders are to deliver the Proteus Tome along with Trent and Miss Darcy here to the research base."),
        VoiceLine(380, Hatcher, ru="Принято!", en="Yes Sir!"),
    ]

class Msn8Space(Msn8, script.SpaceVoiceProps):
    VOICE_LINES = [
        VoiceLine(0, Darcy,
                  ru='Привет, Трент! По поводу твоей просьбы... Встретимся на планете Авалон, все подробности на месте. До встречи.',
				  en="Hey, Trent! I'm good to help you with your request again... Let's meet up on planet Avalon. See you there."),
        VoiceLine(10, Darcy, ru='Трент, координаты линкора загружены в твою нейросеть. Давай быстрее.', en="Trent, the battleships' coordinates are loaded into your neural net. Step on it."),
        VoiceLine(15, Darcy, ru='После стыковки сразу готовь свой корабль к операции. Вылетай по готовности', en="Once you're docked, lock and load and prep for the mission. Launch as soon as you're ready!"),

        VoiceLine(7010, Brighton,
                  ru='В ваше задание внесены небольшие коррективы. Пришли новые данные от нашей разведки.',
				  en="Mission parameters have been adjusted. We're receiving new intelligence. Hold please.",
                  cinematic=True),
        VoiceLine(7020, Brighton,
                  ru='База ИРА в Тау-44 уничтожена, и есть подозрение, что в ее обломках нам оставили сюрприз.',
				  en="The IRA base in Tau-44 has been destroyed, and there is reason to believe that a... surprise has been left for us in the debris.",
                  cinematic=True),
        VoiceLine(7030, Brighton,
                  ru='С учетом этих обстоятельств, вам и Дерси, как частным лицам, предписывается вылететь в сектор и разобраться, что же там произошло.',
				  en="Given the circumstances, you and Darcy, operating as private contractors, are to proceed to the sector and investigate with utmost caution.",
                  cinematic=True),
        VoiceLine(7040, Trent, ru='Ну если предписывается...', en="Well, can't refuse that..."),
        VoiceLine(7050, Brighton, ru='Для вашего прикрытия я выделю отряд быстрого реагирования.', en="I'm assigning a rapid response team to your position to provide cover."),
        VoiceLine(7060, Darcy, ru='Вас поняли, адмирал.', en="Understood, Admiral."),

        VoiceLine(20, Trent, ru='Ничего себе местечко...', en="What a mess..."),
        VoiceLine(30, Darcy, ru='Нужно провести разведку. Я отмечу навигационные точки в твоей нейросети.', en="We need to scout the area. I'm marking nav points on your neural net."),
        VoiceLine(40, Trent, ru='Подозрительно тихо', en="It's too quiet..."),
        VoiceLine(50, Darcy, ru='Трент, за мной! Я, кажется, нашла базу...', en="Trent, on me! I think I've found the base..."),
        VoiceLine(60, Trent,
                  ru='Да тут целое кладбище истребителей. У меня на радаре ничего кроме металлолома. У тебя как?', en="This place is a graveyard for ships. My scanners are picking up doodly squat other than debris. You getting anything?"),
        VoiceLine(70, Darcy, ru='Аналогично. Обломки расположены очень плотно.', en="Nada. The wreckage is incredibly dense."),
        VoiceLine(80, Trent, ru='Судя по всему, их выпускали через шлюзы не штатно, не по одному, а по два.', en="Looks like they were deploying fighters through the airlocks —  in pairs!"),
        VoiceLine(90, Trent,
                  ru='Достаточно рискованный трюк, но если действовать четко и грамотно, позволяет увеличить скорость развертывания истребительных звеньев почти вдвое.',
				  en="Risky, but if executed perfectly, it would double the throughput."),
        VoiceLine(100, Darcy,
                  ru='Получается, вылетали по боевой тревоге, причем все произошло внезапно, у них не было времени на подготовку.', en="So they were scrambling on full alert for combat. Whatever happened, it was sudden. They had no time to fight back."),
        VoiceLine(110, Trent, ru='Дерси, смотри, у них тут неподалеку форпост... был...', en="Darcy, look. They had an outpost nearby..."),
        VoiceLine(120, Darcy, ru='Похоже на научную лабораторию.', en="Looks like a science lab."),
        VoiceLine(130, Trent, ru='А изучали они вот это...', en="And they were studying... That."),
        VoiceLine(140, Darcy, ru='А, кстати, что это?', en="What is... that?"),
        VoiceLine(150, Brighton, ru='Дерси, сблизьтесь с объектом и проведите сканирование.', en="Darcy, close in and run a scan on that thing."),
        VoiceLine(160, Darcy, ru='Сближаюсь...', en="Moving to proximity..."),
        VoiceLine(170, Trent, ru='А черт его знает, что это. Похоже на гигантскую летающую тарелку.', en="Hells if I know what that is. It's huge. Looks like a giant saucer. A giant... flying... saucer."),
        VoiceLine(180, Brighton,
                  ru='Мы обнаружили вход в объект. Дерси, Трент, выдвигайтесь внутрь объекта, действуйте по обстановке.',
				  en="We've located the entrance to the object. Darcy, Trent, enter and proceed as the situation dictates."),
        VoiceLine(190, Darcy, ru='Принято.', en="Acknowledged."),
        VoiceLine(200, Trent, ru='А это еще кто? Откуда здесь корабли Либерти?', en="Who are these guys? Since when does Liberty operate out here?", cinematic=True),
        VoiceLine(210, Darcy, ru='Внимание неопознанным кораблям! С вами говорит...', en="Attention, unidentified vessels! This is...", cinematic=True),
        VoiceLine(220, Darcy, ru='А, черт!', en="Ah, dammit!"),
        VoiceLine(230, Trent, ru='А они вовсе не дружелюбные.', en="So unfriendly."),
        VoiceLine(240, Trent, ru='О как. А в этой системе не жалуют долгие разговоры.', en="Seems like folks in this system aren't big on small talk."),
        VoiceLine(250, Brighton,
                  ru='Нам необходимо исследовать объект изнутри. С большой степенью вероятности, его поверхность значительно ослабляет все виды входящих и исходящих сигналов.',
				  en="Scout out the objects' interior. It's highly likely that its' hull significantly dampens all incoming and outgoing signals."),
        VoiceLine(260, Brighton,
                  ru='Звено прикрытия должно остаться у входа и работать в качестве ретрансляторов и, заодно, охранять вход на случай незваных гостей.',
				  en="Your covering wing will remain around the entrace to relay your comms and guard against any uninvited guests joining the party."),
        VoiceLine(270, Trent, ru='Принято. Дерси, я веду, прикрывай мне задницу.', en="Roger that. Darcy, I'm on point, watch my six."),
        VoiceLine(280, Darcy, ru='Окей, грех не прикрыть такую задницу.', en="Okay, with an six like that, it'd be a sin not to watch it."),
        VoiceLine(290, Darcy, ru='Эксперт, это место тебе ничего не напоминает?', en="So Mr alien expert, does this place remind you of anything?"),
        VoiceLine(300, Trent, ru='Номадская Сфера.', en="Yeah... A Nomad Sphere."),
        VoiceLine(310, Darcy, ru='Именно. Это объект кочевников.', en="Exactly. It's got to be a Nomad construct."),
        VoiceLine(320, Trent, ru='Тупик. Твои предложения?', en="Dead end. Any ideas?"),
        VoiceLine(330, Darcy, ru='Трент, нам нужно пройти через эту дверь.', en="Trent, we need to go through this door."),
        VoiceLine(340, Trent, ru='Но её нет.', en="But there is no door."),
        VoiceLine(350, Darcy, ru='Ну так сделай её.', en="Well, then make one."),
        VoiceLine(360, Trent, ru='Женщина, я начинаю тебя бояться.', en="Woman, you're starting to scare me."),
        VoiceLine(370, Darcy, ru='Ядро? А, черт...', en="A core? Ah, damn it..."),
        VoiceLine(380, Trent, ru='Это мы удачно зашли.', en="Well, this is just perfect..."),
        VoiceLine(390, Tilton,
                  ru='Трент??? А ты здесь откуда? Да еще и в компании бретонского офицера. Я вас сюда не приглашал.',
				  en="Trent??? You??? What are you doing here? And in company of a Bretonian operative!",
                  cinematic=True),
        VoiceLine(400, Trent, ru='Тилтон. Ты сам-то здесь какими судьбами? И "здесь" - это где?', en="Tilton. Why are YOU here? And what and where exactly is \"here\"?",
                  cinematic=True),
        VoiceLine(410, Tilton,
                  ru='Я расскажу, Трент. Вы только не делайте резких движений, а то мои ребята тебя с твоей бретонкой вмиг испепелят.',
				  en="Don't make any sudden moves or my boys will grind you and your Bretonian girlfriend to dust.",
                  cinematic=True),
        VoiceLine(420, Darcy, ru='"Твоей бретонкой"? Ты кто такой...', en="Bretonian girlfriend? Who the hell do you think...",
                  cinematic=True),
        VoiceLine(430, Trent, ru='Дерси, не сейчас.', en="Darcy, not now.",
                  cinematic=True),
        VoiceLine(440, Tilton,
                  ru='Да, Дерси, послушай своего голубка, целее будешь, перевес по стволам на моей стороне. Капитан Уорфиш, орудия крейсера готовы?',
				  en="Yes, silence, bitch. Now is my time. Captain Warfish, are the cruiser's batteries ready?",
                  cinematic=True),
        VoiceLine(450, CruiserCaptain, ru='Накопители заряжены на сорок три процента.', en="Capacitors charged to forty-three percent.",
                  cinematic=True),
        VoiceLine(460, Tilton,
                  ru='У нас есть пара минут, Трент. Что такое "здесь"? "Здесь" - это Логово кочевников. Какими я здесь судьбами? По поручению моего правительства.',
				  en="We have a couple of minutes then. What is \"here\"? \"Here\" is the Nomad's Lair. What are we doing here? Doing God's work. Executing our government's orders. Taking control.",
                  cinematic=True),
        VoiceLine(470, Tilton,
                  ru='Орден предал нас. Правительство Либерти покровительствовало Ордену во время его становления как никакое другое, но как только Орден вошел в силу, все это было забыто.',
				  en="The Order betrayed us. Liberty supported The Order in its infancy without constraint, without reservation... but after The Order gained power, it failed to reciprocate.",
                  cinematic=True),
        VoiceLine(480, Tilton,
                  ru='Все данные по технологиям кочевников были изъяты и засекречены верхушкой Ордена. После его раскола, нашим агентам удалось получить доступ к части архива СБА, относящейся к Логову кочевников.',
				  en="All data on Nomad technology was seized and removed from circulation by the Order's top brass. All that opportunity to leap ahead of the other governments, squandered. The Schism bought us enough disarray and confusion for our agents of ASF to appropriate information related to this place.",
                  cinematic=True),
        VoiceLine(490, Tilton,
                  ru='Это - огромный завод по производству ударных звеньев истребителей кочевников. Если я смогу его запустить, он будет бесконечно производить зерна кочевников.',
				  en="The Nomad's Lair is a massive crucible for the sole purpose of forging Nomad fighters. If we activate it, Liberty will be invincible! Unlimited Nomad Pods at our disposal! My brain trembles!",
                  cinematic=True),
        VoiceLine(500, Tilton,
                  ru='Каждое такое зерно, направленное в сторону противника, раскрывается в виде роя истребителей...',
				  en="Each pod, unfurling into a swarm of fighters... the spear of destiny, raining hellfire unto our heathen enemies!",
                  cinematic=True),
        VoiceLine(510, CruiserCaptain, ru='Накопители заряжены.', en="Sir, capacitors are fully charged.",
                  cinematic=True),
        VoiceLine(520, Tilton, ru='И вам выпала честь присутствовать при этом историческом моменте.', en="And you, Lady and not so Gentleman, have the honor of witnessing this historic moment for Liberty, for posterity!",
                  cinematic=True),
        VoiceLine(530, Darcy, ru='Сумасшедший ублюдок.', en="You're insane!",
                  cinematic=True),
        VoiceLine(540, Trent,
                  ru='Тилтон, а ты уверен, что после "запуска" все будет так, как ты сказал? Что ничего не взорвется? Что там истребители кочевников не начнут атаковать нас?',
				  en="Tilton, You don't know what it'll do! It's alien tech! Are you sure it's going to do what you think? What if the Nomad fighters can't be controlled?",
                  cinematic=True),
        VoiceLine(550, Tilton, ru='Капитан Уорфиш, огонь.', en="Silence, curs. Captain Warfish, fire at will.",
                  cinematic=True),
        VoiceLine(560, CruiserCaptain, ru='Э-ээ... Коммандер Тилтон, вы точно уверены?', en="Uh... Commander Tilton, are you quite certain? Perhaps we should...",
                  cinematic=True),
        VoiceLine(570, Tilton,
                  ru='Да! Твою мать, да! И если ты сейчас же не выстрелишь, Уорфиш, клянусь, я поднимусь к тебе на мостик и размозжу твою башку о ближайшую переборку.',
				  en="Yes! Goddammit! If you don't fire right now, Warfish, I'll have you court martialled!",
                  cinematic=True),
        VoiceLine(580, Darcy, ru='Трент, пора валить отсюда, не находишь?', en="Trent, I think this would be a good time to make ourselves scarce."),
        VoiceLine(590, Trent, ru='Полностью согласен.', en="Couldn't agree more."),

        VoiceLine(4900, Darcy, ru='У моего двигателя мощность упала почти вдвое. Какая же тут мощная гравитация.',
                  en="My engine output just halved. The gravity in here is insane."),
        VoiceLine(4910, Darcy, ru='Трент, не попади под лопасти этой странной мельницы!',
                  en="Trent, don't get caught in the blades of that damned mill thingie!"),
        VoiceLine(5000, Darcy, ru='Сейчас тут всё нахрен взорвётся! Трент, шевелись! Не отставай!',
                  en="This whole place is about to blow! Trent, move it! Don't fall behind!"),
        VoiceLine(5010, Darcy, ru='Черт! Проход закрыт! Трент, гляди! Слева еще тоннель! Летим туда!',
                  en="Damn it! The passage is blocked! Trent, look! There's another tunnel on the left! Let's go!"),
        VoiceLine(5020, Darcy, ru='Осторожно, Трент, тут эти вертящиеся мельницы.',
                  en="Watch out, Trent, more spinning mills ahead."),
        VoiceLine(5030, Darcy, ru='Чё за нафиг! Впереди двойная мельница!',
                  en="Well fuck me! Double spinning mills dead ahead!"),

        VoiceLine(600, Brighton, ru='Рад видеть вас целыми и невредимыми', en="Good to see you both in one piece."),
        VoiceLine(610, Darcy, ru='Брайтон... Линкор "Принц Уэльский"?', en="Brighton... the \"Prince of Wales\"? Really?"),
        VoiceLine(620, Brighton, ru='Мы решили вам чуточку помочь. Вытащить вас из этой передряги.', en="Thought we'd swoop in and sweep you out of this mess. The more firepower the better."),
        VoiceLine(630, Trent, ru='А вот эти ребята из Либерти с вами не согласны...', en="Well, our Liberty friends don't seem to see it as a mess..."),
        VoiceLine(640, Brighton,
                  ru='Переговоры с ребятами из Либерти беру на себя. Вы лучше скажите, что это за гадость регулярно вылетает из объекта?',
				  en="I'll get them to see reason. Why don't you tell me what those... nasty looking things that keep spewing out of that... flying saucer thing are?"),
        VoiceLine(650, Trent, ru='Зерна кочевников. У объекта спровоцировали зерноизвержение.', en="Those are Nomad seeds. They spawn fighter wings. We didn't just wake the beast... we gave it a damned seed-gasm."),
        VoiceLine(660, Brighton,
                  ru='Это большая проблема... Но наши энергетики подсказывают, что есть способ выключить это безобразие.',
				  en="That's... unfortunate. However our scientists think there may be a way to shut this hot mess down."),
        VoiceLine(670, Brighton,
                  ru='Объект перенасыщен энергией, и процесс перенасыщения продолжается. Не знаю, что там сломали эти идиоты из Либерти, но нужно срочно все исправить, иначе никому мало не покажется...',
				  en="That flying saucer... thing is overloading with energy, and charge is continuing to build. I don't know what those Liberty fools did in there, but we need to deal with it post haste, or, well... Boom. Big boom."),
        VoiceLine(680, Brighton,
                  ru='Трент, слушай внимательно. Энергия ядра объекта передается по специальным стойкам. Если их уничтожить, поступление энергии в ядро прекратится и последует разгрузка.',
				  en="Listen carefully you both. The core's energy is being channeled through dedicated conduits. Destroy the conduits and the energy flow to the core will be interrupted, forcing a discharge."),
        VoiceLine(690, Brighton, ru='Трент, Дерси, срочно уничтожьте колонны.', en="Trent, Darcy, destroy the columns, now!"),
        VoiceLine(700, Trent, ru='Понял, работаю.', en="Understood Sir, on it."),
        VoiceLine(710, Darcy, ru='Так точно!', en="Yes, sir!"),
        VoiceLine(720, Brighton, ru='Вот незадача... Всем покинуть корабль!!! Нас чуточку уничтожили...', en="All hands, abandon ship!!! We've been... a tad destroyed."),
        VoiceLine(730, Trent, ru='Дерси, уходим, сейчас все рванет!', en="Darcy, we have to leave, this whole place is about to blow!"),
        VoiceLine(740, Darcy, ru='Трент, я за тобой. Брайтон эвакуируйся с корабля, мы тебя подберем!', en="Trent, I'm right behind you. Brighton, abandon ship, we'll pick you up!"),
        VoiceLine(750, Brighton,
                  ru='Дерси, капитан покидает тонущее судно последним. Следуйте за Трентом, это приказ.',
				  en="Darcy, Captains do not abandon ship until the last man is out. You and Trent get out of here, that's an order."),
        VoiceLine(760, Darcy, ru='Брайтон, ты последний, все его уже покинули!', en="Brighton, you ARE the last man! Everyone else is off!"),
        VoiceLine(770, Brighton, ru='Дерси, иногда капитан предпочитает пойти на дно вместе со своим кораблем.', en="Sorry Darcy, I'm afraid this is goodbye."),
        VoiceLine(780, Darcy, ru='Почему, Брайтон?', en="Why are you doing this??"),
        VoiceLine(790, Brighton,
                  ru='Потому что так было с моим отцом во время восьмидесятилетней войны, с моим дедом, во время предыдущей войны и прадедом во время войны, которую уже никто не помнит.',
				  en="My father died during the Eighty Years' War. My grandfather died in the war before that. And my great-grandfather, in a war nobody even remembers anymore. It is an honour to go down with my ship, like my father, and his father's father before him. And well, there's a small matter of me giving my escape pod to my first mate earlier."),
        VoiceLine(800, Brighton, ru='Ребятки, уходите отсюда как можно дальше, сдается мне, сейчас чуточку рванет...', en="Get as far away from here as you can, kids. I have a feeling things are about to get... a little warm..."),
        VoiceLine(810, Darcy,
                  ru='Трент, Брайтон был единственным... Единственным человеком... Единственным стоящим человеком среди всех этих...',
				  en="Trent, Brighton was the only... The only man... The only decent man among all the...",
                  cinematic=True),
        VoiceLine(820, Trent, ru='Я понимаю, Дерси, но нам надо...', en="I know, Darcy, I know. Look, we need to...",
                  cinematic=True),
        VoiceLine(830, Hatcher, ru='Вам надо замереть на месте и даже не дышать.', en="What you need to do is freeze. Don't even breathe.",
                  cinematic=True),
        VoiceLine(840, Trent, ru='Хетчер.', en="Hatcher, is that you?",
                  cinematic=True),
        VoiceLine(850, Hatcher, ru='Мистер Трент. Вы меня не забыли?', en="Mister Trent. You haven't forgotten me, I hope?",
                  cinematic=True),
        VoiceLine(860, Trent, ru='Мисс Хетчер, вы незабываемы.', en="Miss Hatcher, I could never forget you even if I tried.",
                  cinematic=True),
        VoiceLine(870, Hatcher,
                  ru='Ну ты и засранец, Трент. Красный-один, держите этого персонажа на мушке, если рыпнется - разрешаю открыть огонь на поражение. Отвечаешь за него головой...',
				  en="You're a real piece of work, Trent. Red Leader, keep your sights trained on this scoundrel. If he so much as twitches a muscle, you are weapons-free. You read?",
                  cinematic=True),
        VoiceLine(880, RedLeader, ru='Принял.', en="Copy that.",
                  cinematic=True),
        VoiceLine(890, Hatcher,
                  ru='Итак, что тут случилось? И, Трент, почему, стоит мне увидеть на горизонте прорыв какого-нибудь дерьма, ты обязательно оказываешься рядом? Ты ассенизатор? Сантехник? КТО ТЫ, ТВОЮ МАТЬ???',
				  en="So, what exactly happened here? And Trent, tell me why it is every time that shit hits the fan you show up like a bad penny? Are you a shit-magnet? A shit-stirrer? JUST WHO THE HELL ARE YOU?!",
                  cinematic=True),
        VoiceLine(900, Darcy,
                  ru='Наверное, лучше я расскажу. Один из ваших - коммандер Тилтон - решил запустить фабрику кочевников по производству боевых истребителей.',
				  en="Perhaps it'd be best if I explain. One of your men — Commander Tilton — attempted to activate this monstrous Nomad facility. Ostensibly it was going to churn out a ceaseless supply of Nomad fighters to quote unquote rain hellfire upon the heathen enemies. Classic small man syndrome.",
                  cinematic=True),
        VoiceLine(910, Darcy,
                  ru='Но вместо этого перегрузил ее и пустил вразнос, при этом погиб его крейсер, линкор "Принц Уэльский" пришедший к нам на выручку, и куча людей с обеих сторон.',
				  en="Frankly, he seemed quite mad, manic, or both. Since he clearly had no idea what he was doing, the facility overloaded. The resulting catastrophic chain-reaction culminated in a massive explosion which obliterated him, his ships, and his men. And a Bretonian battleship, the Prince of Wales, captained by a friend of mine.",
                  cinematic=True),
        VoiceLine(920, Hatcher,
                  ru='Тилтон... Больной ублюдок с манией величия... Я надеюсь, он мучился перед смертью.',
				  en="Tilton... That megalomaniac... he finally went too far. Sigh. On behalf of Liberty, please accept my condolences for your loss. My thoughts and prayers are with you.",
                  cinematic=True),
        VoiceLine(930, Hatcher,
                  ru='Хорошо. Вы проследуете со мной до нашей базы. Красный-один, вы остаетесь рядом с обломками объекта, начните поверхностное изучение, я пришлю вам с базы яйцеголовых в помощь.',
				  en="Okay. Now that that's done. You two follow me to base to debrief. Red Leader, stay here and start a preliminary survey of the debris. I'll despatch some eggheads from base later for the scientific survey.",
                  cinematic=True),
        VoiceLine(940, RedLeader, ru='Так точно!', en="Yes, ma'am!",
                  cinematic=True),
        VoiceLine(950, Hatcher, ru='Дерси, вы успели побывать внутри объекта до его активации?', en="Darcy, were you inside the facility when it activated?"),
        VoiceLine(960, Darcy, ru='Да.', en="Yes."),
        VoiceLine(970, Hatcher, ru='Не приходит на ум никаких аналогий между увиденным там и...', en="Did you see anything inside there that reminded you of..."),
        VoiceLine(980, Trent, ru='Хетчер, может спросишь у меня?', en="Hatcher, I was there too. You can ask me."),
        VoiceLine(990, Hatcher,
                  ru='Я? Нет, на базе тебя будет допрашивать группа гораздо более умелых людей. И допросят тебя с пристрастием, не сомневайся.',
				  en="You? Someone else is going to be asking you questions. Someone very meticulous, with very specialized skills and fascinating pointy implements not-quite designed to explore... organic orifices. It will be a very, I assure you, thorough and painful experience."),
        VoiceLine(1000, Darcy, ru='Где это мы? Энтерпрайз?', en="Is this The Enterprise?"),
        VoiceLine(1010, Hatcher, ru='Да. Основная база СБА.', en="Yes. ASF headquarters. We don't allow guests, ever."),
        VoiceLine(1020, Darcy, ru='Шансы на то, что меня отсюда выпустят живой близятся к нулю.', en="My chances of leaving this place alive appear to be dwindling rapidly."),
        VoiceLine(1030, Hatcher, ru='Это будет зависеть от тебя.', en="Well, that depends entirely on you."),
        VoiceLine(1040, Trent, ru='Это будет зависеть от хозяев мисс Хетчер.', en="By which she means her superiors are going to make you walk the gangplank."),
        VoiceLine(1050, Darcy, ru='Я думала, Энтерпрайз - это станция, а оказалось, это - целая система.', en="I always imagined that the Enterprise would be a station! Turns out it's an entire star system."),
        VoiceLine(1060, Trent, ru='Зря ты это сказала. Теперь тебя точно не выпустят отсюда живой.', en="You shouldn't have said that. Super classified. Now you're never making it out of here. Gangplank."),
        VoiceLine(1070, Hatcher, ru='Не обращайте внимания на Трента, он, по своему обыкновению, паясничает.', en="Ignore Trent. He's just clowning around, as usual."),
        VoiceLine(1080, Trent, ru='А что, нас даже не убьют?', en="You're hurting my feelings."),
        VoiceLine(1090, Hatcher, ru='Если бы моя воля - то непременно, а так - как себя вести будете.', en="You picked up on it. Good job."),
        VoiceLine(1100, Trent, ru='Хетчер, теперь ты можешь мне спокойно рассказать, что же произошло с Алариком?', en="Hatcher, do you know what happened to Alaric?"),
        VoiceLine(1110, Hatcher,
                  ru='Могу, но тебе не понравится. Когда ты исчез в неизвестном направлении, Аларик, как будто взбесился.',
				  en="Yes, but you're not going to like it. After you disappeared, Alaric went... berserk."),
        VoiceLine(1120, Hatcher,
                  ru='Говорил, что его друг - герой, и он должен соответствовать. Его было решено использовать как агента в Ордене.',
				  en="Kept ranting about how his friend had died a hero and that he had to measure up in turn. We uhh exploited his grief to enlist him to infiltrate and spy on The Order."),
        VoiceLine(1130, Hatcher,
                  ru='Тем более, что такой обалдуй прижился там буквально сразу же. Перед тем как связь оборвалась, он обещал нам переслать некие секретные документы, но мы их так и не получили.',
				  en="Suprisingly, the fool managed to hit it off with them. Just before comms went dead, he promised to send us some secret documents, but then... you know the rest."),
        VoiceLine(1140, Hatcher,
                  ru='Мы в системе Сириус. Направляемся к планете Спрага. Мисс Дэрси, не могли бы вы связаться с вашим штабом и рассказать про бой в Тау-44.',
				  en="We're in the Sirius system, en-route to the planet Sprague. Miss Darcy, could you contact your superiors and brief them about the engagement in Tau-44?"),
        VoiceLine(1150, Darcy, ru='Уже. Мое начальство одобрило сотрудничество с СБА и с вами конкретно.', en="Already done. They've green-lighted full cooperation with the ASF, and specifically, with you, ma'am."),
        VoiceLine(1160, Trent, ru='Какая милота. Я вам не мешаю?', en="Ooh sexy. Can I watch, later."),
        VoiceLine(1170, Darcy, ru='Трент, не будь ребенком.', en="Trent, grow up."),
    ]


class Msn8PrinceWales(Msn8, script.CutsceneProps):
    ALIAS = 'prince_wales'
    TITLE = 'Линкор Принц Уэльский'
    THORN_CLASS = m08.PrinceWalesScene
    DESCRIPTION = ''
    VOICE_LINES = [
        VoiceLine(10, Darcy, ru="Трент,, давай готовь корабль, мы почти приблизились к точке вылета.", en="Trent, get your ship ready, we've almost reached the launch point."),
        VoiceLine(20, Trent, ru="Что,, уже не будет никакого брифинга?", en="What, no briefing at all?"),
        VoiceLine(30, Darcy, ru="Из тау-44 приходят противоречивые данные. Будем действовать по обстановке.", en="We're getting conflicting data from Tau-44. We'll have to play it by ear."),
        VoiceLine(40, Trent, ru="Значит будем импровизировать?", en="So we're improvising?"),
        VoiceLine(50, Darcy, ru="Именно так.", en="Exactly."),
    ]


class Msn8Sprague(Msn8, script.CutsceneProps):
    ALIAS = 'sprague'
    TITLE = 'Планета Спрага'
    THORN_CLASS = m08.SpragueScene
    DESCRIPTION = ''
    VOICE_LINES = [
        VoiceLine(10, Mandrake, ru="Рад снова вас видеть, мистер Трент!", en="Glad to see you again, Mr. Trent."),
        VoiceLine(20, Mandrake, ru="Хорошо, что вы смогли доставить до нас хотя бы Том Про́тэуса. Теперь он точно будет в безопасности.", en="It's good that you managed to deliver at least the Proteus tome to us. Now it will definitely be safe."),
        VoiceLine(30, Trent, ru="К вашим услугам, профессор. Я тоже рад вас видеть.", en="At your service, Professor. I'm glad to see you too."),
        VoiceLine(40, Mandrake, ru="Кстати,, мистер Трент, у Ордена не было еще каких-либо артефактов?", en="By the way, Mr. Trent, did the Order have any other artifacts?"),
        VoiceLine(50, Trent, ru="Ну был какой-то кристалл,, который я разбил. После этого я очутился на друг+ом конце Сириуса в Бретонии.", en="Well, there was some crystal that I broke. After that, I found myself on the other end of Sirius, in Bretonia."),
        VoiceLine(60, Mandrake, ru="(удивление учёного!) А, так вот как он работает!", en="Ah, so that's how it works!"),
        VoiceLine(70, Trent, ru="Что-то не так,, профессор?", en="Is something wrong, Professor?"),
        VoiceLine(80, Mandrake, ru="Мы проводили несколько экспериментов и этот артефакт просто испарялся. Мы пробовали на людях. И они испарялись вместе с артефактом...", en="We ran several experiments, and that artifact simply evaporated. We tried it on people. And they evaporated along with the artifact..."),
        VoiceLine(90, Mandrake, ru="Вам повезло,, что вы оказались в обитаемой системе, а не в пустом космическом пространстве в тысяче световых лет от цивилизованных систем.", en="You were lucky to end up in an inhabited system, rather than in empty space a thousand light-years from civilized systems."),
        VoiceLine(100, Trent, ru="Значит я очень большой везунчик. Можно даже сказать,, что родился в рубашке дважды.", en="So I'm a very lucky guy. You could even say I was born under a lucky star twice over."),
        VoiceLine(110, Hatcher, ru="Вот чёрт,, Трент, ты действительно спасся чудом.", en="Damn, Trent, you really escaped by a miracle."),
        VoiceLine(120, Trent, ru="Что там по Ордену дальше,, Хетчер?", en="What's next with the Order, Hatcher?"),
        VoiceLine(130, Hatcher, ru="Пока ничего, буду наводить справки. Я сообщу,, когда всё будет готово. А пока развлекайся. Я выдам тебе небольшую компенсацию за моральный ущерб.", en="Nothing yet, I'll keep asking around. I'll let you know when everything is ready. Meanwhile, have fun. I'll give you a small compensation for emotional distress."),
        VoiceLine(140, Trent, ru="А что там по обещанным двухсотпятидесяти тысячам?", en="And what about the promised two hundred and fifty thousand?"),
        VoiceLine(150, Hatcher, ru="Посмотрим,, как у тебя получится достать второй артефакт у Рокфорда. Если всё пойдёт хорошо,, то я обещаю тебе еще бонус сверху.", en="We'll see how you manage to get the second artifact from Rockford. If everything goes well, I promise you an extra bonus on top."),
        VoiceLine(160, Trent, ru="Опять обещания... И куда это на всех ещё заведёт...", en="Promises again... And where will that lead everyone..."),
        VoiceLine(170, Trent, ru="Ладно,, бывайте. Займусь реальной работой. Жду звонка.", en="Alright, take care. I'll get to some real work. Waiting for your call."),
    ]


class Mission8(Msn8, script.StoryMission):
    MISSION_INDEX = 8
    CUTSCENES = [
        Msn8Offer,
        Msn8PrinceWales,
        Msn8Osiris,
        Msn8Sprague,
    ]
    SPACE_CLASS = Msn8Space
    SYNC_SPACE = True
    SYNC_SUBS = True

    MISSION_TITLE = 'Миссия 8. Эксперт по Кочевникам'
